fix(annotation): text annotation re-render will be hidden
antvis/G2 pull request #2916
Opened 2020-10-15 01:34 UTC by hustcc

- [x] 因为非 regionFilter 的 annotation 被重绘了一遍，导致被隐藏。

2020-10-15 01:49 UTC, Me-Momo commented on tests/bugs/2851-spec.ts
>      // regionFilter 不知道怎么去断言！
🤔

2020-10-15 12:33 UTC, hustcc commented on tests/bugs/2851-spec.ts
>      // regionFilter 不知道怎么去断言！
真的不知道。

2020-10-15 12:46 UTC, Me-Momo requested changes

2020-10-15 12:46 UTC, Me-Momo commented on src/chart/controller/annotation.ts
> +        newCache.set(key, co);
这段代码，if-else做的事情不是一样吗

2020-10-15 12:47 UTC, Me-Momo commented
> * [x]  因为非 regionFilter 的 annotation 被重绘了一遍，导致被隐藏。

重绘的时候，为什么会隐藏

2020-10-16 06:37 UTC, hustcc commented
> > * [x]   因为非 regionFilter 的 annotation 被重绘了一遍，导致被隐藏。
> 
> 重绘的时候，为什么会隐藏

我也不知道，直接调用 re-render 也不会出现问题。-_-

2020-10-16 06:37 UTC, simaQ approved these changes

2020-10-16 06:44 UTC, Me-Momo approved these changes

2020-10-16 06:44 UTC, merged