fix(funnel): pyramid shape 最下面一层的 label 绘制不对齐
antvis/G2 pull request #3585
Opened 2021-08-23 08:17 UTC by pearmini

**漏斗图最下面一层的绘制问题**

出现问题的原因应该是 registerShape 的 getPoints 对于 pyramid 的最下面一层只返回了三个点，导致布局计算错误。所以解决办法就是 getPoints 的方法不论是不是 pyramid 都返回相同的 points，只是在渲染的时候区别一下就好。

<img width="563" alt="截屏2021-08-23 下午4 03 32" src="https://user-images.githubusercontent.com/49330279/130413539-987a3fcb-e507-4dc1-a28e-f49655be9eb3.png">

2021-08-23 08:19 UTC, hustcc commented on src/geometry/shape/interval/util.ts
> +  points.push({ x: xMax, y: yMax }, { x: xMax, y: yMin });
isPyramid 的判断没有用？

2021-08-23 08:20 UTC, hustcc commented on src/geometry/shape/interval/util.ts
> +  points.push({ x: xMax, y: yMax }, { x: xMax, y: yMin });
测试一下 isPyramid 和 !isPyramid 两种情况，图形上肯定是又一些区别的。

2021-08-23 08:21 UTC, pearmini commented on src/geometry/shape/interval/util.ts
> +  points.push({ x: xMax, y: yMax }, { x: xMax, y: yMin });
哦哦哦，我去删掉😭

2021-08-23 08:30 UTC, pearmini commented on src/geometry/shape/interval/util.ts
> +  points.push({ x: xMax, y: yMax }, { x: xMax, y: yMin });
之前的代码中 getPoints 在 `isPyramid === true` 的时候只返回一个点，然后在 getFunnelPath 中会区别的生成 path；现在不管 isPyramid 是否为 true 都生成相同的控制点，然后在 getFunnelPath 区别的生成 path

2021-08-23 08:30 UTC, pearmini commented on src/geometry/shape/interval/util.ts
> +  points.push({ x: xMax, y: yMax }, { x: xMax, y: yMin });
是需要加入一个 isPyramid === false 情况下的单测吗？

2021-08-24 12:52 UTC, hustcc commented on tests/bugs/funnel-pyramid-spec.ts
> +    console.log(labelItems)
删除。最后实例destroy

2021-08-24 12:53 UTC, hustcc approved these changes

2021-08-24 13:03 UTC, hustcc submitted a review, later dismissed

2021-08-24 15:07 UTC, visiky requested changes

2021-08-24 15:07 UTC, visiky commented on package.json
> +  "version": "4.1.25",
core.ts 中的版本号 也需要同步更新。另外，需要 changelog，建议新起 pr

2021-08-25 02:45 UTC, pearmini commented on package.json
> +  "version": "4.1.25",
我暂时还是在这个分支修改的，因为感觉再起一个分支 ci 又要跑好久 😭

2021-08-25 03:25 UTC, visiky approved these changes

2021-08-25 03:25 UTC, merged