feat(axis): 添加坐标轴标题详细说明 icon 交互事件
antvis/G2 pull request #3863
Opened 2022-04-12 09:43 UTC by zhangjunjie-loki

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Description of change
为 icon 添加鼠标 hover 事件，当 mousemove 到 icon 上出现详情信息 tooltip，当 mouseleave 时 tooltip 消失。

<img width="500" alt="image" src="https://user-images.githubusercontent.com/95538236/162931001-0f872234-6e78-479c-b575-d03249268371.png">

2022-04-12 10:21 UTC, visiky requested changes

2022-04-12 10:21 UTC, visiky commented on package.json
> +    "@antv/component": "^0.8.27",
其实不需要更新的

2022-04-12 10:21 UTC, visiky commented on src/chart/chart.ts
> +      defaultInteractions = ['tooltip', 'legend-filter', 'legend-active', 'continuous-filter', 'ellipsis-text', 'axis-description'],
建议默认不添加，需要的时候 自己添加就行了

2022-04-12 12:16 UTC, zhangjunjie-loki commented
- 完成 tooltip 样式修改，padding 变小：
<img width="300" alt="image" src="https://user-images.githubusercontent.com/95538236/162960146-028b6cd2-2c15-4c4c-8bff-8f7d6be76e30.png">

- 当描述信息过长时，按照 ellipsis-text 逻辑换行：
<img width="300" alt="image" src="https://user-images.githubusercontent.com/95538236/162960491-399f8469-d281-4511-9618-cd74fb6243d4.png">

2022-04-13 02:46 UTC, visiky approved these changes

2022-04-13 02:46 UTC, merged