feat: draw point shapes with Path
antvis/G2 pull request #3947
Opened 2022-05-28 10:07 UTC by hustcc

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Description of change

2022-05-28 13:41 UTC, pearmini requested changes
很及时！正好我需要用一些 shape 做 transform 的案例！可以顺手处理一下 CI 的问题，估计是 @antvis/g 升级导致单测报错了😆

2022-05-28 13:41 UTC, pearmini commented on src/shape/point/symbol.ts
> +
这个地方可以统一成英文！

2022-05-30 01:46 UTC, hustcc commented
> 很及时！正好我需要用一些 shape 做 transform 的案例！可以顺手处理一下 CI 的问题，估计是 @antvis/g 升级导致单测报错了😆

因为 node_modules cache 的问题，本地跑没有问题，我想去掉 node module cache 咋样？

2022-05-30 05:24 UTC, pearmini commented
> > 很及时！正好我需要用一些 shape 做 transform 的案例！可以顺手处理一下 CI 的问题，估计是 @antvis/g 升级导致单测报错了😆
> 
> 因为 node_modules cache 的问题，本地跑没有问题，我想去掉 node module cache 咋样？

好的

2022-05-30 05:48 UTC, merged