feat(title): support title component
antvis/G2 pull request #3956
Opened 2022-06-01 06:24 UTC by visiky

**Feat:** support title component

### Usage

```ts
type Title = string | null | G2TitleOptions;
// ① simple
{
   title: 'xxx',
}
// ②
{
  title: {
     text: 'xxx',
     style: {},
     subtitle: 'xxx',
     subtitleStlye: {}
  }
}
```

- Options specified by users will be transformed to standard `G2TitleOptions`

```ts
type G2Title = {
  text?: string;
  subtitle?: string | null;
  style?: Record<string, any>;
  subtitleStyle?: Record<string, any>;
};

type G2TitleOptions = G2Title & {
  position?: GuideComponentPosition;
  size?: number;
  zIndex?: number;
};
```

### Demo

#### In `Mark` composition

① simple usage

```ts
render<G2Spec>(
    {
      type: 'interval',
      title: 'Chart Title',
      data,
      encode: {
        x: 'genre',
        y: 'sold',
      },
    },
    {},
    done,
  );
```

② config title, subtitle and subtitleStlye

<img width="631" alt="image" src="https://user-images.githubusercontent.com/15646325/171340188-56dd6038-8cba-4c61-aec7-872b1af00c4b.png">

```ts
render<G2Spec>(
  {
    type: 'interval',
    title: {
      size: 40,
      text: 'Chart Title',
      subtitle: 'Chart Subtitle: description, description.',
      subtitleStyle: { fill: 'pink' },
    },
    data: [
      { genre: 'Sports', sold: 275 },
      { genre: 'Strategy', sold: 115 },
      { genre: 'Action', sold: 120 },
      { genre: 'Shooter', sold: 350 },
      { genre: 'Other', sold: 150 },
    ],
    paddingRight: 80,
    scale: { color: { guide: { position: 'right', size: 80 } } },
    encode: {
      x: 'genre',
      y: 'sold',
      color: 'genre',
    },
  },
  {},
  done,
)
```

#### In `View` composition

<img width="629" alt="image" src="https://user-images.githubusercontent.com/15646325/171339645-eee9879a-5b23-486e-947c-ab0d677d653c.png">

```ts
render<G2Spec>({
  type: 'view',
  title: {
    text: 'View Composition',
    subtitle: 'Description of chart.',
  },
  data,
  paddingRight: 80,
  scale: {
    color: { guide: { position: 'right', size: 80 } },
  },
  children: [
    {
      type: 'line',
      data,
      encode: {
        x: 'month',
        y: 'temperature',
        color: 'city',
      },
    },
    {
      type: 'point',
      data,
      encode: {
        x: 'month',
        y: 'temperature',
        color: 'city',
      },
    },
  ],
});
```

#### In `Rect` composition

<img width="899" alt="image" src="https://user-images.githubusercontent.com/15646325/171339227-3628ff52-53fa-49b5-8766-547d1cfbdbd6.png">

```ts
render<G2Spec>(
  {
    transform: [
      {
        type: 'fetch',
        url: 'https://gw.alipayobjects.com/os/bmw-prod/a0f96c54-d1fa-46c8-b6ef-548e2f700a6d.json',
      },
    ],
    type: 'rect',
    width: 928,
    height: 240,
    paddingLeft: 50,
    paddingBottom: 50,
    title: {
      text: 'Facet',
      subtitle: 'Description of chart.',
    },
    encode: {
      x: 'series',
    },
    scale: {
      x: { guide: { size: 30 } },
    },
    children: [
      {
        type: 'point',
        encode: {
          x: 'x',
          y: 'y',
          shape: 'hollowPoint',
        },
      },
    ],
  },
  {},
  done,
);
```

2022-06-02 06:17 UTC, pearmini requested changes
突然感觉这个 API 的设计可以简洁一点：

```js
// Simple
const config = {
  title: 'hello world';
}
```
```js
// Complex
const config = {
  title: {
    main: 'Title',
    sub: 'Description',
    mainStyle: {},
    subStyle: {}
  }
}
```

2022-06-02 07:52 UTC, visiky commented
先确定为:
```ts
{
    title: {
       text?: string;
       style?: {};
       subtitle?: string;
       subtitleStyle?: {};
    }
}
```

2022-06-06 13:54 UTC, pearmini requested changes

2022-06-07 00:45 UTC, visiky commented on src/runtime/component.ts
> +      : 0)
您看，现在好多了吗？

2022-06-07 02:22 UTC, pearmini requested changes

2022-06-07 02:22 UTC, pearmini commented on src/runtime/component.ts
> +  const spacing = get(subtitleStyle, 'spacing', 0);
没有必要用 get 吧，之后 antv/util 本来就不会使用了。

```js
const titleSize = style?.fontSize || 14;
```

2022-06-07 08:01 UTC, merged