feat: add zoom-in zoom-out cursor
antvis/G2 pull request #3976
Opened 2022-06-11 09:15 UTC by naoyashiga

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] commit message follows commit guidelines

##### Description of change

You can use zoomIn and zoomOut cursor in register-interaction. 

This is useful. For example, you use scale-transform zooming.
```js
registerInteraction('custom-zoom', {
  showEnable: [
    { trigger: 'plot:mouseenter', action: 'cursor:zoomIn' },
    { trigger: 'plot:mouseleave', action: 'cursor:zoomOut' },
  ],
});
```

2022-06-11 09:18 UTC, naoyashiga commented
It may be strange chinese explanation in documents because I'm not native Chinese speaker.

```
光标显示可以被放大
光标显示可以缩小尺寸
```

If it needs modification, please tell me correct explations.

2022-06-12 02:28 UTC, hustcc commented on tests/unit/interaction/action/cursor-spec.ts
> +  const zoomCursors = ['In', 'Out'];
直接放到 cursors 数组中可以吗？

2022-06-13 13:19 UTC, naoyashiga commented on tests/unit/interaction/action/cursor-spec.ts
> +  const zoomCursors = ['In', 'Out'];
If I add zoomIn and zoomOut to cursors, I need to logics for zoom in cursors each loop.
https://github.com/antvis/G2/blob/67e80988d8e848bb1e336402fd7e9ac4498a42b5/tests/unit/interaction/action/cursor-spec.ts#L37-L40

resizeArr is not in cursors and have different test code （'test resize cursors'）. I wrote zoomCursors like this.

2022-06-28 02:24 UTC, hustcc requested changes

2022-06-28 02:24 UTC, hustcc commented on tests/unit/interaction/action/cursor-spec.ts
> +  const zoomCursors = ['In', 'Out'];
> const  cursors = ['default', 'crosshair', 'pointer', 'move', 'wait', 'help', 'text', 'zoom-in', 'zoom-out'];

2022-06-28 02:25 UTC, hustcc commented
Good job, in the test case, you can combine `cursors` and `zoomCursors ` into only one array.

2022-07-04 05:25 UTC, visiky commented on tests/unit/interaction/action/cursor-spec.ts
> +  const zoomCursors = ['In', 'Out'];
no need to add this variable, just add the test caes like:
```ts
 it('zoom cursor', () => {
    each(['zoom-in', 'zoom-out'], (cursor: string) => {
     const method  = cursor.split('-')[1];
      action[`zoom${method.toUpperCase()}`]();
      expect(canvas.getCursor()).toBe(cursor);
    });
  });
```

2022-07-21 04:40 UTC, merged