feat(interaction): support element-highlight interactions
antvis/G2 pull request #3992
Opened 2022-06-18 14:55 UTC by visiky

### Features
- **feat(service action):** `elementSelection` (support filterBy: `x` or `color`)
- **feat(transformer action):** `highlight`

- **feat(interaction):** `elementHighlight`, `elementHighlightByX`, `elementHighlightByColor`

### Demo

<img width="609" alt="image" src="https://user-images.githubusercontent.com/15646325/174443813-3e920191-b011-435f-ac5e-31bee00a890e.png">

```ts
render<G2Spec>(
    {
      type: 'view',
      data: [
        { genre: 'Sports', sold: 275, type: 'A' },
        { genre: 'Sports', sold: 115, type: 'B' },
        { genre: 'Strategy', sold: 115, type: 'A' },
        { genre: 'Strategy', sold: 95, type: 'B' },
        { genre: 'Action', sold: 120, type: 'A' },
        { genre: 'Action', sold: 190, type: 'B' },
        { genre: 'Shooter', sold: 350, type: 'A' },
        { genre: 'Shooter', sold: 250, type: 'B' },
      ],
      title: 'ElementHighlight',
      scale: {
        x: { flex: [1, 2, 3, 4] },
      },
      children: [
        {
          type: 'interval',
          encode: {
            x: 'genre',
            y: 'sold',
            color: 'type',
          },
          scale: {
            color: { guide: { title: null } },
          },
        },
      ],
      interaction: [{ type: 'elementHighlight' }],
    },
  );
```

<img width="607" alt="image" src="https://user-images.githubusercontent.com/15646325/174443826-61977d5a-6039-402f-a741-33b27ae4b5e1.png">

```ts
render<G2Spec>(
    {
      type: 'view',
      data: [
        { genre: 'Sports', sold: 275, type: 'A' },
        { genre: 'Sports', sold: 115, type: 'B' },
        { genre: 'Strategy', sold: 115, type: 'A' },
        { genre: 'Strategy', sold: 95, type: 'B' },
        { genre: 'Action', sold: 120, type: 'A' },
        { genre: 'Action', sold: 190, type: 'B' },
        { genre: 'Shooter', sold: 350, type: 'A' },
        { genre: 'Shooter', sold: 250, type: 'B' },
      ],
      title: 'elementHighlightByColor',
      scale: {
        x: { flex: [1, 2, 3, 4] },
      },
      children: [
        {
          type: 'interval',
          encode: {
            x: 'genre',
            y: 'sold',
            color: 'type',
          },
          scale: {
            color: { guide: { title: null } },
          },
        },
      ],
      interaction: [{ type: 'elementHighlightByColor' }],
    },
  );
```

<img width="613" alt="image" src="https://user-images.githubusercontent.com/15646325/174443845-c9a409ee-f51b-453d-a935-5410fdd5f482.png">

```ts
render<G2Spec>(
    {
      type: 'view',
      data: [
        { genre: 'Sports', sold: 275, type: 'A' },
        { genre: 'Sports', sold: 115, type: 'B' },
        { genre: 'Strategy', sold: 115, type: 'A' },
        { genre: 'Strategy', sold: 95, type: 'B' },
        { genre: 'Action', sold: 120, type: 'A' },
        { genre: 'Action', sold: 190, type: 'B' },
        { genre: 'Shooter', sold: 350, type: 'A' },
        { genre: 'Shooter', sold: 250, type: 'B' },
      ],
      title: 'ElementHighlightByX',
      scale: {
        x: { flex: [1, 2, 3, 4] },
      },
      children: [
        {
          type: 'interval',
          encode: {
            x: 'genre',
            y: 'sold',
            color: 'type',
          },
          scale: {
            color: { guide: { title: null } },
          },
        },
      ],
      interaction: [{ type: 'elementHighlightByX' }],
    },
  );
```

2022-06-20 06:31 UTC, hustcc commented on src/action/service/elementSelection.ts
> +          const { __data__: data } = select(target).node();
有的地方重命名为 data，有的地方是 datum。

2022-06-20 06:44 UTC, hustcc commented on src/action/service/elementSelection.ts
> +    const { event, shared, selection, scale: scales } = context;
nit：可以看后面交互填充多了之后，看怎么处理好。

shared 的数据结构如果是确定的，那么就可以封装一下，并提供固定的对他进行操作的方法。

2022-06-20 07:02 UTC, pearmini requested changes
大部分都没有问题，很棒！但有两个小点需要确认一下：

- Action 的名字应该是 _动词 + 名字_ 的形式，比如 elementSelection -> selectElement ？
- elementSelection 和 surfacePointSelection 的定位有啥区别吗？

还有就是这个 PR 估计等这个 https://github.com/antvis/G2/pull/3993 合并之后再合并？因为有一些不兼容的变化。

2022-06-20 07:07 UTC, visiky commented on src/action/transformer/highlight.ts
> +}
怎么理解？

2022-06-21 04:26 UTC, visiky commented on src/action/transformer/highlight.ts
> +}
这里是设置高亮样式的，后续的话，要从 theme 中获取，也不算是工具函数了

2022-06-21 04:51 UTC, pearmini requested changes

2022-06-21 04:51 UTC, pearmini commented on src/interaction/action/transformer/highlight.ts
> +}
把这种辅助函数的声明都放在组件声明的前面？

2022-06-21 05:23 UTC, hustcc approved these changes

2022-06-21 05:28 UTC, merged