feat(interaction): support legend interaction
antvis/G2 pull request #3994
Opened 2022-06-21 08:46 UTC by visiky

#### Featrues

- service: `legendItemSelection`, `triggerInfoSelection`
- transformer: `setItemState`
- interactions: `legendActive`, `legendHighlight`

#### Interactions

![legend-active](https://user-images.githubusercontent.com/15646325/174757655-2223d2f3-e12d-4714-af56-869417021036.gif)

![legend-highlight](https://user-images.githubusercontent.com/15646325/174757688-c3e9f894-1705-4bbd-a30a-a2816b8de54d.gif)

2022-06-22 02:45 UTC, pearmini commented
关于 Action 有两个问题：

- 高亮 element 是 highlightSelection，为啥高亮 legend 就变成了 setItemState？这两个得统一吧，要么高亮 element 也是 setSelectionState，要么高亮 legend 也是 HighlightItem 或者 HighlightLegendItem。
- 为什么 LegendActive 里面是 highlightSelection，到了 LegendHighlight 和 ElementListHighlight 又变成了 highlight？这两个有啥区别

2022-06-22 02:47 UTC, visiky commented
https://www.yuque.com/antv/g2-docs/interaction-plan#wUNZk

<img width="653" alt="image" src="https://user-images.githubusercontent.com/15646325/174932541-e341b61c-a67a-4098-932d-b867371ffc4f.png">

2022-06-22 02:52 UTC, pearmini requested changes

2022-06-22 02:52 UTC, pearmini commented on src/component/legendCategory.ts
> +              fill: '#d8d8d8',
为啥 legend 又有状态了？GUI 需要有状态嘛？

2022-06-22 02:52 UTC, pearmini commented on src/interaction/action/service/legendItemSelection.ts
> +      );
有的地方解构，有的地方不考虑是，这样目的是？

2022-06-22 03:11 UTC, pearmini approved these changes

2022-06-22 04:10 UTC, visiky commented
需要修改的点：
1、图例不需要状态（需要考虑图例的交互该如何处理，直接操作 legendItem，还是增加 selectionLayer？）
2、element 关于状态的交互反馈，是否区分 active、highlight、selected，还是合并？具体命名逻辑？

2022-06-23 00:43 UTC, visiky commented on src/interaction/action/service/legendItemSelection.ts
> +      );
是我没有考虑太多 [🤦‍♀️😭] 要不都统一解构？还是？

2022-06-23 03:08 UTC, pearmini commented on src/interaction/action/service/legendItemSelection.ts
> +      );
这个可以后续讨论一下，比如统一解构，或者是需要获得某个对象多个 value 的时候再解构？

2022-06-23 03:16 UTC, pearmini requested changes

2022-06-23 03:16 UTC, pearmini commented on src/interaction/action/service/triggerInfoSelection.ts
> +    if (!multiple) triggerInfo = [];
这可以把 let 去掉？
```js
const triggerInfo = multiple ? (shared.triggerInfo || []) : [];
```

2022-06-23 06:31 UTC, visiky commented on src/interaction/action/service/triggerInfoSelection.ts
> +    if (!multiple) triggerInfo = [];
好了

2022-06-23 11:05 UTC, pearmini requested changes

2022-06-23 11:05 UTC, pearmini commented on src/interaction/builtin/legendActive.ts
> +        { type: 'highlightSelection' },
这是 highlightSelection，其他的是 highlight，又啥区别吗？

2022-06-28 11:38 UTC, merged