fix(theme): 背景 rect 的 bbox 在 slider 重新布局后 没有覆盖全 canvas
antvis/G2 pull request #3998
Opened 2022-06-23 06:51 UTC by ai-qing-hai

| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/65594180/175852810-ed07e52f-3627-4618-be26-d18ec6f29354.png) |  ![image](https://user-images.githubusercontent.com/65594180/175852786-8e0b09d4-bd00-4a43-95c8-74add6106220.png) |
 
fixed #2484

2022-06-24 03:21 UTC, hustcc commented on src/chart/view.ts
> +      // slider, scrollbar 的 layout 会让 viewBBox 被剪切 cut 导致使用 viewBBox 获取宽高时重新剪切后的，覆盖不到 slider、scrollbar
应该修改 layout，让 viewBBox 不被裁减。理论上 viewBBox 就是整个 view 的大小，coordinateBBox 才是除去四周的组件（axis、slider 等）距离之后的大小。

2022-06-27 03:10 UTC, ai-qing-hai commented on src/chart/view.ts
> +      // slider, scrollbar 的 layout 会让 viewBBox 被剪切 cut 导致使用 viewBBox 获取宽高时重新剪切后的，覆盖不到 slider、scrollbar
@hustcc  修改好了

2022-06-28 02:29 UTC, hustcc commented on src/chart/view.ts
> +  public contentBBox?: BBox;
不能这么增加变量，现在有 viewBBox 和 coordinateBBox，两个变量是足够使用的，反而增加一个变量，这三个变量直接互相定位没法区别。

2022-06-28 02:30 UTC, hustcc requested changes

2022-06-28 02:30 UTC, hustcc commented on src/chart/view.ts
> +  public contentBBox?: BBox;
不能这么增加变量，现在有 viewBBox 和 coordinateBBox，两个变量是足够使用的，反而增加一个变量，这三个变量直接互相定位没法区别。

2022-06-28 03:44 UTC, ai-qing-hai commented on src/chart/view.ts
> +  public contentBBox?: BBox;
这边需要这个 新的保存 viewBBox 的 clone bbox 的地方。  view 上是比较好的选择。coordinateBBox ， viewBBox 不能更改， 我只能重新加一个 BBox了

2022-07-04 23:19 UTC, visiky commented
看下是不是和这个 PR 的问题是一样的，coordinate 更新之后，没有更新 controller 组件的位置

2022-07-05 02:10 UTC, ai-qing-hai commented
@visiky 和这个感觉差距有点大。 这个主要不是 coordinateBox 的问题。 而是 viewBBox 的问题。 slider 和 scrollbar 会裁剪掉 viewBBox 的 来记录自己的位置。 导致黑色背景覆盖不到 slider 和 scrollbar。 所以我这边才用的 新 contentBBox 。 单纯的 viewBBox 和 coordinateBBox 不够。 需要一个新的 bbox 属性去记录位置。

2022-09-09 08:14 UTC, hustcc commented
这个 PR 先关闭了。

2022-09-09 08:14 UTC, closed without merging