feat: add fadeOut animation
antvis/G2 pull request #4009
Opened 2022-06-28 03:30 UTC by hustcc

##### Checklist

- [x] fix test cases for animation
- [x] fade in/out
- [ ] scaleY in/out
- [ ] scaleX in/out
- [ ] demo

##### Description of change

2022-06-28 11:29 UTC, pearmini requested changes
感觉几个 scale 的动画可以复用一个 Scale 函数。

```ts
function Scale(channel: 'x' | 'y', direction: 'in' | 'out', options) {}

function ScaleInX(options) {
  return Scale('x', 'in', options);
}
```

2022-06-28 11:29 UTC, pearmini commented on src/animation/fadeIn.ts
> +      shape.parsedStyle as ParsedBaseStyleProps;
这里为啥要 as，如果 shape.parsedStyle 是 any 的话直接声明类型号，还是断言好？

2022-06-28 11:36 UTC, hustcc commented on src/animation/fadeIn.ts
> +      shape.parsedStyle as ParsedBaseStyleProps;
不用写 as，类型定义是全的。

2022-06-28 11:48 UTC, hustcc commented
当前 scale 合并的复用率太低了，不过如果后面全部合并为 scale 的，再考虑合并。。

2022-06-29 02:25 UTC, pearmini approved these changes

2022-06-29 02:34 UTC, merged