feat: support merge and split animation
antvis/G2 pull request #4011
Opened 2022-06-28 11:54 UTC by pearmini

> TODO

2022-06-28 12:36 UTC, hustcc requested changes

2022-06-28 12:36 UTC, hustcc commented
selection 写单测。

2022-06-30 02:48 UTC, visiky commented on src/runtime/types/component.ts
> +  defaults: G2Theme['enter' | 'exit' | 'enter'],
为什么修改了这里？手误？

2022-06-30 02:53 UTC, pearmini commented on src/runtime/types/component.ts
> +  defaults: G2Theme['enter' | 'exit' | 'enter'],
哦哦哦，这个地方应该是写错了，另外一个 PR 修改了，合并这个 PR 的时候又改回来了😭

2022-06-30 02:58 UTC, visiky approved these changes

2022-06-30 04:56 UTC, merged