docs: add a customize donut demo
antvis/G2 pull request #4110
Opened 2022-08-26 04:44 UTC by visiky

### preview

![image](https://user-images.githubusercontent.com/15646325/186823886-0f02c362-ec9a-414c-b290-7d45ccfb8f41.png)

2022-08-26 06:04 UTC, pearmini requested changes

2022-08-26 06:04 UTC, pearmini commented on docs/customize.md
> +  };
- apply -> add 
- style 支持直接传入一个对象，不需要多次调用 style 方法

```js
const addAnnotationText = (node, data, style) => 
  node
    .annotationText()
    .data(data)
    .encode('x', 'x')
    .encode('y', 'y')
    .encode('text', 'text')
    .scale('x', { guide: null })
    .scale('y', { guide: null, domain: [0, 1] })
    .style('textAlign', 'center')
    .style('textBaseline', 'middle')
    .style('fill', '#333')
    .style('lineWidth', 0)
    .style('dx', 0)
    .style('dy', 0)
    .style(style);
```

2022-08-26 06:04 UTC, pearmini commented on docs/customize.md
> +# Customize
还是不叫 Customize？因为其实也没有涉及到啥自定义的地方，可以就叫 showCase 或者啥？就是放一些稍微复杂一点的那里。

2022-08-29 05:30 UTC, pearmini approved these changes

2022-08-29 05:30 UTC, pearmini commented on docs/show-case.md
> +    return shape;
这里其实可以函数体直接返回的，`const addAnnotstionText = () => node.annotationText()...`，之后可以注意一下。

2022-08-29 05:50 UTC, visiky commented on docs/show-case.md
> +    return shape;
ok. 我下个 PR 带上

2022-08-29 05:50 UTC, merged