[WIP feat: support custom renderer and plugins
antvis/G2 pull request #4113
Opened 2022-08-29 13:17 UTC by pepper-nice

* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

2022-08-30 07:13 UTC, xiaoiver commented
打包 UMD 时将 `@antv/g` 和 `@antv/g-canvas` 从 G2 中 external 掉：
https://rollupjs.org/guide/en/#external
https://rollupjs.org/guide/en/#outputglobals

2022-08-31 12:46 UTC, pearmini commented
讨论结果：g2 会打两种 umd，一种是包含 g 的，叫 g2.min.js；一种是不包含 g 的，叫 g2-lite.min.js。开箱即用的情况使用前者，在需要插件的情况下使用后者。

2022-08-31 13:38 UTC, xiaoiver commented
> 讨论结果：g2 会打两种 umd，一种是包含 g 的，叫 g2.min.js；一种是不包含 g 的，叫 g2-lite.min.js。开箱即用的情况使用前者，在需要插件的情况下使用后者。

我会用俩 rollup 配置生成 UMD，一个就是之前的 `g.min.js`，另一个 external 掉 `@antv/g` 和 `@antv/g-canvas`。
但有一个小小的问题是：

2022-09-08 08:12 UTC, hustcc commented on .genjirc
> +    "docs/assets/g-plugin-rough-svg-renderer.umd.min.js",
这些不能以 devDependences 的方式存在，必须要使用 umd 吗？

2022-09-08 08:14 UTC, hustcc commented on rollup.config.js
> +    external: ['@antv/g', '@antv/g-canvas'],
> svg 也可以加上，G2 5.0 默认内置 svg renderer。

可以下一个 PR 单独增加内置 svg renderer。

2022-09-08 08:16 UTC, hustcc commented
@pepper-nice 

- 有一个空文件：`runtime/canvas.ts`，是否删除？
- umd 文件放 git 中不是很友好！

2022-09-08 11:39 UTC, pearmini requested changes
去掉一些不需要的修改就好

2022-09-08 11:39 UTC, pearmini commented on .genjirc
> +      "Renderer": "renderer",
这个可以暂时先去掉

2022-09-08 11:39 UTC, pearmini commented on src/renderer/canvas.ts
> +  });
这个地方的修改也是不需要的

2022-09-08 11:41 UTC, pearmini commented
还需要处理一下冲突

2022-09-08 12:29 UTC, pearmini commented
案例后续再加，等 genji-notebook 升级

2022-09-08 12:29 UTC, merged