feat: update some data transform
antvis/G2 pull request #4140
Opened 2022-09-14 09:51 UTC by pepper-nice

#### Related Issue
#4136 

#### API Design

##### fetch
```js
{ 
  type: 'fetch',
  value: 'http://xxx.json',
  format: 'csv' | 'json',
  // detect data types such as dates and booleans and convert values to the corresponding JS type.
  autoType?: true | false,
}
```

##### filterBy
```js
// Filter field with different callback. 
{ type: 'filterBy', fields: [ ['time', callback], ['count', callback] }
```
##### sortBy
```js
// true => asc; false => desc
{ type: 'sortBy', fields: [ ['time', true], ['count', false] ] }
```
##### map
```js
// Handle array data with callback.
{ type: 'map', callback: data => data }
```
##### custom
```js
// Handle any type data with callback.
{ type: 'custom', callback: data => data }
```

#### Implement
- [x] code
- [x] test
- [ ] docs

2022-09-14 11:58 UTC, pearmini requested changes

2022-09-14 11:58 UTC, pearmini commented on src/data/sortBy.ts
> +        //     : -(a[field] !== b[field]),
用下面的就好，稍微啰嗦一点没有关系

2022-09-14 11:58 UTC, pearmini commented on src/data/sortBy.ts
>    return (data) => {
这里和 filterBy 一起都支持字符串的形式？这样可以更简单的使用。

```js
{ fields: ['a', 'b', ['c', d => d > 100]] };
```

相对于先对 fields 进行一下归一化，都转换为 `[field, reverse]` 的形式？

2022-09-14 11:58 UTC, pearmini commented on __tests__/unit/data/fetch.spec.ts
> -    });
这里可以增加一个单测测试一下 autoType，证明该配置有用就行，不用深入测试

2022-09-14 11:58 UTC, pearmini commented on __tests__/unit/data/sortBy.spec.ts
>    });
这里额外测试一下多个 fields，同时存在升序和降序的情况

2022-09-14 11:58 UTC, pearmini commented on docs/data.md
> -      callback: (d) => Object.assign(d, { weight: +d.weight }),
这种涉及类型转换的用 autoType 试一下？

2022-09-14 11:58 UTC, pearmini commented on docs/data.md
> +        },
这个也用 autoType 试一下？

2022-09-14 12:37 UTC, pepper-nice commented on src/data/sortBy.ts
>    return (data) => {
那比如下面这种情况下，应该怎么处理呢。a、b 应该使用什么样的规则？
```js
{ fields: ['a', 'b', ['c', d => d < 10], ['d', d => d > 100]] };
```

2022-09-14 12:38 UTC, pepper-nice commented on __tests__/unit/data/sortBy.spec.ts
>    });
<img width="417" alt="image" src="https://user-images.githubusercontent.com/109653633/190155887-d39b0478-596f-4622-a055-d3ca6f8fbbde.png">
有的，在 44 行写了

2022-09-15 03:46 UTC, pepper-nice commented on src/data/sortBy.ts
>    return (data) => {
已修改。新规则：
```js
// 1.
['a', 'b', ['c', cb]] =>  [['a', cb], ['b', cb], ['c', cb]]
// 2.
['a', ['b', cb1], 'c', ['d', cb2]] => [['a', cb1], ['b', cb1], ['c', cb2], ['d', cb2]]
```
这样合理吗？

归一化的方法写在 `src/data/utils/fields.ts` 中，重点 CR 下。

2022-09-15 04:22 UTC, pearmini requested changes

2022-09-15 04:22 UTC, pearmini commented on docs/data-fetch.md
> +### Get Start
`###` -> `##`， 标题为 `#`，正文从 `##` 开始，依次递减。

2022-09-15 04:22 UTC, pearmini commented on docs/data-fetch.md
> +请求 json 或 csv 格式数据
句号

2022-09-15 04:22 UTC, pearmini commented on docs/data-fetch.md
> +# Data Fetch
不用加 Data，直接 Fetch

2022-09-15 04:22 UTC, pearmini commented on docs/data-fetch.md
> +### API
`###` -> `##`

2022-09-15 04:22 UTC, pearmini commented on docs/data-fetch.md
> +### FAQ
如果没有的话这里可以 FAQ 可以去掉

2022-09-15 04:22 UTC, pearmini commented on docs/data-fetch.md
> +`autoType` 能自动将数据中 string 类型的数字转化成 number 类型: '123' => 123.
所有的标题和正文之间空一行

2022-09-15 04:22 UTC, pearmini commented on src/data/filterBy.ts
> +  const processorF = normalizeFields(F);
normalizedF 或者 processedF 会好一点？把状态也放在变量的名字里面

2022-09-15 04:22 UTC, pearmini commented on src/data/utils/fields.ts
> + * @returns Converts a random format array into a regular two-dimensional array
这个可以用 `@description`，不用 `@returns`

2022-09-15 04:22 UTC, pearmini commented on src/data/utils/fields.ts
> +}
感觉这样写有点不是很容易懂？下面这样怎么样？

```js
function normalizeFields(fields, defaultValue = false) {
  return fields.map((d) => {
    if (Array.isArray(d)) {
      const [field, value = defaultValue] = d;
      return [field, value];
    }
    return [d, defaultValue];
  });
}
```

2022-09-15 04:25 UTC, pearmini commented on src/data/sortBy.ts
>    return (data) => {
这个规则感觉过于复杂了？如果不是数组就使用默认的顺序或者 callback 就好了

2022-09-15 05:06 UTC, pearmini requested changes

2022-09-15 05:06 UTC, pearmini commented on docs/data-fetch.md
> +### Get Start
中文：快速开始

2022-09-19 03:21 UTC, hustcc commented on src/data/custom.ts
> +  return (data) => (callback ? callback(data) : data);
这里有判断，是不是 `callback = identity` 这个可以去掉了？

2022-09-19 03:22 UTC, hustcc commented on src/data/fetch.ts
> +      return dsvFormat(delimiter).parse(str, autoType ? d3AutoType : identity);
和上述类似的。

2022-09-19 04:41 UTC, pearmini requested changes
这个 PR 里把 coordinate 的文档去掉，coordinate 的文档可以作为下一个 PR。

2022-09-19 05:12 UTC, pepper-nice commented on src/data/fetch.ts
> +      return dsvFormat(delimiter).parse(str, autoType ? d3AutoType : identity);
这里需要判断 autoType 是否为 true 才进行计算，和上面的情况不太一样。上面已修改。

2022-09-19 06:05 UTC, pearmini approved these changes

2022-09-19 06:22 UTC, merged