feat(point): plots related to point mark
antvis/G2 pull request #4181
Opened 2022-09-28 09:34 UTC by pearmini

# Point

绘制散点图等图。

## 变更点

- Scale：
   - 增加 Sequential
   - 增加 rangeMin，rangeMax，domainMax，domainMin
- Runtime：支持 padding 配置
- Mark
  - Point - 支持生成一个控制点，size 的默认比例尺是 Sqrt 比例尺
  - LIneX、lineY - data 支持一个数组，不用 encode
  - Link - 支持只传一个 x 和 y
- 主题：更新 point 相关的默认值，r 从 2 变成 3

## 案例

### 普通散点图

![image](https://user-images.githubusercontent.com/49330279/192742403-25432f15-1ef7-4a3b-aae9-a2295977464a.png)

```js
(() => {
  const chart = new G2.Chart();

  chart
    .point()
    .data({
      type: 'fetch',
      value:
        'https://gw.alipayobjects.com/os/basement_prod/6b4aa721-b039-49b9-99d8-540b3f87d339.json',
    })
    .encode('x', 'height')
    .encode('y', 'weight')
    .encode('color', 'gender')
    .encode('shape', 'hollow');

  return chart.render().node();
})();
```

### 一维散点图

![image](https://user-images.githubusercontent.com/49330279/192742459-ac07b9b3-8962-4f19-a599-40c7456a424f.png)

```js
(() => {
  const chart = new G2.Chart({ height: 120 });

  chart
    .point()
    .data({
      type: 'fetch',
      value:
        'https://gw.alipayobjects.com/os/basement_prod/6b4aa721-b039-49b9-99d8-540b3f87d339.json',
    })
    .encode('x', 'height')
    .encode('shape', 'hollow');

  return chart.render().node();
})();
```

### 数据标签

![image](https://user-images.githubusercontent.com/49330279/192742604-7b6c66d5-af4e-4e43-b913-3e4220378aa0.png)

```js
(() => {
  const chart = new G2.Chart();

  chart
    .point()
    .data({
      type: 'fetch',
      value:
        ' https://gw.alipayobjects.com/os/bmw-prod/474e51c8-b47b-4bb6-b3ed-87813a960df2.csv',
    })
    .scale('x', { nice: true, domainMax: 38 })
    .scale('y', { nice: true })
    .encode('x', 'mpg')
    .encode('y', 'hp')
    .encode('shape', 'hollow')
    .encode('color', 'steelblue')
    .label({
      text: 'name',
      stroke: '#fff',
      textAnchor: 'start',
      textBaseline: 'middle',
      dx: 10,
      position: 'left',
      fontSize: 10,
      lineWidth: 2,
    });

  return chart.render().node();
})();
```

### 气泡图

Point 的 Size 通道的比例尺默认是 Sqrt 比例尺，是圆的半径。

![image](https://user-images.githubusercontent.com/49330279/192742676-011daf30-337c-4bd7-bda2-4fcc9535e8cd.png)

```js
(() => {
  const chart = new G2.Chart({
    paddingLeft: 150,
    paddingTop: 50,
  });

  chart
    .point()
    .data({
      type: 'fetch',
      value:
        'https://gw.alipayobjects.com/os/bmw-prod/2b48887c-56fb-437e-a91c-6f48e80e5a91.csv',
      transform: [
        {
          type: 'filterBy',
          fields: [['Entity', (d) => d !== 'All natural disasters']],
        },
      ],
    })
    .encode('x', 'Year')
    .encode('y', 'Entity')
    .encode('size', 'Deaths')
    .encode('color', 'Entity')
    .scale('size', { rangeMax: 35 })
    .scale('color', { guide: null })
    .style('stroke', 'black')
    .style('opacity', 0.8)
    .style('lineWidth', 1);

  return chart.render().node();
})();
```

### 对数气泡图

当数据分布不均匀的时候可以使用 Log 比例尺。

![image](https://user-images.githubusercontent.com/49330279/192742735-79aadaf6-d008-4bcb-9d52-393dddadf84d.png)

```js
(() => {
  const chart = new G2.Chart();

  chart
    .point()
    .data({
      type: 'fetch',
      value: 'https://gw.alipayobjects.com/os/antvdemo/assets/data/bubble.json',
    })
    .encode('x', 'GDP')
    .encode('y', 'LifeExpectancy')
    .encode('size', 'Population')
    .encode('color', 'continent')
    .scale('size', { type: 'log', range: [4, 20] })
    .style('fillOpacity', 0.3)
    .style('lineWidth', 1);

  return chart.render().node();
})();
```

### 不同形状

![image](https://user-images.githubusercontent.com/49330279/192742805-36ac0ff7-3079-41bc-844f-fa6a42a02a7e.png)

```js
(() => {
  const chart = new G2.Chart();

  chart
    .point()
    .data({
      type: 'fetch',
      value:
        'https://gw.alipayobjects.com/os/bmw-prod/bd73a175-4417-4749-8b88-bc04d955e899.csv',
    })
    .encode('x', 'x')
    .encode('y', 'y')
    .encode('shape', 'category')
    .encode('color', 'category')
    .style('r', 5);

  return chart.render().node();
})();
```

### 堆叠点图

![image](https://user-images.githubusercontent.com/49330279/192742864-c914d521-8e9e-4417-b93d-40bb6e1597c8.png)

```js
(() => {
  const chart = new G2.Chart({ height: 360 });

  chart
    .point()
    .data({
      type: 'fetch',
      value:
        'https://gw.alipayobjects.com/os/bmw-prod/88c601cd-c1ff-4c9b-90d5-740d0b710b7e.json',
    })
    .transform({ type: 'stackY' })
    .encode('x', (d) => 2021 - d.birth)
    .encode('y', (d) => (d.gender === 'M' ? 1 : -1))
    .encode('color', 'gender')
    .scale('color', { field: 'Gender' })
    .scale('x', { field: 'Age →', nice: true })
    .scale('y', {
      field: '← Women · Men →',
      formatter: (d) => `${Math.abs(+d)}`,
    });

  chart.lineY().data([0]).style('stroke', 'black');

  return chart.render().node();
})();
```

### 扰动点图

![image](https://user-images.githubusercontent.com/49330279/192742917-5e3cde55-2bda-494e-a0bb-051e420cf150.png)

```js
(() => {
  const chart = new G2.Chart();

  chart
    .point()
    .data({
      type: 'fetch',
      value:
        'https://gw.alipayobjects.com/os/bmw-prod/2c813e2d-2276-40b9-a9af-cf0a0fb7e942.csv',
    })
    .transform({ type: 'sortX', channel: 'x', reducer: (I, V) => +V[0] })
    .transform({ type: 'jitterX' })
    .encode('y', 'Horsepower')
    .encode('x', 'Cylinders')
    .encode('shape', 'hollow')
    .encode('color', 'Cylinders')
    .scale('x', { type: 'point' })
    .scale('color', { type: 'ordinal' });

  return chart.render().node();
})();
```

![image](https://user-images.githubusercontent.com/49330279/192742972-17d28c45-3182-4a3b-af01-7fa920750dc1.png)

```js
(() => {
  const chart = new G2.Chart();

  chart.coordinate({ type: 'polar' });

  chart
    .point()
    .data({
      type: 'fetch',
      value:
        'https://gw.alipayobjects.com/os/antvdemo/assets/data/diamond.json',
    })
    .transform({ type: 'jitter' })
    .scale('color', { guide: null })
    .encode('x', 'clarity')
    .encode('color', 'clarity');

  return chart.render().node();
})();
```

### 线标注

![image](https://user-images.githubusercontent.com/49330279/192743020-84dde30c-225e-4b82-81e2-c0b4681af012.png)

```js
(() => {
  const chart = new G2.Chart();

  chart
    .point()
    .data([
      { x: 95, y: 95, z: 13.8, name: 'BE', country: 'Belgium' },
      { x: 86.5, y: 102.9, z: 14.7, name: 'DE', country: 'Germany' },
      { x: 80.8, y: 91.5, z: 15.8, name: 'FI', country: 'Finland' },
      { x: 80.4, y: 102.5, z: 12, name: 'NL', country: 'Netherlands' },
      { x: 80.3, y: 86.1, z: 11.8, name: 'SE', country: 'Sweden' },
      { x: 78.4, y: 70.1, z: 16.6, name: 'ES', country: 'Spain' },
      { x: 74.2, y: 68.5, z: 14.5, name: 'FR', country: 'France' },
      { x: 73.5, y: 83.1, z: 10, name: 'NO', country: 'Norway' },
      { x: 71, y: 93.2, z: 24.7, name: 'UK', country: 'United Kingdom' },
      { x: 69.2, y: 57.6, z: 10.4, name: 'IT', country: 'Italy' },
      { x: 68.6, y: 20, z: 16, name: 'RU', country: 'Russia' },
      { x: 65.5, y: 126.4, z: 35.3, name: 'US', country: 'United States' },
      { x: 65.4, y: 50.8, z: 28.5, name: 'HU', country: 'Hungary' },
      { x: 63.4, y: 51.8, z: 15.4, name: 'PT', country: 'Portugal' },
      { x: 64, y: 82.9, z: 31.3, name: 'NZ', country: 'New Zealand' },
    ])
    .encode('x', 'x')
    .encode('y', 'y')
    .encode('color', '#1890ff')
    .encode('size', 'z')
    .scale('x', { nice: true })
    .scale('y', { nice: true, domainMax: 165, zero: true })
    .scale('size', { range: [10, 40] })
    .style('stroke', '#1890ff')
    .style('fillOpacity', 0.3)
    .label({
      text: 'name',
      position: 'inside',
      fill: '#1890ff',
      stroke: '#fff',
    });

  chart.lineY().data([50]).style('stroke', '#54545').label({
    text: 'Safe sugar intake 50g/day',
    position: 'right',
    textBaseline: 'bottom',
  });

  chart.lineX().data([65]).style('stroke', '#54545').label({
    text: 'Safe fat intake 65g/day',
    position: 'left-top [...]

2022-09-28 09:48 UTC, hustcc commented on __tests__/unit/shape/point/point.spec.ts
> +      lineWidth: '',
这里区别是什么？

2022-09-28 09:49 UTC, hustcc commented on src/mark/image.ts
> +    const offset = createBandOffset(scale, value, options);
这个要统一这么改了吗？

2022-09-28 09:50 UTC, hustcc commented on src/shape/point/symbol.ts
> +  const hr = r * 0.618;
不是正菱形？

2022-09-28 09:52 UTC, hustcc requested changes

2022-09-28 09:52 UTC, hustcc commented on src/transform/maybeSize.ts
> +    console.log(size);
删除。

2022-09-28 09:53 UTC, pearmini commented on src/transform/maybeSize.ts
> +    console.log(size);
这里要不 console.log 变成 error，这样 eslint 检查的时候可以检查出来

2022-09-28 09:54 UTC, pearmini commented on src/mark/image.ts
> +    const offset = createBandOffset(scale, value, options);
嗯嗯，和点相关的都可以这么改，image，point，link 这些，area 和 line这些就没有必要

2022-09-28 09:55 UTC, pearmini commented on __tests__/unit/shape/point/point.spec.ts
> +      lineWidth: '',
这里的区别其实不大，因为这里这里没有把 shape 和 defaultShape 传入

2022-09-28 09:56 UTC, pearmini commented on src/shape/point/symbol.ts
> +  const hr = r * 0.618;
我感觉钻石不是正菱形，这样好看一点。

![image](https://user-images.githubusercontent.com/49330279/192749771-c722adb0-6896-44f3-b8d1-e3b72e1f6611.png)

2022-09-29 07:22 UTC, hustcc approved these changes

2022-09-29 07:23 UTC, merged