fix(node): node.attr method support to assign undefined
antvis/G2 pull request #4189
Opened 2022-10-08 08:27 UTC by Aarebecca

Before
---
```javascript
node.attr(key, undefined)  // get attr value of key
```

After
---
```javascript
node.attr(key, undefined)  // assign `undefined` to the attr value of key
```

2022-10-08 12:39 UTC, pearmini requested changes

2022-10-08 12:39 UTC, pearmini commented on src/api/props.ts
>      }
- `node.objectKey(param)` 不管 param 类型是啥都直接赋值，不需要当 param 是 string 的时候，把其作为 key，并且返回对应 value。
- 这里可以把 clone 操作去掉，现在可以先不用让数据 immutable。

```js
if (args.length === 0) return this.attr(k);
if (args.length === 1) return this.attr(k, args[0]);
const [key, value] = args;
const obj = this.attr(k) || {};
obj[key] = value;
return this.attr(key, obj);
```

2022-10-08 12:39 UTC, pearmini commented on src/api/props.ts
>      }
- 这里的 undefined  判断可以去掉，之前是模拟 `args.length === 1` 的情况
- 暂时先不用 clone array。

```js
if (Array.isArray(value) return this.attr(key, value);
```

2022-10-08 12:39 UTC, pearmini commented on src/api/props.ts
> -    const newArray = [...(Array.isArray(array) ? array : [])];
这里 Array.isArray 主要是为了判断 array 是不是数组，而不是判断它是否为空。不过目前这样写也行，就默认设置的都是 array。

2022-10-08 12:49 UTC, pearmini reviewed
不使用 clone 的原因是目前 clone 也会把 data clone 一份，有点消耗性能，之后可以优化一下

2022-10-08 12:56 UTC, Aarebecca commented on src/api/props.ts
>      }
这里不做判断的话可能有个问题， `undefined` 会被作为新 value 添加到数组后 
```javascript
node.a([1,2,3])  // node.a() => [1,2,3]
node.a(undefined)  // node.a() => [1,2,3, undefined]
```

2022-10-08 13:09 UTC, pearmini commented on src/api/props.ts
>      }
嗯嗯，这也算合理的行为，毕竟也可以直接设置值为 undefined

2022-10-08 16:29 UTC, Aarebecca commented on src/api/props.ts
> -    const newArray = [...(Array.isArray(array) ? array : [])];
这个暂时没改，感觉问题不大

2022-10-09 01:55 UTC, hustcc commented on src/api/node.ts
> +    if (arguments.length === 1) return this.value[key];
666，学会了。

2022-10-09 01:59 UTC, hustcc requested changes

2022-10-09 01:59 UTC, hustcc commented on src/api/props.ts
> +  Node.prototype[name] = function (...args) {
建议和 node.attr 方法风格保持一致。如果是确定的 key value 参数，就显式的写出来，然后根据方法内置 `arguments` 去判断长度。

2022-10-09 01:59 UTC, hustcc commented on src/api/props.ts
> +  Node.prototype[name] = function (...args) {
上面的那个方法类似。

2022-10-09 02:10 UTC, Aarebecca commented on src/api/props.ts
> +  Node.prototype[name] = function (...args) {
嗯嗯，我感觉用函数重载应该会好一些

2022-10-09 02:13 UTC, pearmini commented on src/api/props.ts
> +  Node.prototype[name] = function (...args) {
好像我看直接 arguments eslint 也没有问题？

2022-10-09 06:53 UTC, hustcc commented
![image](https://user-images.githubusercontent.com/7856674/194742376-ed79cd39-dfd9-4fb2-93ea-4a16ca9a55f0.png)

记得用 rebase，这样会稍微好看一些。

2022-10-10 05:45 UTC, merged