feat: add connectNull and style for area mark
antvis/G2 pull request #4193
Opened 2022-10-09 10:35 UTC by hustcc

-[x] area connect style
 -[x] connectNull -> connectNulls

相关绘制 issue： https://github.com/antvis/G/issues/1172

2022-10-09 12:18 UTC, pearmini requested changes

2022-10-09 12:18 UTC, pearmini commented on src/shape/area/curve.ts
> +        .node();
这里可能还是需要两条 path，一条绘制定义的部分，一条绘制没有定义的部分，这样才方便把渐变色添加到定义的部分。

2022-10-09 12:20 UTC, pearmini approved these changes

2022-10-09 12:20 UTC, pearmini commented on src/shape/area/curve.ts
> +        .style('ds', [areaRadialPath(P)].concat(MS.map(areaRadialPath)))
选择这两种 `array.concat` 和 `[...A, ...B]` 拼接数组的方式有啥讲究吗？

2022-10-09 12:29 UTC, hustcc commented on src/shape/area/curve.ts
> +        .style('ds', [areaRadialPath(P)].concat(MS.map(areaRadialPath)))
没啥讲究，`...` 会转成 concat。我是看哪个看起来直观，就用哪个，比如上面连个 object 合并一定是 `...` 直观。

2022-10-10 05:05 UTC, hustcc commented on src/shape/area/curve.ts
> +        .node();
done，对于含 z 的 path，不能使用 `,` 连接。

2022-10-10 05:08 UTC, pearmini commented on src/shape/area/curve.ts
> +        .style('ds', [areaRadialPath(P)].concat(MS.map(areaRadialPath)))
ok

2022-10-10 05:10 UTC, pearmini approved these changes

2022-10-10 05:45 UTC, merged