feat(animation): add zoomIn & zoomOut animation
antvis/G2 pull request #4206
Opened 2022-10-13 10:11 UTC by visiky

close: #4205

2022-10-13 10:56 UTC, pearmini requested changes

2022-10-13 10:56 UTC, pearmini commented on src/animation/zoomOut.ts
> +        transform: 'scale(0)',
这里可以写 `scale(0)` 吗，我记得好像是不行？ @xiaoiver

2022-10-13 10:56 UTC, pearmini commented on src/animation/zoomIn.ts
> +      },
感觉这里还是像 scaleInX 那样通过 opacity 处理一下比较好？

2022-10-14 02:08 UTC, visiky commented on src/animation/zoomOut.ts
> +        transform: 'scale(0)',
我测试了下，没有问题~

2022-10-14 02:29 UTC, pearmini commented on src/animation/zoomIn.ts
> +    ];
这里不要直接写 0.1，scaleInX 和 scaleInY 也有类似的需求，可以抽象一个常量比如说叫：ZERO。同时透明度不是直接从 `0` 变成 `1`，可以参考 scaleInX 实现。更好的做法是把这种实现抽线成一个函数

2022-10-14 02:32 UTC, pearmini commented on docs/animation.md
> +- exit: 出场动画
可以把这篇文档拆分成按照 animation 种类分类的文档，参考[模版](https://www.yuque.com/antv/g2-docs/bx7htb)。这种大的文章可以后面加。然后案例可以复杂一点，不用这里过于简单的数据。

2022-10-14 02:39 UTC, visiky commented on docs/animation.md
> +- exit: 出场动画
文档我后面处理

2022-10-14 02:48 UTC, visiky commented on src/animation/zoomIn.ts
> +    ];
你来抽象 [狗头嘻嘻.jpg]

2022-10-17 02:09 UTC, pearmini requested changes

2022-10-17 02:09 UTC, pearmini commented on src/animation/zoomIn.ts
> +      },
这里不是直接从 0 到 1，有一个 offset，参考 scaleInX

2022-10-17 02:12 UTC, pearmini commented on src/animation/zoomIn.ts
> +    ];
嗯嗯，这里可以先不抽象。

2022-10-17 02:26 UTC, merged