feat: chart API
antvis/G2 pull request #4210
Opened 2022-10-18 08:44 UTC by pepper-nice

### Feature: Chart API of Part 1.
#### Node
- [x] getNodesByType(type): Node[]
- [x] getNodeByKey(key): Node
- [x] remove(Node): Node

#### Chart
- [x] changeData(data)
- [x] changeSize(width, height)
- [x] options.autoFit
- [x] forFit()
- [x] destroy()
- [x] clear()

2022-10-19 03:02 UTC, pearmini requested changes
这里有一点解释一下，能力都在 runtime 里面， chart api 只有以下两个功能：

- 构造和操作 runtime 需要的 options：chart.node()，chart.[select] ...
- 提供语法糖：changeData，changeSize

2022-10-19 03:15 UTC, pearmini commented on src/api/node.ts
> +      const children = node.value?.children || node.children || [];
不需要考虑后面的情况，因为后面的写法连 interval node 这个对象都没有

2022-10-24 02:41 UTC, pepper-nice commented
1. 事件 `_event` 在 Node 中声明，可以在 `options` 中取到，在 runtime 中触发。
2. 在 Chart 中新增 `this.width(width)` 和 `this.height(height)` 语法糖用于修改容器宽高。

2022-10-24 03:27 UTC, pearmini requested changes

2022-10-24 03:27 UTC, pearmini commented on src/api/node.ts
> +  }
定义在 chart 里面，存在 value 里面。
```js
chart.on('mouseenter', A);
chart.on('mouseenter', B);
// chart.options()
const options = {
  on: {
    mouseenter: [A , B]
  }
}
```

2022-10-24 03:27 UTC, pearmini commented on src/api/node.ts
> +    }
find + splice

2022-10-24 03:27 UTC, pearmini commented on src/api/node.ts
> +        return (targetNode = node);
这里 return 可以去掉

2022-10-24 03:27 UTC, pearmini commented on src/api/node.ts
> +        return (targetNode = node);
通过 node.value.key 这种形式获得 key

```js
chart.interval().key('a');
```

2022-10-24 03:27 UTC, pearmini commented on src/api/node.ts
> +    let discovered: Node = this;
root

2022-10-24 03:27 UTC, pearmini commented on src/api/chart.ts
> +    _event: node._event,
这里可以去掉了

2022-10-24 03:27 UTC, pearmini commented on src/api/chart.ts
> +        _height,
这里不要用下划线，更语义化的名字：finalWidth

2022-10-24 03:27 UTC, pearmini commented on src/api/chart.ts
> +    this.render();
这个是异步的

2022-10-24 03:27 UTC, pearmini commented on src/runtime/render.ts
> +  const { width = 640, height = 480, autoFit = false, _event } = options;
从 on 里面拿到

```js
const options = {
  on: []
};
```

2022-10-24 03:27 UTC, pearmini commented on src/runtime/render.ts
>      .then(callback);
这里触发事件

2022-10-24 03:27 UTC, pearmini commented on src/runtime/render.ts
> +
只绑定一次

2022-10-24 03:27 UTC, pearmini commented on src/utils/size.ts
> +  const wrapperHeight = container.clientHeight || parseInt(style.height, 10);
```js
const parseInt10 = d => parseInt(d, 10);
```

2022-10-24 03:27 UTC, pearmini commented on src/api/node.ts
> +    emitEvent(events, CHART_LIFE_CIRCLE.BEFORE_CHANGE_DATA);
暂时先去掉。

2022-10-24 07:54 UTC, pearmini requested changes

2022-10-24 07:54 UTC, pearmini commented on src/spec/composition.ts
>  };
可以暂时按照下面的写法：
```ts
Record<'string', ((...args: any[]) => void )[]>
```

2022-10-24 07:54 UTC, pearmini commented on src/api/node.ts
> +      root = root?.parentNode;
这里  `?` 不要了

2022-10-24 07:54 UTC, pearmini commented on __tests__/unit/api/node.spec.ts
> +    node['key'] = 'node1';
单测这里是没有更新吗？`node.attr('key') = 'node1'`

2022-10-24 07:54 UTC, pearmini commented on __tests__/unit/api/node.spec.ts
> +  it('node.remove(node) should delete the node.', () => {
`node.remove()` 没有 node 参数

2022-10-24 08:47 UTC, pepper-nice commented on __tests__/unit/api/node.spec.ts
> +    node['key'] = 'node1';
sorry, 忘记了。

2022-10-24 09:18 UTC, pearmini requested changes

2022-10-24 09:18 UTC, pearmini commented on src/api/node.ts
> +        return item === this;
```js
const index = children.find(d => d === this);
children.splice(index, 1);
```

2022-10-24 09:22 UTC, pepper-nice commented on src/api/node.ts
> +        return item === this;
好的，第一次见这个 api，学到了。

2022-10-24 11:07 UTC, merged