feat(label): support label line
antvis/G2 pull request #4232
Opened 2022-11-01 08:21 UTC by visiky

### 新增 labelLine 和 offset 配置

- 复用 text shape

**使用如下:**
```js
labels: [
  {
    text: 'type',
    position: 'outside',
    offset: 8,
    labelLine: { stroke: '#416180', strokeOpacity: 0.45 },
  },
],
```

2022-11-01 09:09 UTC, pearmini requested changes
提交 PR 前先本地运行测试案例，从而生成基准图片，目前你的 PR 里面基准图表都没有。

2022-11-01 09:09 UTC, pearmini commented on __tests__/integration/charts/label-rose.ts
> +        labelLine: { stroke: '#416180', strokeOpacity: 0.45 },
labelLine 拍平

2022-11-01 09:09 UTC, pearmini commented on __tests__/integration/charts/label-rose.ts
> +    scale: { color: { guide: null } },
不要用 guide 语法：

```js
{
  legend: false
}
```

2022-11-01 09:09 UTC, pearmini commented on __tests__/integration/charts/label-rose.ts
> +    },
这个数据太简单了，用一点复杂的数据

2022-11-01 09:09 UTC, pearmini commented on __tests__/integration/charts/label-pie.ts
> +        'https://gw.alipayobjects.com/os/bmw-prod/79fd9317-d2af-4bc4-90fa-9d07357398fd.csv',
不要用远程数据，参考别的案例

2022-11-01 09:09 UTC, pearmini commented on __tests__/integration/charts/index.ts
> +export { roseLabel } from './label-rose';
文件的命名有问题，格式参考别的案例和 contribution.md

2022-11-01 09:09 UTC, pearmini commented on __tests__/integration/charts/label-pie.ts
> +    children: [pie(), pie(true)],
这里不要用 spaceFlex，保证每个测试的测试的东西较少

2022-11-01 09:09 UTC, pearmini commented on __tests__/integration/charts/label-pie.ts
> +export function pieLabel(): G2Spec {
这里的命名同样有问题，格式参考别的案例和 contribution.md

2022-11-01 13:42 UTC, visiky commented on __tests__/integration/charts/label-rose.ts
> +        labelLine: { stroke: '#416180', strokeOpacity: 0.45 },
labelLine 拍平的话，会和 labelLineWidth 冲突（代表 label 的 lineWidth）

2022-11-02 01:37 UTC, visiky commented on __tests__/integration/charts/label-rose.ts
> +        labelLine: { stroke: '#416180', strokeOpacity: 0.45 },
修改为 connector

2022-11-03 05:47 UTC, visiky commented on src/shape/label/label.ts
> +    ...PositionProcessor[camelCase(p)](p, points, v, coordinate),
theme 的优先级应该低于运行时推断的 style 优先级

2022-11-03 08:45 UTC, hustcc commented
这图看起来有点好看~

2022-11-03 13:16 UTC, hustcc commented on src/shape/text/text.ts
> +    maybeAppend(this, '.connector', 'path')
这个写法是神马

2022-11-03 13:16 UTC, hustcc commented on src/utils/helper.ts
> +    .filter(([key]) => key !== undefined && key !== '');
null 要处理吗？

2022-11-07 02:37 UTC, pearmini requested changes

2022-11-07 02:37 UTC, pearmini commented on src/label-transform/circleSurround.ts
> +export const CircleSurround: LLC<CircleSurroundOptions> = (options) => {
这个改一个名字？一般 transform 都是 **动词 + xxx** 或者 **名词** 的形式，比如 surroundCircular。当然其实我觉得 surround 会更加简洁一点，因为围绕本身其实就有圆的感觉。

2022-11-07 03:26 UTC, merged