feat: treemap mark
antvis/G2 pull request #4242
Opened 2022-11-04 08:42 UTC by pepper-nice

#### 案例验证

<img width="500" alt="image" src="https://user-images.githubusercontent.com/109653633/199928423-845cebb1-1fca-401e-b3f3-6481cdaf5fce.png">

```js
import { G2Spec } from '../../../src';
import { philosophyTreemapData } from '../data/philosophy';

export function flareTreemapDefault(): G2Spec {
  return {
    type: 'treemap',
    data: {
      value: philosophyTreemapData,
    },
  };
}
```

<img width="500" alt="image" src="https://user-images.githubusercontent.com/109653633/199928718-35ead4b2-550b-4b12-b120-d159f253e863.png">

```js
import { csv } from 'd3-fetch';
import { autoType } from 'd3-dsv';
import { schemeTableau10 } from 'd3-scale-chromatic';
import { G2Spec } from '../../../src';

export async function flareTreemapCustom(): Promise<G2Spec> {
  const data = await csv('data/flare.csv', autoType);

  return {
    type: 'view',
    height: 900,
    width: 1100,
    children: [
      {
        type: 'treemap',
        data: {
          value: data,
        },
        layout: {
          tile: 'treemapBinary',
          path: (d) => d.name.replace(/\./g, '/'),
        },
        scale: {
          color: { range: schemeTableau10 },
        },
        encode: {
          value: 'size',
          color: (d) => d.parent.data.name.split('.')[1],
        },
        label: {
          text: (d) => {
            const name = d.data.name
              .split('.')
              .pop()
              .split(/(?=[A-Z][a-z])/g)[0];
            return name.length > 5 ? name.slice(0, 5) + '...' : name;
          },
          fill: '#000',
          position: 'top-left',
          dx: '3px',
          dy: '3px',
        },
        style: {
          fillOpacity: 0.5,
        },
      },
    ],
  };
}

```

2022-11-04 09:05 UTC, pearmini commented
矩阵树图的 label 直接透传就好了，通过 mark.labels 去声明。而不是下面这样：

![image](https://user-images.githubusercontent.com/49330279/199934567-df8c8edd-9eef-4e20-904a-fd1de696097e.png)

桑基图的相关 API 我后面也要做相应调整。

2022-11-04 09:25 UTC, pearmini requested changes
大部分没有问题，有两个和 label 的问题：

- label 的声明方式，CR 里面已经说了。
- label 的隐藏的问题：是否可以给 label 添加 clipPath 的能力，让它的父亲作为它的 clipPath，这样就可以实现 D3 这样的效果：

![image](https://user-images.githubusercontent.com/49330279/199938451-bc6c353f-3df8-4a9b-a164-d11583686ef7.png)

2022-11-04 09:25 UTC, pearmini commented on src/mark/sankey.ts
> +    console.log(linkData);
去掉

2022-11-04 09:25 UTC, pearmini commented on src/mark/treemap.ts
> +      tooltip: { field: '流派' },
去掉

2022-11-04 09:25 UTC, pearmini commented on src/spec/geometry.ts
> +export type TreemapMark = BaseGeometry<'treemap', 'color' | 'value'> & {
这里的通道不只有 color 和 value，应该是所有的 channelTypes

2022-11-04 09:25 UTC, pearmini commented on src/spec/geometry.ts
> +  label?: Record<string, any>;
去掉

2022-11-04 09:25 UTC, pearmini commented on src/mark/treemap.ts
> +    : d3Hierarchy[tile];
如果 'd3Hierarchy[tile]' 是 undefined 改怎么办？

2022-11-04 09:25 UTC, pearmini commented on src/mark/treemap.ts
> +    .filter((d) => d.height === 0);
这里 filter 的目的是？是不是必须的，还是用户也可以指定显示地指明这里的值？

2022-11-04 09:25 UTC, pearmini commented on src/mark/treemap.ts
> +    : d3Hierarchy.hierarchy(data);
这个地方写得挺好的，两种数据格式都照顾到了

2022-11-04 09:25 UTC, pearmini commented on src/mark/treemap.ts
> +    } = options;
这里的 rest options 直接透传给转换之后的 mark，比如 animate 这些。

2022-11-04 09:25 UTC, pearmini commented on __tests__/integration/charts/flare-treemap-custom.ts
> +        },
普通的 mark 的 label 都是数组，但是因为符合 mark 一般都会有 label，所以可以提供多一种声明 label 的方式。参考 Saneky 的实现方式，不是直接提供 label 配置，而是全部放在 style 里面。

```js
const options = {
  style: {
    labelText: '',
    labelFill: ''
    ...
  }
}
```

2022-11-04 09:26 UTC, pearmini commented
rebase 一下 PR

2022-11-04 09:35 UTC, pearmini requested changes

2022-11-04 09:35 UTC, pearmini commented on src/mark/treemap.ts
> +      y: { type: 'identity', domain: [0, 1] },
这里既然是 identity scale 了就不用指定 domain 了，我看 Sankey 图的 y 比例尺我有这个问题，一起去掉一下

2022-11-04 09:47 UTC, pearmini requested changes

2022-11-04 09:47 UTC, pearmini commented on src/mark/treemap.ts
> +    : d3Hierarchy.hierarchy(data);
等一下，我突然觉得这里有点问题，path 配置其实和布局是没有关系，应该是和数据有关的，感觉不应该放在 layout 里面。相当于 data 其实支持两种类型：JSON 和 CSV。如果是 JSON 就用 hierarchy，如果是 CSV 就用 stratify，同时要指定 path。这样你先把 path 配置放在 data 里面。

```js
const options = {
  data: {
    value: '',
    path: ''
  }
}
```

2022-11-04 16:40 UTC, pepper-nice commented
label 的 parent 是 'label-layer'，是最外层的大盒子，无法作为每个 label 的 clipPath。所以 `clipPath` 我是这样添加的。但是不生效，能看看问题在哪吗？我拿到每个格子的 point 绘制一个 path 作为裁剪区域。

<img width="657" alt="image" src="https://user-images.githubusercontent.com/109653633/200028801-00a45a8c-bb6d-4976-9576-cdf99746525f.png">

2022-11-07 02:43 UTC, pearmini requested changes

2022-11-07 02:43 UTC, pearmini commented on __tests__/integration/charts/energy-sankey-defaults.ts
> +  console.log(links);
去掉

2022-11-07 02:43 UTC, pearmini commented on src/shape/label/label.ts
>        .call(applyStyle, overrideStyle)
clipPath 不生效？@xiaoiver

2022-11-07 02:46 UTC, pearmini requested changes

2022-11-07 02:46 UTC, pearmini commented on src/shape/label/label.ts
> +    const { text, x, y, clipPath = true, ...overrideStyle } = value;
我觉得这里叫 clip 会好一点？防止和本来的用户指定的 clipPath 冲突？

2022-11-07 11:30 UTC, pearmini approved these changes

2022-11-07 11:30 UTC, pearmini commented on src/utils/size.ts
> +  } = options;
这里应该还需要减去 inset 的值

2022-11-07 11:30 UTC, pearmini commented on src/mark/treemap.ts
> +      textOverflow: 'clip',
这个能力还挺不错的，之后看能不能作为 label 的通用能力（所有 chart label 都可以用这个能力）

2022-11-07 12:20 UTC, pepper-nice commented on src/mark/treemap.ts
> +      textOverflow: 'clip',
这个方法只能暂时解决问题。我在处理 pack 时发现，point 的外容器是圆，用这种方法没法处理。只能等 G 那边 clipPath 方法没问题后在 label 上加一层容器作为通用能力。

2022-11-08 02:56 UTC, pearmini commented on src/mark/treemap.ts
> +      textOverflow: 'clip',
ok

2022-11-08 03:24 UTC, merged