docs(demo): add lottie #4221
antvis/G2 pull request #4262
Opened 2022-11-10 10:52 UTC by xiaoiver

* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

2022-11-10 11:06 UTC, hustcc commented
有没有好看一点的 lottie 文件~

2022-11-10 11:06 UTC, hustcc requested changes

2022-11-10 11:06 UTC, hustcc commented on site/examples/others/animation/demo/lottie.ts
> +  autoFit: true,
可以固定大小吧，避免拖大之后，lottie 的位置不好看~

2022-11-10 13:32 UTC, hustcc commented
![image](https://user-images.githubusercontent.com/7856674/201105046-e31a79fc-0e6d-453a-9b0d-0d43c90629b2.png)

2022-11-11 04:27 UTC, visiky commented
怎么控制 G2 渲染出来的 group 的动画执行呢？

2022-11-11 06:05 UTC, hustcc commented
> 怎么控制 G2 渲染出来的 group 的动画执行呢？ 现在貌似是直接在 G2 渲染出来的 canvas 上加了一个 gif 的感觉？

现在相当于是用三方的插件做一个点缀，后续可以尝试增加一个 lottie 的 mark。

2022-11-14 06:59 UTC, xiaoiver commented
蚂蚁形象动画解析有问题，导致无法播放：
https://github.com/antvis/G/issues/1212

2022-11-14 07:59 UTC, hustcc commented
那这个先合并掉，后面新增和优化 demo？

2022-11-14 08:32 UTC, xiaoiver commented
> 那这个先合并掉，后面新增和优化 demo？

我先改成 Shape Mark 的写法。

2022-11-14 11:22 UTC, merged