docs(rough): add 2 sketchy-styled examples
antvis/G2 pull request #4265
Opened 2022-11-11 02:56 UTC by xiaoiver

2022-11-11 03:05 UTC, hustcc requested changes

2022-11-11 03:05 UTC, hustcc commented on site/examples/others/theme/demo/rough-point.ts
> +          // tickFontFamily: 'Gaegu',
注释直接移除

2022-11-11 03:05 UTC, hustcc commented
效果好的话，可以再来一个折线图、饼图嘛~

2022-11-11 03:05 UTC, pearmini requested changes

2022-11-11 03:05 UTC, pearmini commented on site/examples/others/theme/demo/rough-point.ts
> +      });
```js
.axis('x', {})
.axis('y', {})
```

2022-11-11 03:24 UTC, visiky commented
组件部分的样式，是不是 G 层可以做继承的处理？

2022-11-14 06:32 UTC, xiaoiver commented
`strokeOpacity` 问题已修复，可以正常展示 grid 了：

<img width="699" alt="截屏2022-11-14 下午2 32 05" src="https://user-images.githubusercontent.com/3608471/201590859-4b3b8efb-c04c-4062-b315-bc126af8cb6a.png">

2022-11-14 07:09 UTC, hustcc approved these changes

2022-11-14 07:10 UTC, merged