feat: add force mark
antvis/G2 pull request #4274
Opened 2022-11-14 01:01 UTC by pepper-nice

<img width="695" alt="image" src="https://user-images.githubusercontent.com/109653633/201554889-b19753f3-0c1c-435e-92a5-2ee34bc54f37.png">

```js
import { schemeTableau10 } from 'd3-scale-chromatic';
import { G2Spec } from '../../../src';

export function miserableForceCustom(): G2Spec {
  return {
    type: 'force',
    data: {
      type: 'fetch',
      value: 'data/miserable-disjoint.json',
    },
    layout: {
      joint: false,
    },
    encode: {
      source: 'source',
      target: 'target',
      value: 'value',
    },
    scale: {
      color: { range: schemeTableau10 },
    },
    style: {},
  };
}

```

2022-11-14 01:24 UTC, hustcc requested changes

2022-11-14 01:24 UTC, hustcc commented on __tests__/integration/charts/energy-sankey-defaults.ts
> +  console.log(links);
删除。

2022-11-14 01:24 UTC, hustcc commented on __tests__/integration/data/miserable-disjoint.json
> +{
文件名称格式保持一致。这个是小写，上面那个是驼峰。

2022-11-14 01:24 UTC, hustcc commented on src/mark/force.ts
> +        color: { range: schemeTableau10 },
默认颜色取  theme 中的色板。

2022-11-14 01:24 UTC, hustcc commented on src/mark/pack.ts
> +    console.log(transformedData);
删除。

2022-11-14 02:05 UTC, pearmini requested changes
这种 PR 可以标记为 `[WIP]:xxx` 这样别人就知道你还没有完成，就暂时不会来看了。

2022-11-14 02:05 UTC, pearmini commented on src/mark/force.ts
> +      linkStrength: 1,
这里的 nodeStrength 和 linkStrength 可能有问题？先使用默认值试试？

2022-11-14 11:52 UTC, pearmini requested changes
代码本身没有太多问题，主要是多覆盖一些测试情况

2022-11-14 11:52 UTC, pearmini commented on __tests__/integration/charts/miserable-force-default.ts
> +      value: 'data/miserable.json',
这个地方还是指定一下比例尺的类型，因为它这里的颜色字段 group 是一个数字，所以用的是数值比例尺，但是这里其实本来是离散的。

```ts
const options = {
  scale: { color: { type:'ordinal' }},
};
```

2022-11-14 11:52 UTC, pearmini commented on src/utils/mapping.ts
> +}
这个 utils 就先放在 mark 的 utils 里面？感觉还没有通用到放在公共的 utils 里面

2022-11-14 11:52 UTC, pearmini commented on __tests__/integration/charts/miserable-force-custom.ts
> +  };
这里测试的地方尽量多测一些 API，比如 style 和 encode，主要是看是否通过 prefix 区分了。可能加了之后图不好看，但是没有关系，在案例的时候把这些额外的声明去掉就好了。

```js
const optons = {
  encode: {
    nodeColor: '',
  },
  style: {
    linkFill: '',
    nodeStroke: ''
  }
}
```

或者你新增一个测试专门测这些参数传递

2022-11-14 11:52 UTC, pearmini commented on __tests__/integration/charts/miserable-force-custom.ts
> +      joint: false,
包括这里测试一下算法的某些参数，看是否传递下去了

2022-11-14 15:23 UTC, pepper-nice commented on __tests__/integration/charts/miserable-force-custom.ts
> +  };
都测了一下，但有些实在让图片太丑了。没有放进去。

2022-11-15 02:12 UTC, pearmini requested changes
我看 API 还没有加，你是这个 PR 加还是下个 PR 再加？

2022-11-15 02:12 UTC, pearmini commented on __tests__/integration/charts/miserable-force-custom.ts
> +      // linkStrength: () => 10,
这注释可以去掉？

2022-11-15 03:28 UTC, pearmini approved these changes

2022-11-15 03:29 UTC, pearmini approved these changes

2022-11-15 05:05 UTC, merged