feat(theme): add light and dark theme token
antvis/G2 pull request #4292
Opened 2022-11-15 14:04 UTC by visiky

- [x] 丰富两套主题的 token
- [ ] 接入组件主题测试
- [ ] 增加一套外置的主题

2022-11-15 15:43 UTC, visiky commented on site/examples/theme/theme/demo/meta.json
> +        "zh": "默认品牌色",
todo 修改为：默认主题色

2022-11-15 15:43 UTC, visiky commented on src/shape/utils.ts
> +    markTheme[shape],
让默认主题色可以 merge 到 shape 主题中

2022-11-15 15:52 UTC, pearmini requested changes
我感觉现在 label 的颜色怎么看上去灰蒙蒙的：

![image](https://user-images.githubusercontent.com/49330279/201964546-d3f281c7-1f6d-4d57-9a01-ad49375ea091.png)

测试案例应该不只挂了这些吧

2022-11-15 15:52 UTC, pearmini commented on site/examples/theme/theme/demo/dark.ts
> +chart.style('plotFill', '#141414').theme({ type: 'dark' });
plotFill 也作为主题的一部分呗？比如 theme.view.xxxx

2022-11-15 15:53 UTC, visiky commented
> 我感觉现在 label 的颜色怎么看上去灰蒙蒙的：
> 
> ![image](https://user-images.githubusercontent.com/49330279/201964546-d3f281c7-1f6d-4d57-9a01-ad49375ea091.png)
> 
> 测试案例应该不只挂了这些吧

我按照 4.x 的 token 搞得，挂的都是主题相关的

2022-11-15 15:59 UTC, pearmini requested changes

2022-11-15 15:59 UTC, pearmini commented on site/examples/theme/theme/demo/default-color.ts
> +  .encode('y', 'sold');
这个案例太简单了，换一个吧

2022-11-16 03:00 UTC, visiky commented on src/theme/light.ts
>          fill: '#1D2129',
文字颜色暂不做调整

2022-11-16 05:32 UTC, pearmini approved these changes

2022-11-16 05:32 UTC, pearmini commented on src/theme/light.ts
>          fill: '#1D2129',
ok

2022-11-16 05:33 UTC, pearmini approved these changes

2022-11-16 05:34 UTC, merged