feat: add wordCloud mark
antvis/G2 pull request #4293
Opened 2022-11-15 15:35 UTC by pepper-nice

<img width="629" alt="image" src="https://user-images.githubusercontent.com/109653633/201960356-11e3e192-52ba-4528-8634-4712186dd1ab.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/109653633/202068104-d0802494-a9af-42d5-a512-1d09b5088890.png">

```js
import { G2Spec } from '../../../src';

export function philosophyWordCloudCustom(): G2Spec {
  return {
    type: 'wordCloud',
    layout: {
      padding: 4,
      spiral: 'rectangular',
    },
    data: {
      type: 'fetch',
      value: 'data/philosophyWord.json',
      transform: [{ type: 'custom', callback: words }],
    },
    encode: {
      color: 'text',
    },
  };
}
```

2022-11-15 15:37 UTC, pepper-nice commented on src/runtime/plot.ts
> +  const [flattenMarks] = await Promise.all(
wordCloud transform 是异步的，所以需要把 Mark 生成这里变成异步。
因为 flatMap 函数内部添加异步不能生效，所以用 `Promise.all` 的方式，这里是否有更好的写法呢？

2022-11-15 15:46 UTC, pearmini requested changes
这个地方应该还有一个图片词云的例子，你看看 runtime 的 text.spec.ts，把这个例子也放到单测里面？该例子中用到的图片也保存到 data 文件里面，然后 src 指定为 src/xxx（参考 image mark）

2022-11-15 15:46 UTC, pearmini commented on src/runtime/plot.ts
> +  const [flattenMarks] = await Promise.all(
确实感觉只能这样写

2022-11-15 15:46 UTC, pearmini commented on src/data/wordCloud.ts
> +  console.log(options);
这个地方去掉

2022-11-15 15:46 UTC, pearmini commented on __tests__/integration/charts/philosophy-wordCloud-custom.ts
> +  };
这个地方我建议把生成后的数据保存为 json，而不是直接用这个原始数据（这个格式的数据本身就不规范），这样能保证这个地方的测试尽量简单。

2022-11-16 05:29 UTC, pearmini approved these changes

2022-11-16 05:30 UTC, merged