docs: add hierarchy&network demo
antvis/G2 pull request #4298
Opened 2022-11-16 10:07 UTC by pepper-nice

<img width="577" alt="image" src="https://user-images.githubusercontent.com/109653633/202151559-6644d62a-f9b9-4c5e-bff6-c57cb68dd398.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/109653633/202151659-22370828-f734-468d-aa0d-39ae0325af0c.png">

2022-11-16 10:22 UTC, hustcc requested changes

2022-11-16 10:22 UTC, hustcc commented on site/examples/general/text/demo/meta.json
> +      "filename": "wordCloud.ts",
wordCloud 还是 wordcloud ?

2022-11-16 10:22 UTC, hustcc commented on site/examples/graph/hierarchy/demo/meta.json
> +        "en": "CirclePack"
Circle Packing

2022-11-16 14:40 UTC, hustcc approved these changes

2022-11-16 14:40 UTC, merged

2022-11-17 06:03 UTC, pearmini commented on site/examples/general/text/demo/wordCloud.ts
> +  .legend(false);
这是不用这么设置的，这些高阶 mark 这里的设置有点问题，Sankey 也有

2022-11-17 06:03 UTC, pearmini commented on site/examples/graph/hierarchy/demo/treemap.ts
> +  .encode('legend', (d) => d.parent.data.name.split('.')[1])
`encode.legend` 是啥意思？