docs(axis): add axis component docs
antvis/G2 pull request #4310
Opened 2022-11-17 14:41 UTC by Aarebecca

Axis Component Composition:
* Title 标题
* Line 轴线
* Tick 刻度
* Label 刻度值
* Grid 网格线

A simple G2 Axis usage:
```ts
chart
  .interval()
  .data(...)
  .axis('x', {
    labelAlign: 'parallel',
    labelDirection: 'positive',
    labelSpacing: 10,
    labelFilter: (datum, index, data) => index % 5 === 0,
    labelTransforms: [{ type: 'hide' }],
    lineLineWidth: 5,
    lineStroke: '#675193',
    showGrid: true,
  });
```

2022-11-17 14:47 UTC, hustcc requested changes

2022-11-17 14:47 UTC, hustcc commented on site/docs/api/component/axis.zh.md
> +```typescript
ts，和前面一致

2022-11-18 00:11 UTC, Rayyy369 commented on site/docs/api/component/axis.zh.md
> +```typescript
Ok

2022-11-18 05:43 UTC, merged

2023-01-06 09:52 UTC, lxliang912 commented
labelTransforms: [{ type: 'hide' }] 的处理逻辑是什么样的？配置这个属性后，在缩小窗口图表自适应后x轴的label隐藏了，放大窗口也不会显示x轴的label，感觉很奇怪

2023-01-08 09:21 UTC, Aarebecca commented
> labelTransforms: [{ type: 'hide' }] 的处理逻辑是什么样的？配置这个属性后，在缩小窗口图表自适应后x轴的label隐藏了，放大窗口也不会显示x轴的label，感觉很奇怪

原理是对相邻刻度值进行碰撞检测，发生碰撞时隐藏标签。可以提供复现的Demo吗，建议提个issue。

2023-01-09 02:07 UTC, lxliang912 commented
> > labelTransforms: [{ type: 'hide' }] 的处理逻辑是什么样的？配置这个属性后，在缩小窗口图表自适应后x轴的label隐藏了，放大窗口也不会显示x轴的label，感觉很奇怪
> 
> 原理是对相邻刻度值进行碰撞检测，发生碰撞时隐藏标签。可以提供复现的Demo吗，建议提个issue。

我用官方的[案例](https://g2.antv.antgroup.com/zh/examples/general/interval/#bar-fixed-cornered)复现了一下  https://github.com/antvis/G2/issues/4555