docs(pattern): using g-pattern
antvis/G2 pull request #4352
Opened 2022-11-23 10:01 UTC by xiaoiver

* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

2022-11-23 11:01 UTC, visiky commented
看下饼干图可以吗？G2 5.0 的有些模糊，没有 G2Plot 的那个清晰

2022-11-23 11:03 UTC, visiky commented
G2Plot 貌似比较清晰~

<img width="679" alt="image" src="https://user-images.githubusercontent.com/15646325/203531027-a69db693-f136-4f92-99bb-f1bde3429e7d.png">

2022-11-24 02:45 UTC, pearmini requested changes

2022-11-24 02:45 UTC, pearmini commented on site/examples/theme/pattern/demo/custom-pattern-with-g-api.ts
> +) => {
这个函数要么放在初始化图表实例前面，要么用 `function`？这样写虽然也没有问题，但如果不是 `.style` 里面的函数延迟执行就会出问题。

2022-11-24 06:21 UTC, xiaoiver commented on site/examples/theme/pattern/demo/custom-pattern-with-g-api.ts
> +) => {
是的，公共 pattern 的创建应该放在外面。

2022-11-28 01:30 UTC, visiky commented on site/examples/theme/pattern/demo/custom-pattern-with-g-api.ts
> +  pattern1 = createPattern(document, '#edaa53', '#44120c', true, true);
pattern的生成直接放到style fill中？不在这里去监听chart beforerender是不是好些

2022-11-28 01:35 UTC, xiaoiver commented on site/examples/theme/pattern/demo/custom-pattern-with-g-api.ts
> +  pattern1 = createPattern(document, '#edaa53', '#44120c', true, true);
我理解这里有两点考虑：
* Pattern 是可以共用的嘛，所以放到外面生成比较好。这样总共就只需要生成三个，放到里面的话，每次执行 `fill` 生成方法都会生成仨
* 放到 `beforerender` 里是想找一个时机能获取到 `document` 对象，这样可以用 `document.createElement` 即 G 的 API 生成 Pattern

2022-11-28 05:18 UTC, visiky commented on site/examples/theme/pattern/demo/custom-pattern-with-g-api.ts
> +  pattern1 = createPattern(document, '#edaa53', '#44120c', true, true);
怎么会呢~~~  每次可以控制生成一个就好，我理解还是运行时动态生成需要的 pattern 就行了。指导用户写法的时候，也推荐动态生成

2022-11-28 06:23 UTC, xiaoiver commented on site/examples/theme/pattern/demo/custom-pattern-with-g-api.ts
> +  pattern1 = createPattern(document, '#edaa53', '#44120c', true, true);
OK 了解了。如果是和 value 相关的那肯定得放在函数里生成。我看之前的例子里是一次性创建了 pattern1/2/3，再根据 value 选择其中一个，所以才想着改进一下共享这仨 pattern。

2022-11-30 02:47 UTC, merged