refactor: update axis and legend
antvis/G2 pull request #4357
Opened 2022-11-24 06:45 UTC by visiky

2022-11-24 09:54 UTC, visiky commented
剩余的小问题：
<img width="812" alt="image" src="https://user-images.githubusercontent.com/15646325/203749509-1c34748b-9331-45fa-a45a-99ae2357f545.png">
<img width="659" alt="image" src="https://user-images.githubusercontent.com/15646325/203749708-90a58145-063a-4c3c-b460-982f15f26745.png">


axis 执行 `axis.update({})` 会导致 grid 的描边透明度失效
<img width="807" alt="image" src="https://user-images.githubusercontent.com/15646325/203752710-c6d6d281-8042-40e4-8aba-17cc2bc2b140.png">

2022-11-29 12:32 UTC, Aarebecca reviewed
疑似有问题的地方
<img width="484" alt="image" src="https://user-images.githubusercontent.com/25787943/204529802-8b6fd726-c0d7-4275-82a3-3421faf739ce.png">

2022-11-30 03:19 UTC, pearmini requested changes

2022-11-30 03:19 UTC, pearmini commented on src/component/legendCategory.ts
> +    }
1. `_` 下划线一般用于私有的变量，这里可以换一个名字，比如 `finalGridRow` 啥的？
2. 这里会有问题吗？比如设置了 gridCol 或者  gridRow 的时候，都会进入 `if`  分支，从而重新设置 gridCol 和 gridRow，覆盖已经设置的值。
3. 把 `Record<position, [number, number]>` 命名为一个变量，然后在使用，可读性会好一点？
4. 5.有可能不用 `let` 吗？在非循环的情况下，保证 `immutable`。

2022-12-01 06:34 UTC, pearmini approved these changes

2022-12-01 06:35 UTC, merged