fix: sort transform should sort the I array
antvis/G2 pull request #4395
Opened 2022-12-01 13:02 UTC by hustcc

`sortX` 的处理仅仅对 scale.domain 进行处理，对于 interval 等图形上是离散的没有问题，因为在 mark shape 绘制的时候，并不需要消费 I。

但是对于 line、area 等 series 类型的 mark，都会导致乱序。因此同时增加对 I 的同等排序。

2022-12-01 13:42 UTC, pearmini requested changes
应该是有三种情况：

1. 对于离散的非系列 mark，比如 interval。(实现如 PR 前）

```js
const data = [
  { genre: 'Sports', sold: 275 },
  { genre: 'Strategy', sold: 115 },
  { genre: 'Action', sold: 120 },
  { genre: 'Shooter', sold: 350 },
  { genre: 'Other', sold: 150 },
];

G2.render({
  type: 'interval',
  data,
  encode: {
    x: 'name',
    y: 'value',
  },
  // 对 domain 进行排序，target 默认为 domain
  transform: [{ type: 'sortX' }],
});
```

2. 对于离散的系列 mark，比如 line。（实现如 PR 后：对 index 和 domain 同时进行排序）。

```js
const data = [
  { genre: 'Sports', sold: 275 },
  { genre: 'Strategy', sold: 115 },
  { genre: 'Action', sold: 120 },
  { genre: 'Shooter', sold: 350 },
  { genre: 'Other', sold: 150 },
];

G2.render({
  type: 'line',
  data,
  encode: {
    x: 'name',
    y: 'value',
  },
  // 对 index 和 domain 一起排序
  transform: [{ type: 'sortX', target: 'both' }],
});
```

3. 对于连续的 mark，比如 line。（大概实现如下）。

```js
function sortX() {
  return (I, mark) => {
    const sortedI = sort(I, (i) => X[i]);
    return [sortedI, mark];
  };
}
```

```js
G2.render({
  type: 'line',
  data,
  encode: {
    x: 'date',
    y: 'value',
  },
  // 对 index 进行排序
  transform: [{ type: 'sortX', target: 'index' }],
});
```

2022-12-01 14:07 UTC, visiky commented
`sortX` transform 的 target 是不是可以内部根据 scale 类型推断，而不是用户指定？

2022-12-01 14:14 UTC, pearmini commented
> `sortX` transform 的 target 是不是可以内部根据 scale 类型推断，而不是用户指定？

目前不行

2022-12-02 01:12 UTC, hustcc commented
想了一下，`target` 枚举值有 both、domain、index 对开发者来说，都太难理解了，相当于需要让开发者知道 G2 大概的渲染逻辑。

如果默认全部都 sort 不会带来问题，我建议是默认都做，带来了性能问题，但也只是加入了 sort transform 之后才有的。

2022-12-02 03:45 UTC, pearmini commented
> 想了一下，`target` 枚举值有 both、domain、index 对开发者来说，都太难理解了，相当于需要让开发者知道 G2 大概的渲染逻辑。
> 
> 如果默认全部都 sort 不会带来问题，我建议是默认都做，带来了性能问题，但也只是加入了 sort transform 之后才有的。

是的，这种使用 API 需要知道实现逻辑应该就是叫做**抽象泄漏**，确实不太好。**但是默认都做，不仅仅是性能问题**。

对于上述第一种和第二种情况，默认都做是没有问题的，只存在性能问题。

对于上述第三种情况，默认都做就会存在问题：**连续数据和离散数据的获得方法是不一样的**。连续数据的 domain 只是一个 `[min, max]`，离散数据的 domain 却是 `[n0, n1, n2, ... nN]`。如果都离散数据的求法，是有问题。

所以不能默认都按相同的方式做，得用一个配置项（或者 type）去区分两种情况（目前没有办法直接推断）。解决办法也很简单，换一种区分方法：从实现逻辑变成通道类型。

```js
// 对于上面的第一种和第二种情况
const data = [
  { genre: 'Sports', sold: 275 },
  { genre: 'Strategy', sold: 115 },
  { genre: 'Action', sold: 120 },
  { genre: 'Shooter', sold: 350 },
  { genre: 'Other', sold: 150 },
];

G2.render({
  type: 'interval',
  data,
  encode: {
    x: 'name',
    y: 'value',
  },
  // 对 domain 进行排序
  // 对 domain 和 index 都排序
  transform: [{ type: 'sortX', strategy: 'ordinal'}],
});
```

```js
function sortX() {
  return (I, mark) => {
    const sortedI = sort(I, (i) => X[i]);
    return [sortedI, mark];
  };
}

G2.render({
  type: 'line',
  data,
  encode: {
    x: 'date',
    y: 'value',
  },
  // 对 index 进行排序
  transform: [{ type: 'sortX', strategy: 'quantitative' }],
});
```

最后说一下性能问题，在离散的情况下，其实有没有对 Index 排序或者没有用 Map 去优化逻辑，算法的时间复杂度都是 `O(n*logn)`，这个复杂度来自于对 domain 的排序。

2022-12-02 04:00 UTC, hustcc commented
ordinal, quantitative 稍微好理解一些。

map 已经加了，是 O(nlogn)。

2022-12-02 12:41 UTC, pearmini requested changes

2022-12-02 12:41 UTC, pearmini commented on src/transform/sort.ts
> +  const sortedI = groupSort(I, normalizeReducer, (i: number) => i);
这个地方用 groupSort 感觉有点重了，可以直接用 sort

```js
function sortQ(options) {
  // ....
  const { channel } = options;
  const [V] = column(encode, channel);
  const sortedI = sort(I, i => V[i]);
  // ...
}
```

2022-12-02 12:42 UTC, pearmini commented on src/transform/sort.ts
> +  const s = typeof slice === 'number' ? [0, slice] : slice;
目前 slice 没有用，但我觉得问题不大，slice 这个地方后面我和 filter 一起处理一下

2022-12-03 04:17 UTC, pearmini requested changes
- 需要再添加一个集成测试去测试第二种情况？（离散折线图）
- 总感觉 `strategy` 这个配置还可以优化一下名字，之前用这个是因为 `sampling` 要用。有以下几个方案:

1. 保持原状
2. 换一个名字，比如 `vaueType`, `dataType`,  `channelType`
3. 通过开关去配置，因为只有两种情况，比如 `ordinal: boolean`

```js
const options = {
  type: 'sortX',
  ordinal: false, // 默认为 true
}
```

4. 通过 type 去区分

```js
const options = {
  type: 'sortQX' // 或者 `sortQuantitativeX`
}

const options = {
  type: 'sortOX', // 或者 `sortOrdinalX`
}
```
5. 忽略这个问题，之后把这个 transform 放在创建 scale 之后，类似 pack，就可以不用用户去指定排序的类型了。

2022-12-03 04:17 UTC, pearmini commented on src/transform/sort.ts
>      const normalizeReducer = createReducer(channel, rest, encode);
normalizeReducer 这个是不是放在 sortOrdinal 前面会更好，毕竟 sortQuantitative 用不到

2022-12-03 11:51 UTC, hustcc commented
我觉得第三种比较好一些！

2022-12-03 12:39 UTC, visiky commented
🐶 之前想说 `strategy` 这个是否可以换成 scaleType。不过看了下你们的回复，我觉得第三种挺好的，因为如果后续做了第 5 步，这个 ordinal 配置就可以不需要了，这种情况相比之下，第三种就比第四种好些

2022-12-04 05:52 UTC, pearmini commented
那就第三种呗，就看是下面那种：

```js
const options = {
  ordinal: false,
}

// 或者
const options = {
  quantitative: true
}
```

我其实感觉下面一种好理解一点，因为上面 `ordinal: false` 其实有点逆向思维的感觉，但是 `quantitative: true` 有点长😭

2022-12-05 08:17 UTC, hustcc commented
对于 x 分类数据，绘制折线图的情况，暂时在外部进行数据排序。

2022-12-05 08:42 UTC, pearmini requested changes

2022-12-05 08:42 UTC, pearmini commented on src/transform/sort.ts
> +        ordinal,
`options.ordinal` sortQuantitative 看上去没有用到？

2022-12-05 08:42 UTC, pearmini commented on src/transform/sort.ts
> +        ordinal,
还有一个小问题：

![image](https://user-images.githubusercontent.com/49330279/205592484-507faa25-509a-4b01-8363-0f0b61d5346f.png)

2022-12-05 09:03 UTC, hustcc commented on src/transform/sort.ts
> +        ordinal,
就用 ordinal，默认 true~

2022-12-05 09:05 UTC, pearmini commented on src/transform/sort.ts
> +        ordinal,
ok

2022-12-05 10:08 UTC, merged