feat(component): support slider without interaction
antvis/G2 pull request #4413
Opened 2022-12-06 09:56 UTC by visiky

- [x] 接入 slider
- [ ] slider 文档
- sliderFilter 下一个 PR

详情见:  https://github.com/antvis/G2/discussions/4396

<img width="629" alt="image" src="https://user-images.githubusercontent.com/15646325/205878699-8c59d9a1-3425-40d9-b4ee-03f60327bff1.png">

2022-12-06 10:06 UTC, Aarebecca commented
文档我晚上来补吧

2022-12-06 10:41 UTC, visiky commented
> 文档我晚上来补吧

discussion中已经把文档写好了，只缺配置项部分而已

2022-12-06 12:02 UTC, pearmini commented on src/runtime/component.ts
> +  const scaleMap = group(scales, (d) => d.name);
- 参考[规范](https://www.yuque.com/antv/g2-docs/code-spec#lBrQi)里面的 Map 的命名方式。

2022-12-06 12:17 UTC, pearmini requested changes
这个 PR 只是在一种情况下把 slider 展示出来了，还有很多问题需要考虑：

- slider 受 transpose 的坐标系影响？
- view 里面 slider 的传递？
- slider 的同步问题？
- 分面里面的 slider 的传递？

不过这些问题暂时可以忽略，先满足需求就可以。

2022-12-06 12:17 UTC, pearmini commented on src/runtime/component.ts
> +  }, [] as G2GuideComponentOptions[]);
这个地方用 flatMap + map 会比 reduce + forEach 的可读性要好一点？

```js
function createSliders() {
  return marks
    .filter((d) => d.slider)
    .flatMap((mark) => {
      const { slider } = mark;
      return Object.entries(slider).map(([scaleType, options]) => ({}));
    });
}
```

2022-12-06 12:17 UTC, pearmini commented on __tests__/integration/charts/aapl-line-slider.ts
> +        formatter: (d) => new Date(d).toLocaleDateString(),
别只叫 formatter， 和 axis 统一下都叫 `labelFormatter`

2022-12-06 12:17 UTC, pearmini commented on src/runtime/component.ts
> +  const scaleMap = group(scales, (d) => d.name);
这里为要 group scale？如果只是为了后面索引的话，如下应该就行了？

```js
const nameScale = new Map(scales.map(scale => [scale.name, scale])
```
```js
nameScale.get(name);
```

2022-12-06 14:13 UTC, visiky commented
> * view 里面 slider 的传递？
> * slider 的同步问题？
> * 分面里面的 slider 的传递？

✅ transpose 下的 slider
待办:
- [] view 里面 slider 的传递？
- [] slider 的同步问题？
- [] 分面里面的 slider 的传递？

2022-12-07 03:26 UTC, pearmini commented
还有一个问题，就是 Chart API 也需要更新一下？

2022-12-07 06:55 UTC, pearmini requested changes
- api 增加了 `mark.slider`，同时增加一下单测
- 处理 一下 accesslint 的问题

2022-12-07 13:36 UTC, hustcc approved these changes

2022-12-08 03:39 UTC, merged