WIP: feat: add 4 label.transform
antvis/G2 pull request #4453
Opened 2022-12-13 01:33 UTC by hustcc

https://github.com/antvis/G2/discussions/4414

- [ ] add 4 label.transform.
- [ ] move `spider`, `surround` to label.position.
- [ ] documents for labels.
- [ ] integration tests
- [ ] demos

2022-12-13 10:23 UTC, hustcc commented on src/utils/color.ts
> +  const i = document.createElement('i');
是的，会导致问题，颜色解析应该 G 也是类似的搞法，后面看看怎么搞。

2022-12-13 12:46 UTC, visiky commented on src/utils/bounds.ts
> +export function isInBounds(point: Vector2, bounds: Bounds): boolean {
对于饼图这种扇形，貌似这种计算不是很精确？

2022-12-13 13:26 UTC, hustcc commented on src/utils/bounds.ts
> +export function isInBounds(point: Vector2, bounds: Bounds): boolean {
这个目前紧紧用在矩形区域上。

2022-12-14 02:42 UTC, pearmini requested changes

2022-12-14 02:42 UTC, pearmini commented on src/utils/color.ts
> +  const i = document.createElement('i');
这里不建议直接用 document，解决办法就是用一些支持颜色转换的库。我看这个函数是把颜色转换为 rgb 的颜色格式，所以有两个建议：

- 名字改成 parseToRGB，这样可读性更强一点
- 使用 [d3-color](https://github.com/d3/d3-color) 去做转换

![image](https://user-images.githubusercontent.com/49330279/207491924-72ffd6e8-4957-4b77-826a-cc847f249be2.png)

2022-12-14 02:42 UTC, pearmini commented on src/utils/bounds.ts
> +}
这些函数倒是挺通用的，交互里面也用到了，之后可以抽一抽

2022-12-14 03:04 UTC, hustcc commented on src/utils/bounds.ts
> +}
你做交互的时候处理下，相关函数在 G2 4.x 也有的。。

2022-12-14 03:22 UTC, pearmini commented on src/utils/color.ts
> +  const i = document.createElement('i');
G 的颜色解析也是通过 document 的完成的？如果是这样是如何保证服务端渲染的？@xiaoiver

2022-12-14 03:25 UTC, hustcc commented on src/utils/color.ts
> +  const i = document.createElement('i');
我先改成 d3-color，大概率是使用 document 的。

2022-12-14 03:26 UTC, pearmini commented on src/utils/color.ts
> +  const i = document.createElement('i');
G 也是使用的 d3-color：https://github.com/antvis/G/blob/next/packages/g-lite/src/css/parser/color.ts#L2

2022-12-14 03:39 UTC, pearmini approved these changes
🚀🚀🚀 沉浸式写代码的效率就是高啊！

2022-12-14 03:42 UTC, pearmini requested changes

2022-12-14 03:42 UTC, pearmini commented on src/label-transform/overlapDodgeY.ts
> +  const { maxIterators = 10, maxError = 0.1, padding = 1 } = options;
maxIterators -> maxIterations

2022-12-14 04:22 UTC, visiky commented on src/utils/bounds.ts
> +export function isInBounds(point: Vector2, bounds: Bounds): boolean {
GUI 也有很多类似的方法，赶脚 G 也会有

2022-12-14 05:14 UTC, hustcc commented on src/utils/bounds.ts
> +export function isInBounds(point: Vector2, bounds: Bounds): boolean {
path-util 里面有更复杂的 polygon 碰撞，之前 overlap 用的这个方法，应该性能上会比矩形的差。

2022-12-14 05:15 UTC, pearmini approved these changes

2022-12-14 05:15 UTC, merged