feat(theme): add academy theme and schemaTableau10 palette
antvis/G2 pull request #4459
Opened 2022-12-13 11:04 UTC by visiky

内置学术风格主题，后续会在 theme-set 中使用

- **feat(palette):** 增加 schemaTableau10 色板
- **feat(theme):** 增加 academy 学术风格主题

2022-12-13 11:18 UTC, hustcc approved these changes

2022-12-13 12:11 UTC, hustcc commented
PR 中来一张 academy 的图~

2022-12-13 14:06 UTC, pearmini requested changes

2022-12-13 14:06 UTC, pearmini commented on src/palette/schemeTableau10.ts
> +
这个不用加，已经有了

2022-12-13 14:10 UTC, pearmini requested changes
defaultCategory10: tableau10

2022-12-14 02:16 UTC, visiky commented on src/palette/schemeTableau10.ts
> +
应该还没有？对应哪个色板？不过我刚好也想问下要不要换名字为  `tableau10` 就好

2022-12-14 02:25 UTC, pearmini commented on src/palette/schemeTableau10.ts
> +
[d3-d3-scale-chromatic](https://github.com/d3/d3-scale-chromatic) 里面的颜色都有

2022-12-14 02:27 UTC, pearmini commented on src/palette/schemeTableau10.ts
> +
scheme 前缀是方案的意思，别的色板都没有加 scheme，这个也不用加吧

2022-12-14 02:31 UTC, visiky commented on src/palette/schemeTableau10.ts
> +
没有要加，我也觉得得去掉的。你为什么脾气那么大，很吓人

2022-12-14 02:32 UTC, closed without merging