feat(theme): add academy theme
antvis/G2 pull request #4469
Opened 2022-12-14 09:16 UTC by visiky

讨论：https://github.com/antvis/G2/discussions/4465

内置学术风格主题，后续会在 theme-set 中使用

- fix(scale): 修复 scale 消费获取色板，G2 注册色板优先级提高
- feat(theme): 增加 academy 学术风格主题
- refactor(theme): 修改 box stroke 颜色, 影响截图更新

2022-12-14 13:13 UTC, hustcc requested changes

2022-12-15 02:22 UTC, visiky commented on site/examples/theme/theme/demo/meta.json
> +        "en": "Academy Theme"
写错了，我改一下
- 不过是 style 好呢，还是 theme
- 我一开始的想法是英文是 theme，中文是风格

2022-12-15 03:33 UTC, pearmini requested changes

2022-12-15 03:35 UTC, pearmini commented on src/runtime/scale.ts
> +    console.warn(`'palette ${palette} load failed !!!'`);
`console.warn` 暂时不考虑，和其他的组件报错方式不统一。

2022-12-15 05:09 UTC, pearmini approved these changes
👍

2022-12-15 05:48 UTC, merged