feat(slider): sync slider scale
antvis/G2 pull request #4528
Opened 2022-12-27 07:16 UTC by visiky

- 将 `slider` options 放到 scale descriptor 中，参与 sync 同步（好处是改动少，scrollbar 也可以按照一样的逻辑）
- 后续再考虑是否将 scale.guide 变成数组形式

<img width="656" alt="image" src="https://user-images.githubusercontent.com/15646325/209627302-b9196309-8504-4da5-a258-3e0db9ea3bb6.png">

2022-12-27 07:31 UTC, hustcc commented on src/runtime/component.ts
> +      const componentType = inferSliderType(channelName, coordinates);
感觉不太合理，原逻辑从 mark 配置中获取 slider 更合理一些。这部分等万木回来 cr 吧。

2022-12-27 07:49 UTC, visiky commented on src/runtime/component.ts
> +      const componentType = inferSliderType(channelName, coordinates);
之前放在 mark 上的 slider 配置，没有经过 scale 同步，会出现下面的情况 (不过也是因为只是通过 channelName 去获取 scale，导致第一个 slider 获取的 scale 是属于第二个的，可能得通过 scaleKey 来区分。但是 scaleKey 并没有在 mark 的描述符上)

<img width="682" alt="image" src="https://user-images.githubusercontent.com/15646325/209631154-9a9d5a12-ad99-4f92-a473-8954947899eb.png">

2023-01-04 02:55 UTC, pearmini requested changes

2023-01-04 02:55 UTC, pearmini commented on __tests__/integration/charts/weather-line-multi-slider.ts
> +            titleFill: '#EE6666',
这里的 titleFill 应该和 color 一样是 `#5470C6`？

2023-01-04 02:55 UTC, pearmini commented on src/runtime/component.ts
> +      const componentType = inferSliderType(channelName, coordinates);
这里 axis、slider 和 scrollbar 确实应该有相同的处理方法，从 scale 里面取组件的信息是合理的，现在有两种思路：

1. scale 有一个 guide key，所有的组件都放在 guide 里面。

```js
const innerOptions = {
  scale: {
    x: {
      axis: {},
      slider: {},
      scrollbar: {},
    },
    color: {
      legend: {},
    },
  },
};
```

3. scale 用组件的名字作为 key，value 是对应组件的配置。

```js
const innerOptions = {
  scale: {
    x: {
      guide: [{ type: 'axis' }, { type: 'slider' }, { type: 'scrollbar' }],
    },
    color: {
      guide: [{ type: 'legend' }],
    },
  },
};
```

当然上面的描述都是内部的，外部的 API 还是和现在保持一致。

- 如果选择第一种思路，这个 PR 可以合并，我下一个 PR 把目前的 guide 都换成 axis 或者 legend
- 如果选择第二种思路，那么这个 PR 可以先关闭。

我倾向于第一种思路。

2023-01-04 08:43 UTC, visiky commented on src/runtime/component.ts
> +      const componentType = inferSliderType(channelName, coordinates);
我倾向于方案 1

2023-01-05 02:13 UTC, pearmini approved these changes

2023-01-05 03:42 UTC, merged