docs: add documents for title component
antvis/G2 pull request #4529
Opened 2022-12-27 09:04 UTC by hustcc

- [x] docs: add documents for title component.
- [ ] refactor title for default style and position.
- [ ] add test cases
- [ ] add examples

2022-12-27 09:17 UTC, visiky commented
1. `title` 组件暂时不透出，说配置项需要调整下
2. title 现在是一个普通的 text，可以考虑增强为 DisplayObject。可以等具体说下配置要调整什么的时候，再做还有文档

2022-12-27 09:20 UTC, hustcc commented
> 1. `title` 组件暂时不透出，说配置项需要调整下
> 2. title 现在是一个普通的 text，可以考虑增强为 DisplayObject。可以等具体说下配置要调整什么的时候，再做还有文档

配置项调整要等谁？我直接搞掉？

2022-12-27 09:22 UTC, visiky commented
> > 1. `title` 组件暂时不透出，说配置项需要调整下
> > 2. title 现在是一个普通的 text，可以考虑增强为 DisplayObject。可以等具体说下配置要调整什么的时候，再做还有文档
> 
> 配置项调整要等谁？我直接搞掉？

万木没有具体说问题是什么，只是让先不要上

2022-12-27 09:23 UTC, hustcc commented
> 万木没有具体说问题是什么，只是让先不要上

那我来做。

2022-12-27 10:55 UTC, visiky requested changes
title style 是否和其他组件一样拍平？还有副标题

2022-12-27 11:09 UTC, hustcc commented
> title style 是否和其他组件一样拍平？还有副标题

嗯。

2022-12-28 03:02 UTC, pearmini commented
我觉得属性是要拍平的，其实 title 和 axis 以及 legend 是一样的，应该保证 api 的统一。之前是先不透出就是 api 的设计和 axis 不太统一，然后当时时间比较紧，所以就暂时先不透出。

2022-12-28 03:04 UTC, hustcc commented
> 我觉得属性是要拍平的，其实 title 和 axis 以及 legend 是一样的，应该保证 api 的统一。之前是先不透出就是 api 的设计和 axis 不太统一，然后当时时间比较紧，所以就暂时先不透出。

当时属性要拍平的原因是啥？我没有感受到好处是什么？感觉不管是写代码，还是写文档，甚至用户使用起来，都不如收起来好。

2022-12-28 03:04 UTC, pearmini requested changes

2022-12-28 03:04 UTC, pearmini commented on src/runtime/types/common.ts
> +  style?: Omit<TextStyleProps, 'x' | 'y' | 'text'>;
这里还是排平比较好？

2022-12-28 03:04 UTC, pearmini commented on src/runtime/types/common.ts
> +  subtitleStyle?: Omit<TextStyleProps, 'x' | 'y' | 'text'>;
这里也是拍平比较好？

2022-12-28 10:05 UTC, pearmini commented
> > 我觉得属性是要拍平的，其实 title 和 axis 以及 legend 是一样的，应该保证 api 的统一。之前是先不透出就是 api 的设计和 axis 不太统一，然后当时时间比较紧，所以就暂时先不透出。
> 
> 当时属性要拍平的原因是啥？我没有感受到好处是什么？感觉不管是写代码，还是写文档，甚至用户使用起来，都不如收起来好。

主要是还是保持 API 风格统一，不管是 Axis，Legend 和 Title 其实都是 Mark：都是图表里面的视觉单元，后面也有相同的渲染流程。那么API 的风格都应该应该是一样。

至于为啥 Mark 需要拍平属性，主要有以下几点：

- 方便数据驱动。
- 保持属性和 G 或者说 CSS 属性风格的统一。在 G2 中 Mark 的属性和 G 中图形的属性唯一的区别就是：G2 中的数据可以数据驱动，可以是字段和回调。G 中图形的属性都是拍平的。
- 更灵活的去组合属性，做到关注点分离。嵌套的配置会强制用户按照 namespace 去组织代码，比如 title 放在一起，subTitle 放在一起。如果我的关注点是根据 fill 和 fontSize 去分离的，那么就是不可行的。

```js
// 按照 fill 和 fontSize 区分关注点
const flat = {
  // 颜色
  titleFill: 'red',
  subTitleFill: 'red',

  // 字号
  titleFontSize: 10,
  subTitleFontSize: 8,
};

// 按照 title 和 subTitle 区分关注点
const flat = {
  // title
  titleFill: 'red',
  titleFontSize: 10,

  // subTitle
  subTitleFill: 'red',
  subTitleFontSize: 8,
};

```

“不管是写代码，还是写文档，甚至用户使用起来，都不如收起来好” 我觉得有待商榷，因为 CSS 属性都是拍平的，不是嵌套的，也没有人抱怨。

当然下面的 API 形式也是可以接受的，同样和 G 保持了统一。

```js
const options = {
  title: '',
  subTitle: '',
  align: 'center',
  style: {
    titleFill: 'red',
    subTitleFill: 'red',
  }
}
```

2022-12-29 02:28 UTC, visiky commented
1、`height` 应该用 `size` 就行
2、`subtitle` 是存在的，代表的是副标题，小标题。不过还要看下大家觉得 `subtitlte` 还是 `subTitle` 好

2022-12-29 02:37 UTC, pearmini requested changes
应该在 API 那里加一个 `chart.title()`和单测？这个 API 应该就是一个 value API：

```js
chart.title('hello world');
```
```js
chart.title({
  text: 'hello world'
});
```

2022-12-29 02:37 UTC, pearmini commented on __tests__/unit/render/renderToMountedElement.spec.ts
>            subtitleStyle: { fill: 'pink' },
这个地方需要改一下？

2022-12-29 02:37 UTC, visiky commented on src/runtime/types/common.ts
> +  height?: number;
`size` 貌似就行了？所有组件都有一个 `size` 配置。
对于 bottom、top 的代表高度，left、right 的代表宽度

2022-12-29 02:50 UTC, hustcc commented on src/runtime/types/common.ts
> +  height?: number;
我从 size 改成 height，前天再看 title 组件的时候，一直以为 size 是 fontSize 的快捷设置。应该 title 也不太可能设置为竖向放左右两边，所以感觉上 height 其实更直观一些。

2022-12-29 03:13 UTC, hustcc commented
> 1、`height` 应该用 `size` 就行 2、`subtitle` 是存在的，代表的是副标题，小标题。不过还要看下大家觉得 `subtitlte` 还是 `subTitle` 好

那还是 subtitle 好~

2022-12-29 04:04 UTC, pearmini commented on src/runtime/types/common.ts
> +  height?: number;
size 应该是所有组件都有的一个共有属性，或者更准确的说是：crossSize，因为 mainSize 总是充满容器。如果方向是水平，那么 mainSize 就是图表的宽度；如果方向是竖直方向，那么 mainSize 就是图表的高度，所以没有必要指定 mainSize。

2022-12-29 04:09 UTC, pearmini commented on __tests__/unit/api/chart.spec.ts
> +  });
我突然发现 `__tests__/api/chart.spec.ts` 里面没有 `__tests__/api/composition.spec.ts`  里面那么通用测试 `chart.[attribute]` 的测试案例，之后我加上

2022-12-29 05:13 UTC, pearmini approved these changes
👍

2022-12-29 07:37 UTC, merged