fix: area support transpose
antvis/G2 pull request #4536
Opened 2022-12-28 10:34 UTC by hustcc

- fixed https://github.com/antvis/G2/issues/4530

2022-12-29 09:36 UTC, visiky approved these changes

2022-12-29 09:36 UTC, visiky commented on src/mark/area.ts
> +const shapes = ['area', 'smooth', 'step'];
有没有看一下, 折线图 hvh, hv, vh 等各种情况的时候，和 area 的 step 可否匹配上？还是说只能 match 其中一种

2022-12-30 01:30 UTC, hustcc commented on src/mark/area.ts
> +const shapes = ['area', 'smooth', 'step'];
只有 hvh 和 step 是匹配的。area 没有设置 hv、vh 两种阶梯方式。

2022-12-30 02:57 UTC, pearmini requested changes
这里没有生成新的截图，是本地没有跑 CI 吗？

2022-12-30 02:57 UTC, pearmini commented on __tests__/integration/charts/aapl-area-missing-data-transpose.ts
> +    data: {
我会觉得用一个简单一点的测试会好一点，就是不用 missing data 这个例子，因为这个测试案例其实测试点有点多了，如果 mssing data 之后要调整，那么这个测试也会调整

2022-12-30 06:19 UTC, visiky commented on src/mark/area.ts
> +const shapes = ['area', 'smooth', 'step'];
那且不是折线图想要增加面积的时候，设置了 shape 为 hv, vh 之后，绘制就对应不上了

2022-12-30 06:20 UTC, visiky requested changes
错选了”通过“

2023-01-04 01:53 UTC, hustcc commented on src/mark/area.ts
> +const shapes = ['area', 'smooth', 'step'];
是的，这个确实是问题，我把 area 的 shape 和 line 的保持一致吧。

2023-01-04 01:54 UTC, hustcc commented on __tests__/integration/charts/aapl-area-missing-data-transpose.ts
> +    data: {
已经增加截图，当时是想顺带也测试下 connectNull 能够正确的 transpose。

2023-01-04 02:10 UTC, pearmini approved these changes

2023-01-04 05:20 UTC, merged