feat: add data.transform.sample
antvis/G2 pull request #4547
Opened 2023-01-04 11:10 UTC by hustcc

- [ ] remove transform.sample
- [ ] add data.transform.sample
- [ ] update documents
- [ ] update demo
- [ ] add `lttb` algo

```ts
export type SampleTransform = {
  type?: 'sample';
  /**
   * Sample by which field.
   */
  field: string;
  /**
   * Sample strategy. Default is 'median'.
   */
  strategy?:
    | 'lttb'
    | 'median'
    | 'max'
    | 'min'
    | 'first'
    | 'last'
    | ((I: number[], V: number[]) => number);
  /**
   * The thresholds of sample, when data size great then thresholds, sample will take effect.
   * Default is 2000.
   */
  thresholds?: number;
  /**
   * Group data by fields, for series data.
   */
  groupBy?: string | string[];
};
```

2023-01-28 07:54 UTC, pearmini requested changes

2023-01-28 07:54 UTC, pearmini commented on src/transform/sample.ts
> +import { maxIndex, minIndex, medianIndex } from 'd3-array';
这个意思就是  `medianIndex` 在 d3-array@3.2.0 增加了，但是 @types/d3-array 没有同步嘛？

2023-01-28 07:54 UTC, pearmini commented on src/transform/sample.ts
> +    ],
这里都是根据 y 通道进行筛选，有 x 通道进行筛选的情况嘛？比如散点图？

2023-01-28 07:54 UTC, pearmini commented on src/transform/utils/lttb.ts
> +      avgY += Y[start] * 1;
这里感觉应该是：

```js
avgX += X[I[start]] * 1;
avgY += Y[I[start]] * 1;
```

同理后面去获得值的时候都好像有这个问题，可以如下解决：

```js
const x = i => X[I[i]];
const y = i => Y[I[i]];
avgX += x(start);
avgY += y(start);
```

2023-01-28 08:01 UTC, hustcc commented on src/transform/sample.ts
> +import { maxIndex, minIndex, medianIndex } from 'd3-array';
是的，types 还是 3.0.4 的。这种 types 三方维护，确实挺难保持同步的。medianIndex 是 23 年加的，很新。

2023-01-28 08:02 UTC, hustcc commented on src/transform/sample.ts
> +    ],
理论是通过一个字段进行筛选，但是没有办法通过两个字段，因为两个字段筛选可能筛选出来的不属于原始数据中的点了。
这里其实是默认通过 y 去筛选了。

2023-01-28 08:03 UTC, hustcc commented on src/transform/utils/lttb.ts
> +      avgY += Y[start] * 1;
确实是的。

2023-01-28 15:28 UTC, pearmini commented on src/transform/sample.ts
> +    ],
有配置支持 x 通道筛选嘛？或者通过 `sampleX` 和 `sampleY` 区分？

2023-01-29 01:33 UTC, hustcc commented on src/transform/sample.ts
> +    ],
暂时不加吧，复杂了。而且区分 x y 的话，不如直接 data.transform 合适，放到 transform 中的一个好处就是对应的通道数据已经确定和明确的。

另外，实际上，具体情况下，只有折线图抽样是相对来说有意义一些。

2023-01-29 02:21 UTC, pearmini commented on src/transform/sample.ts
> +    ],
嗯嗯，那名字有必要改成 sampleY 吗：根据 y 通道的值去筛选数据？

2023-01-29 02:21 UTC, pearmini commented
是否需要增加一个测试案例来测试这个 issue 提到的问题（这也算一个 bug 了）：https://github.com/antvis/G2/issues/4505

2023-01-29 03:00 UTC, hustcc commented
增加案例，fixed #4505

2023-01-29 03:18 UTC, pearmini approved these changes
lttb 👍

2023-01-29 11:28 UTC, merged