fix: interaction should be destroy before rerendering
antvis/G2 pull request #4582
Opened 2023-01-13 09:30 UTC by pearmini

# 交互重新渲染

修复以下 issue 提到的问题：

- https://github.com/antvis/G2/issues/4539
- https://github.com/antvis/G2/issues/4533
- https://github.com/antvis/G2/issues/4550

## 问题原因

重新渲染图表之后，带来的数据更新，导致交互不可用。

## 解决办法

重新渲染图表之后，首先移除之前的交互，然后再重新执行交互。

2023-01-15 12:54 UTC, hustcc requested changes

2023-01-15 12:54 UTC, hustcc commented on src/runtime/plot.ts
> +            const interactions = this['nameInteraction'].values();
尽量少用这中隐含 this 的逻辑吧。现在应该很少代码用这种方式写。

2023-01-15 12:54 UTC, hustcc commented on src/runtime/plot.ts
> +            const interactions = this['nameInteraction'].values();
而且这样应该必须使用 function，不能使用箭头符号。

2023-01-15 12:54 UTC, hustcc commented on src/runtime/plot.ts
> +    return Array.from(viewContainer.entries()).map(([view, container]) => ({
好像没有什么必要抽出来，反而 对于 enterContainer、updateContainer 是遍历两遍，不确定这个 container 是和数据有关系吗？

2023-01-16 02:10 UTC, Aarebecca commented on src/runtime/plot.ts
> +            const interactions = this['nameInteraction'].values();
> 尽量少用这中隐含 this 的逻辑吧。现在应该很少代码用这种方式写。

➕1

2023-01-16 03:05 UTC, pearmini commented on src/runtime/plot.ts
> +            const interactions = this['nameInteraction'].values();
嗯嗯，这个是目前 selection 的写法，但是是为了保持和 d3-selection 一致。之后确实可以修改一下。

2023-01-16 03:14 UTC, pearmini commented on src/runtime/plot.ts
> +    return Array.from(viewContainer.entries()).map(([view, container]) => ({
- 一个 container 对于一个视图，enterContainer 对应所有新增视图，updateContainer 对应更新的视图。
- enterContainer 和 updateContainer 是两个没有重叠部分，这里都分别只遍历一次。

这里抽处理出来的原因是 enterContainer 和 updateContainer 没有办法合并处理，这样会把两者混合，它们的处理逻辑其实是不一样的。如何不抽象函数可能如下处理：

```js
const [enterInstances, updateInstances] = [
  Array.from(enterContainer.entries()),
  Array.from(updateContainer.entries()),
].map((d) => {
  /* ... */
});
```

你是觉得这样处理会好一点吗？

2023-01-16 04:55 UTC, hustcc commented on src/runtime/plot.ts
> +            const interactions = this['nameInteraction'].values();
嗯，后面统一来一个 this 的治理，尽量显示的在参数中声明好。

2023-01-16 04:57 UTC, hustcc commented on src/runtime/plot.ts
> +    return Array.from(viewContainer.entries()).map(([view, container]) => ({
就是 viewInstanceof 中 map 和 下面的 for 循环合并到一起，在一个循环中搞定。当然如果 container 数量级就是个位、十位量级的，直接忽略好了。

2023-01-16 05:08 UTC, pearmini commented on src/runtime/plot.ts
> +    return Array.from(viewContainer.entries()).map(([view, container]) => ({
哦哦哦，这个意思呀，不过这个 container 的数量级确实是个位和十位的量级。

2023-01-16 05:08 UTC, pearmini commented on src/runtime/plot.ts
> +            const interactions = this['nameInteraction'].values();
好的。

2023-01-16 08:00 UTC, merged