Feat/multi mask actions
antvis/G2 pull request #4589
Opened 2023-01-16 07:54 UTC by kakacookie

* **🎯 背景**: 项目业务需要在 AntV G2 气泡图中圈选出多个群组，每个群组的详细数据联动渲染在联动 AntV S2 交叉表上。因此需要实现多选模式的遮罩交互

* **🎨 效果**:
  - 动图
    - [rect-multi-mask.gif](https://img.alicdn.com/imgextra/i1/O1CN017YLP4G20CPChU3gPn_!!6000000006813-1-tps-728-512.gif)
![rect-multi-mask](https://img.alicdn.com/imgextra/i1/O1CN017YLP4G20CPChU3gPn_!!6000000006813-1-tps-728-512.gif "rect-multi-mask")

    - [x-rect-multi-mask.gif](https://img.alicdn.com/imgextra/i2/O1CN01PVHFdF1x5aSdxkVLS_!!6000000006392-1-tps-694-476.gif)
![x-rect-multi-mask](https://img.alicdn.com/imgextra/i2/O1CN01PVHFdF1x5aSdxkVLS_!!6000000006392-1-tps-694-476.gif "x-rect-multi-mask")

    - [y-rect-multi-mask.gif](https://img.alicdn.com/imgextra/i1/O1CN01v6aK4Q29wVcD2Kf0w_!!6000000008132-1-tps-728-512.gif)
![y-rect-multi-mask](https://img.alicdn.com/imgextra/i1/O1CN01v6aK4Q29wVcD2Kf0w_!!6000000008132-1-tps-728-512.gif "y-rect-multi-mask")

    - [circle-multi-mask.gif](https://img.alicdn.com/imgextra/i3/O1CN01Srw9W01zT3zS4Lokh_!!6000000006714-1-tps-728-512.gif)
![circle-multi-mask](https://img.alicdn.com/imgextra/i3/O1CN01Srw9W01zT3zS4Lokh_!!6000000006714-1-tps-728-512.gif "circle-multi-mask")

    - [path-multi-mask.gif](https://img.alicdn.com/imgextra/i2/O1CN01ads8fz1GfkFdGTSjX_!!6000000000650-1-tps-728-512.gif)
![path-multi-mask](https://img.alicdn.com/imgextra/i2/O1CN01ads8fz1GfkFdGTSjX_!!6000000000650-1-tps-728-512.gif "path-multi-mask")

    - [smooth-path-multi-mask.gif](https://img.alicdn.com/imgextra/i2/O1CN01beKwr928IpgnqgdJu_!!6000000007910-1-tps-728-512.gif)
![smooth-path-multi-mask](https://img.alicdn.com/imgextra/i2/O1CN01beKwr928IpgnqgdJu_!!6000000007910-1-tps-728-512.gif "smooth-path-multi-mask")

  - 相关交互
    - 光标在某个 mask 上拖动时，可移动该 mask
    - 光标在某个 mask 上双击时，可清除该 mask
    - 光标不在任何 mask 上时双击，可清除所有 mask

* **🎏 实现**:
  - 创建了一个 MultipleMaskBase 作为各种 multi-mask action 的基类。MultipleMaskBase 与原本的 MaskBase 类似，不同点是使用数组 maskShapes 保存多个 mask shape， 使用 recordPoints 记录每一次圈选操作过程的坐标点

  - 基于 MultipleMaskBase 创建了 rect, dim-rect, circle, path, smooth-path 的 multiple actions，它们的属性方法都复用了原 MaskBase 对应子类的方法

  - 修改了识别 mask context 和获取 mask 选中元素的相关方法，秉承开放封闭的原则，添加了支持 multi-mask 的逻辑

  - 更新了 multi-mask 的 api，仿照原有 api 写法，仅添加了 rect, circle, path 3种

  - 添加了 multi-mask action 的测试用例，包含了所有类型的 multi-mask action

  - 在内置交互中添加了element-x-multi-range-highlight，用于在图表示例中展示

2023-01-16 14:39 UTC, pearmini requested changes
很厉害👍

2023-01-16 14:39 UTC, pearmini commented on src/interaction/action/util.ts
> +export function getMaskPathByMaskShape(maskShape, tolerance: number) {
这个方法需要 export 出去吗？

2023-01-16 14:39 UTC, pearmini commented on src/interaction/action/mask/multiple/base.ts
> +      return !isEmpty && maskShape.isHit(currentPoint.x, currentPoint.y)
有点好奇这里为啥没有分号了？

2023-01-16 14:39 UTC, pearmini commented on src/interaction/action/util.ts
> +      return maskPathList.map((maskPath) => getElementsByPath(context.view, maskPath)).flat();
这里是不是可以用 flatMap？

2023-01-16 14:39 UTC, pearmini commented on src/interaction/action/mask/circle.ts
> +    const currentPoint = last(points);
我觉得把每种 mask 的 getMaskAttrs 抽成一个纯函数会好一点，对可读性和可维护性都更友好。

```js
// circle.ts
function getMaskAttrs(points) {
   //...
}

class CircleMask extends MaskBase {
  protetcted getMaskAttrs() {
    getMaskAttrs(this.points)
  }
}
```
```js
// multiple/circle.ts
import { getMaskAttrs } '../circle';
class CircleMask extends MultipleMaskBase {
  protected getMaskAttrs = getMaskAttrs
}
``

2023-01-17 03:18 UTC, kakacookie commented on src/index.ts
> +registerInteraction('element-x-multi-range-highlight', {
嗯嗯

2023-01-17 03:20 UTC, kakacookie commented on src/interaction/action/util.ts
> +export function getMaskPathByMaskShape(maskShape, tolerance: number) {
测试业务用了一下，不需要 export，去掉了

2023-01-17 03:21 UTC, kakacookie commented on src/interaction/action/mask/multiple/base.ts
> +      return !isEmpty && maskShape.isHit(currentPoint.x, currentPoint.y)
后来改的，忘记执行 prettier 了，加上了

2023-01-17 03:21 UTC, kakacookie commented on src/interaction/action/util.ts
> +      return maskPathList.map((maskPath) => getElementsByPath(context.view, maskPath)).flat();
学到了👍🏻

2023-01-17 03:21 UTC, kakacookie commented on src/interaction/action/mask/circle.ts
> +    const currentPoint = last(points);
嗯嗯，你这个方案更好~~👍🏻

2023-01-17 06:11 UTC, pearmini approved these changes
🚀🚀🚀

2023-01-17 06:35 UTC, merged