feat: add api for chart&mark to get view instance
antvis/G2 pull request #4590
Opened 2023-01-17 03:10 UTC by pepper-nice

2023-01-17 03:30 UTC, pearmini requested changes

2023-01-17 03:30 UTC, pearmini commented on src/api/mark/base.ts
> +  }
这个叫 getScale 就行，因为其实返回的是一个 Scale 对象。

2023-01-17 03:30 UTC, pearmini commented on src/api/mark/base.ts
> +  getScale(channel: string): Scale {
这个叫  `getScaleByChannel` 会好一点？和 `getNodeByKey` 会统一点。

2023-01-17 03:30 UTC, pearmini commented on src/api/composition/base.ts
> +    return selectGroupByKey(chartGroup, key);
这个封装的目的是? 直接 `chartGroup.getElementByKey(key)` 就好了？

2023-01-17 03:30 UTC, pearmini commented on src/api/mark/base.ts
> +    return markState.get(markKey);
这里直接 `return markState.get(this.attr('key'))` 就好了？

2023-01-17 03:30 UTC, pearmini commented on src/api/mark/base.ts
> +    return selectGroupByKey(chartGroup, key);
`chartGroup.getElementByKey(key)`

2023-01-17 03:30 UTC, pearmini commented on src/utils/selection.ts
> +
这个方法其实就是 `root.getElementByKey(key)`，所以就不需要封装了？

2023-01-17 03:30 UTC, pearmini commented on __tests__/unit/api/mark.spec.ts
> +      expect(interval.getGroup().id).toEqual(interval.attr('key'));
这里 `getMark` 和 `getScaleByChannel` 也需要测试一下。

2023-01-17 03:32 UTC, pearmini requested changes
如果我们约定了通过 `get` 前缀去获得一些**非 options 的属性**，那么是否还应该做如下的修改？

 - `chart.context` -> `chart.getContext`
 - `chart.node` -> `chart.getNode`

2023-01-17 12:47 UTC, pepper-nice commented on src/api/mark/base.ts
> +    return markState.get(markKey);
不行。markState是map，key时mark option。value是mark实例。

<img width="501" alt="image" src="https://user-images.githubusercontent.com/109653633/212902537-11f37db7-039d-4913-9f31-72a6b6b8f945.png">

不知道你这么设计有什么使用上的特殊需求吗？其实我觉得MarkState可以改为：
```ts
Map<string, G2MarkState >
```

2023-01-17 13:03 UTC, pepper-nice commented on src/api/mark/base.ts
> +  getScale(channel: string): Scale {
已修改

2023-01-18 02:52 UTC, pearmini commented on src/api/mark/base.ts
> +    return markState.get(markKey);
`mark` 对应的是用户传入的 mark options，`markState` 是内部生成的数据。

2023-01-18 02:54 UTC, pearmini approved these changes

2023-01-18 03:25 UTC, merged