feat(interaction): add poptip
antvis/G2 pull request #4597
Opened 2023-01-22 08:41 UTC by pearmini

# poptip

之前是 ellipsisText，但是和目前其他交互的名字形式不统一，同时本来的含义就是展示气泡提示框，所以被目前改名为 `poptip`。

## 案例

![poptip](https://user-images.githubusercontent.com/49330279/213907355-5311e6eb-9a9b-4780-b665-687956352caa.gif)

```ts
export function unemploymentAreaPoptip(): G2Spec {
  return {
    width: 800,
    type: 'area',
    data: {
      type: 'fetch',
      value: 'data/unemployment-by-industry.csv',
    },
    encode: {
      x: 'date',
      y: 'unemployed',
      color: 'industry',
    },
    transform: [{ type: 'stackY' }],
    axis: { y: { labelFormatter: '~s' } },
    legend: { color: { size: 60, layout: 'grid', gridCol: 6, gridRow: 3 } },
    interactions: [{ type: 'poptip' }],
  };
}
```

![poptip-styled](https://user-images.githubusercontent.com/49330279/213907372-9821926e-b77e-4d4c-9533-eb39c3ff786b.gif)

```ts
export function unemploymentAreaPoptipStyled(): G2Spec {
  return {
    width: 800,
    type: 'area',
    data: {
      type: 'fetch',
      value: 'data/unemployment-by-industry.csv',
    },
    encode: {
      x: 'date',
      y: 'unemployed',
      color: 'industry',
    },
    transform: [{ type: 'stackY' }],
    axis: { y: { labelFormatter: '~s' } },
    legend: { color: { size: 60, layout: 'grid', gridCol: 6, gridRow: 3 } },
    interactions: [{ type: 'poptip', tipBackgroundColor: 'red' }],
  };
}
```

2023-01-28 07:23 UTC, hustcc requested changes

2023-01-28 07:23 UTC, hustcc commented on src/interaction/native/poptip.ts
> +        label.removeEventListener('pointermove', pointermove);
1. 事件监听会非常多。应该使用时间代理的方式。
2. 目前只处理了 legend，应该只要是文本被省略掉的地方都需要处理，比如 axis，label 等。

之前的约定方式是，事件来源是 Text 才处理，如果 Text 组件中有 tip 信息，则 hover 的时候展示 tip 文本信息，否则都处理。所以在 gui 中做组件文本省略的时候，需要在 tip 属性中写入原始文本。

2023-01-29 02:11 UTC, pearmini commented on src/interaction/native/poptip.ts
> +        label.removeEventListener('pointermove', pointermove);
ok，那我改一下

2023-01-29 03:41 UTC, pearmini commented on src/interaction/native/poptip.ts
> +        label.removeEventListener('pointermove', pointermove);
gui 中做组件文本省略的时候，有 tip 属性吗？@Aarebecca

2023-01-29 04:06 UTC, Aarebecca commented on src/interaction/native/poptip.ts
> +        label.removeEventListener('pointermove', pointermove);
> gui 中做组件文本省略的时候，有 tip 属性吗？@Aarebecca

目前没有这个属性，不过可以考虑在封装 Text 组件中添加

2023-01-29 04:14 UTC, Aarebecca commented on src/interaction/native/poptip.ts
> +        label.removeEventListener('pointermove', pointermove);
> > gui 中做组件文本省略的时候，有 tip 属性吗？@Aarebecca
> 
> 目前没有这个属性，不过可以考虑在封装 Text 组件中添加

现在采用的 G 提供的文本缩略，所以直接读取 Text.attributes.text 的值就是原始的文本，不过需要结合 wordWrapWidth、maxLines、textOverflow 属性来判断当前文本是否被缩略，目前 G 没有给到这样一个标识符

2023-01-29 10:50 UTC, hustcc commented on src/interaction/native/poptip.ts
> +        label.removeEventListener('pointermove', pointermove);
@xiaoiver 看看 G.Text 是否可以增加这样的标示~

2023-01-30 06:28 UTC, pearmini commented on src/interaction/native/poptip.ts
> +        label.removeEventListener('pointermove', pointermove);
> > > gui 中做组件文本省略的时候，有 tip 属性吗？@Aarebecca
> > 
> > 
> > 目前没有这个属性，不过可以考虑在封装 Text 组件中添加
> 
> 现在采用的 G 提供的文本缩略，所以直接读取 Text.attributes.text 的值就是原始的文本，不过需要结合 wordWrapWidth、maxLines、textOverflow 属性来判断当前文本是否被缩略，目前 G 没有给到这样一个标识符

这里我觉得直接把完整文本的信息放在 axis 和 legend 的 style.tip 里面就行了，不需要判断是否省略。

2023-01-30 07:22 UTC, Aarebecca commented on src/interaction/native/poptip.ts
> +        label.removeEventListener('pointermove', pointermove);
我觉得这块还是放到 G 的 Text 中会好一些，tip 对于 axis 和 legend 来说没有必要分别做这个工作

2023-01-30 07:46 UTC, pearmini commented on src/interaction/native/poptip.ts
> +        label.removeEventListener('pointermove', pointermove);
不论 G 是否内置这个属性，tip 这个属性都是要在 axis 和 legend 中设置。

2023-01-31 05:31 UTC, Aarebecca commented on src/component/legendCategory.ts
> +      gridCol: gridCol ?? finalGridCol,
这块逻辑放到 `inferLayout ` 好些吧

2023-01-31 05:36 UTC, Aarebecca commented on src/interaction/native/poptip.ts
> +      const tipELement = new HTML({
所有的 tip 共用一个 element 会不会好些，这样反复 new、delete 会有一定性能损耗

2023-01-31 06:07 UTC, pearmini commented on src/component/legendCategory.ts
> +      gridCol: gridCol ?? finalGridCol,
主要这里是不想去动 inferLayout 代码，这样可以更清晰的看出用户指定的 gridRow 的优先级比 infer 出来的高。

2023-01-31 06:11 UTC, pearmini commented on src/interaction/native/poptip.ts
> +      const tipELement = new HTML({
之后也许会出现多个 poptip 的情况，所以每一个 text 应该绑定一个 poptip，而不是共用一个。这里的 new 和 delete 性能损耗也不大。

2023-01-31 06:14 UTC, hustcc commented on src/interaction/native/poptip.ts
> +      const tipELement = new HTML({
我也建议是保留一个实例，poptip 类似于 tooltip 一样，都是单一实例。

2023-01-31 06:24 UTC, hustcc approved these changes

2023-01-31 11:55 UTC, merged