feat: adapt to gui axis animation
antvis/G2 pull request #4634
Opened 2023-02-09 10:48 UTC by Aarebecca

* now axis support animation, usage: 
```ts
  chart
    .interval()
    .encode('x', 'genre')
    .encode('y', 'sold')
    .encode('color', 'genre')
    .axis({ x: { animate: false }, y: { animate: { duration: 1000 } } });
```

* fix site demos

2023-02-09 11:09 UTC, pearmini requested changes
- `src/composition/timingKeyframe.ts` 是不是需要也指定一下 component 的动画？ 
- 怎么感觉[这张图](__tests__/integration/snapshots/animation/iris-point-shapes-keyframe/interval2-2.png)的 x 轴的 title 没有跟着一起移动？

![image](https://user-images.githubusercontent.com/49330279/217796361-b3bdc934-dd64-4b6e-b700-536804b1e2ed.png)

2023-02-09 11:14 UTC, Aarebecca commented
> * `src/composition/timingKeyframe.ts` 是不是需要也指定一下 component 的动画？
> * 怎么感觉[这张图](__tests__/integration/snapshots/animation/iris-point-shapes-keyframe/interval2-2.png)的 x 轴的 title 没有跟着一起移动？
> 
> ![image](https://user-images.githubusercontent.com/49330279/217796361-b3bdc934-dd64-4b6e-b700-536804b1e2ed.png)

看它下一帧的截图的话感觉是刚好截图的时机卡到了label动画之后，因为 title 的位置调整总是会比 label 慢。不过我一会儿确认下

2023-02-09 11:43 UTC, pearmini commented
> > * `src/composition/timingKeyframe.ts` 是不是需要也指定一下 component 的动画？
> > * 怎么感觉[这张图](__tests__/integration/snapshots/animation/iris-point-shapes-keyframe/interval2-2.png)的 x 轴的 title 没有跟着一起移动？
> > 
> > ![image](https://user-images.githubusercontent.com/49330279/217796361-b3bdc934-dd64-4b6e-b700-536804b1e2ed.png)
> 
> 看它下一帧的截图的话感觉是刚好截图的时机卡到了label动画之后，因为 title 的位置调整总是会比 label 慢。不过我一会儿确认下

也许是 title 的 animation 对象没有返回？

2023-02-10 03:22 UTC, pearmini commented
> 这里由于 title 依赖于 label 的 animation，所以没有返回

可以返回吗？

2023-02-10 09:32 UTC, pearmini approved these changes

2023-02-10 09:33 UTC, merged