fix(animate): 部分动画覆盖 callback 配置导致外部的 callback 配置失效
antvis/G2 pull request #4678
Opened 2023-02-22 08:11 UTC by zhaokejian

* **G2 Version**: v4
fixes #4627

内置动画通过 callback 实现时确保外部 callback 配置生效

2023-02-22 08:28 UTC, pearmini requested changes
加一个单测测试这种情况？防止这个问题再出现！

2023-02-28 14:41 UTC, zhaokejian commented
> 加一个单测测试这种情况？防止这个问题再出现！

done

2023-03-02 01:51 UTC, pearmini reviewed
👍

2023-03-02 01:52 UTC, pearmini approved these changes

2023-03-02 01:53 UTC, merged