feat(MarkBase): change the name from MarkBase to Mark (related #4672)
antvis/G2 pull request #4689
Opened 2023-02-23 07:51 UTC by pepper-nice

2023-02-23 12:29 UTC, pearmini requested changes

2023-02-23 12:29 UTC, pearmini commented on src/api/composition/facetCircle.ts
> +export interface FacetCircle extends Composition, MarkNode {
如何比较统一的话 Composition 最好也改成 CompositionNode 会好一点，但是也不是很紧急，可以之后再改。

2023-02-23 12:29 UTC, pearmini commented on src/runtime/types/component.ts
> +  | IMark
这里不要改成 IMark，有两个原因：

- 其实的 type 没有 I
- I 主要是 Interface 的意思，虽然大部分情况 interface 和 type 是一样的，但是从语义上讲是接口，没有类型（type）准确。

需要是冲突了，可以在冲突的地方重命名：

```ts
import { Mark as G2Mark } from '../runtime' // 类似这种
```

2023-02-24 02:04 UTC, pepper-nice commented on src/runtime/types/component.ts
> +  | IMark
G2Mark 也被占用了的。改为`MarkOptions`？

2023-02-24 03:46 UTC, pearmini commented on src/runtime/types/component.ts
> +  | IMark
哦哦哦，你的意思是 api 里面的 Mark 和 runtime 里面的 Mark 冲突了呀。那这样吧：MarkBase -> MarkNode，其余的都不用改。

2023-02-24 03:48 UTC, pearmini commented on src/api/composition/facetCircle.ts
> +export interface FacetCircle extends Composition, MarkNode {
这个不用改了。

2023-02-24 08:54 UTC, pearmini requested changes

2023-02-24 08:54 UTC, pearmini commented on __tests__/unit/api/mark.spec.ts
> +describe.only('MarkNode', () => {
把这个 only 去掉？应该是我之前不小心加上了😭

2023-02-24 09:03 UTC, pearmini approved these changes

2023-02-24 11:53 UTC, merged