feat(event): add more bubbles event
antvis/G2 pull request #4716
Opened 2023-03-01 09:43 UTC by pearmini

# Event

抛出更多 element 的事件。

- click
- dbclick

pointer 事件：

- pointertap
- pointerdown
- pointerup
- pointerover
- pointerout
- pointermove
- pointerenter
- pointerleave
- pointerupoutside

拖拽事件：

- dragstart
- drag
- dragend
- dragenter
- dragleave
- dragover
- drop

## 注意

如果希望 rightup 事件生效，需要禁止默认的 contextmenu 事件。

```js
const chart = new Container({ container });

chart.on('element:rightup', console.log);

// 禁止默认的 contextmenu 事件。
container.addEventListener('contextmenu', (e) => {
  e.preventDefault();
});
```

如果希望监听拖拽事件，需要设置 draggable 和 droppable 属性。

```js
chart.interval().style('draggable', true).style('droppable', true);
```

## 讨论

有了 `pointer*` 事件，还是否需要 `mouse*` 事件？@xiaoiver 的建议是不加，因为 pointer 事件已经包含了。

2023-03-01 09:48 UTC, Aarebecca commented on __tests__/plots/api/chart-on-item-element.ts
> +  gCanvas
要使用 `rightup` 事件的话，就必须用户像这样手动阻止默认事件行为吗，感觉下面的写法不太友好欸

2023-03-01 09:52 UTC, Aarebecca commented
>  pointer 事件已经包含了

是指同时监听 mouse 事件 和 pointer 事件的话会导致多次触发吗

2023-03-01 11:41 UTC, pearmini commented on __tests__/plots/api/chart-on-item-element.ts
> +  gCanvas
嗯嗯，确实不太友好。但是默认禁止 contextmenu 其实也不合理，因为有些用户其实就是需要这种能力，比如浏览器自带的将 canvas 保存成截图的能力。


当然，更好的做法是提供一种更优化的方式去禁止默认的 contextmenu 事件，比如如下：

```js
chart.on('contextmenu', (e) => {
  e.preventDefault();
});
```

这个我觉得可以后面再加。

2023-03-01 15:32 UTC, hustcc commented
right 事件有点怪怪，是有其他封装逻辑吗

2023-03-02 01:18 UTC, hustcc commented
官网的文档也加一下，事件枚举、用法。

2023-03-02 01:49 UTC, pearmini commented
> right 事件有点怪怪，是有其他封装逻辑吗

right 是 G 支持的原生事件，鼠标右键事件，G2 这里没有做啥逻辑封装。@xiaoiver G 里面是封装了吗？

2023-03-02 01:49 UTC, pearmini commented
> 官网的文档也加一下，事件枚举、用法。

嗯嗯，我把官网的问题修复了之后就加。

2023-03-02 02:02 UTC, Aarebecca approved these changes

2023-03-02 02:33 UTC, xiaoiver requested changes

2023-03-02 02:33 UTC, xiaoiver commented on src/interaction/native/event.ts
> +    container.addEventListener('rightdown', rightdown);
建议去掉 rightdown / up，鼠标左键和右键都会在 pointerdown / up 中触发，区分两者的方法是通过事件对象的 `e.button` 判断，`2` 代表右键触发。

https://developer.mozilla.org/zh-CN/docs/Web/API/MouseEvent/button#%E8%BF%94%E5%9B%9E%E5%80%BC

2023-03-02 02:33 UTC, xiaoiver commented on src/interaction/native/event.ts
>      container.addEventListener('click', click);
click / dblclick 我觉得可以保留，尽管我们提供了 `pointertap` 这一事件尝试统一 鼠标、触摸屏和 pen，然后通过 [detail](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail) 区分单双击。理由还是用户习惯问题，前者毕竟太常用了。

2023-03-02 02:33 UTC, xiaoiver commented on src/interaction/native/event.ts
> +    container.addEventListener('dragend', dragend);
4.0 中 Drag 'n' Drop 实现的并不完整，我们目前通过 [g-plugin-dragndrop](https://g.antv.antgroup.com/plugins/dragndrop) 插件支持了完整的 [HTML_Drag_and_Drop_API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)，这里缺失了 Drop 相关的事件（target 为放置区域的图形，而 drag / start / end 的 target 为被拖动的图形）：
* dragenter 有图形被拖入该区域
* dragleave 有图形被拖离该区域
* dragover 有图形正在划过该区域
* drop 有图形放置在该区域

且它们都是支持冒泡的。

2023-03-02 02:33 UTC, xiaoiver commented on src/interaction/native/event.ts
> +    container.addEventListener('rightdown', rightdown);
另外这里缺少了几个 PointerEvent 和 WheelEvent：
* pointermove
* pointerenter
* pointerleave
* pointerupoutside 这个可能有点难以理解，想象一下在一个圆上按下鼠标（触发 pointerdown），然后拖动一定距离到空白处再抬起（触发 pointerup）
* wheel

2023-03-02 02:38 UTC, xiaoiver commented
> > pointer 事件已经包含了
> 
> 是指同时监听 mouse 事件 和 pointer 事件的话会导致多次触发吗

会的，我们实现 PointerEvent 就是希望统一不同的输入设备，因此通过鼠标触发 mousedown 是一定会同时触发 pointerdown 的

![image](https://user-images.githubusercontent.com/3608471/222316244-b9a98124-17c0-4d26-a064-ff14243964cc.png)

https://g.antv.antgroup.com/api/event/intro

2023-03-02 02:40 UTC, xiaoiver commented
> right 事件有点怪怪，是有其他封装逻辑吗

浏览器实现 PointerEvent 的初衷就是希望统一现有的输入设备（Mouse、Touch、Pen），因此我们不希望用户感知它们的区别（当然通过 pointerType 也可以获取设备类型），例如只需要监听 pointerdown 就可以兼顾 PC、移动。

2023-03-02 02:42 UTC, pearmini commented on src/interaction/native/event.ts
> +    container.addEventListener('rightdown', rightdown);
嗯嗯，pointer 事件我都加上，right 事件去掉，wheel 事件暂时先不加。

2023-03-02 02:43 UTC, pearmini commented on src/interaction/native/event.ts
> +    container.addEventListener('dragend', dragend);
ok，我加上。

2023-03-02 05:12 UTC, xiaoiver approved these changes

2023-03-02 05:27 UTC, merged