feat: gauge mark
antvis/G2 pull request #4739
Opened 2023-03-08 03:02 UTC by pepper-nice

#### Feature
Add Gauge Mark
- [x] test
- [x] demo

#### Start
```js
import { Chart } from '@antv/g2';

const chart = new Chart ({
  container: 'container',
});
chart
  .data([{ target: 120, total: 400, name: 'score' }])
  .gauge()
chart.render();
```
<img width="488" alt="image" src="https://user-images.githubusercontent.com/109653633/223608620-d27b51f4-221c-46d9-9628-9bf44cd351a4.png">

**Custom Shape**
```js
const customShape = () => {
  return (points, value, coordinate, theme) => {
    const [cx, cy] = coordinate.getCenter();
    const [x, y] = getOrigin(points);
    return new Line({
      style: {
        x1: x,
        y1: y,
        x2: cx,
        y2: cy,
        stroke: '#30BF78',
        lineWidth: 5,
      },
    });
  };
};
return {
  type: 'gauge',
  data: [
    {
      target: 159,
      total: 424,
      name: 'score',
    },
  ],
  scale: {
     color: {
       domain: [100, 200, 424],
       range: ['#F4664A', '#FAAD14', 'green'],
     },
   },
  style: {
    indicatorShape: customShape,
    textContent: (target, total) => {
      return `得分：${target}\n占比：${(target / total) * 100}%`;
    },
  },
};
```
<img width="478" alt="image" src="https://user-images.githubusercontent.com/109653633/223608923-13a83b53-719b-42af-a344-4767c022b5b0.png">

2023-03-08 03:55 UTC, pearmini requested changes
- gauge 应该是一个 mark，而不是一个 composition。目前 coordinate 可以设置在 view 层面。

```js
const options = {
  type: 'interval',
  coordinate: {},
}
```

- 对应的 chart API 也增加一下

2023-03-08 04:55 UTC, pearmini commented on src/composition/Gauge.ts
> +        }),
这里的 radius 不一定要用 coordinate 的 outerRadius 的？可以直接把它 shape 的参数？这样就可以用一个 coordinate 了？

2023-03-08 05:04 UTC, pepper-nice commented on src/composition/Gauge.ts
> +        }),
应该不行。pointer 我是通过 point mark 绘制的。 point 的半径位置只能通过 coordinate 来设置吧

2023-03-08 05:14 UTC, pearmini commented on src/composition/Gauge.ts
> +        }),
point 半径有很多设置方法，这里比较合理的是，你在 style 里面任意的加一个属性比如 radius，然后在 shape 里面拿到 radius 根据 coordinate 的大小计算。

2023-03-08 06:05 UTC, visiky reviewed
`src/composition/Gauge.ts` 文件命名为什么不用小写呢？看着有些不协调

2023-03-10 03:54 UTC, pepper-nice commented
gauge 应该没有 tooltip，我看 echarts、G2 都没有做过。

2023-03-10 03:56 UTC, pepper-nice commented on src/mark/gauge.ts
> +        ...resOptions,
是的，除了 style 以外，他们使用的配置应该都是通用的。

2023-03-10 05:34 UTC, pearmini commented
> gauge 应该没有 tooltip，我看 echarts、G2 都没有做过。

ok

2023-03-10 05:40 UTC, pearmini requested changes

2023-03-10 05:40 UTC, pearmini commented on src/mark/gauge.ts
> +        ...resOptions,
animation 呢？我看 animation 还没有处理？

2023-03-10 05:40 UTC, pearmini commented on __tests__/unit/api/chart.spec.ts
>      expect(chart.options().children).toEqual([
还需要在 api/mark.spec.ts 里面测试一下 gauge 的的属性设置。

2023-03-10 07:05 UTC, pearmini requested changes

2023-03-10 07:05 UTC, pearmini commented on __tests__/unit/api/mark.spec.ts
> +    expect(setCompositeOptions(node).value).toEqual(getCompositeOptions());
这个地方应该 `setOptions` 就好， gauge 没有 layout 属性

2023-03-10 07:05 UTC, pearmini commented on src/mark/gauge.ts
> +        },
这里 text animation 应该也要加上？

2023-03-10 07:05 UTC, pearmini commented on src/spec/mark.ts
> +};
这个地方应该不用加，data 里面应该有 any（之后通过范型去掉），并且完整的 type 也应该是：

```ts
{ data: { value: {name:string, percent: number }} }
```

2023-03-10 08:00 UTC, pearmini approved these changes
LGTM

2023-03-10 15:14 UTC, merged