feat: adapt to gui 0.5.0-alpha.5
antvis/G2 pull request #4752
Opened 2023-03-11 14:28 UTC by Aarebecca

* 适配关闭 CSS Parse
* 适配 GUI 0.5 API
* 预览环境支持查找

⚠️ 剩余问题待 [@xiaoiver](https://github.com/antvis/G/commits?author=xiaoiver) 解决
绘制轮廓异常：（共 20 个用例异常）

![alphabetIntervalDataDrivenStyled-diff](https://user-images.githubusercontent.com/25787943/224489799-f113a276-3f62-4e3c-bc77-5fa608d157c2.png)
![disastersPointBubble-diff](https://user-images.githubusercontent.com/25787943/224489801-e4318f0a-61bc-4eca-a659-5e845e4c4220.png)
![githubStarIntervalThemeAcademy-diff](https://user-images.githubusercontent.com/25787943/224489821-90ee5046-837c-4be8-a6f9-e870e51ceff5.png)
![morleyBox-diff](https://user-images.githubusercontent.com/25787943/224489832-5030f13f-bb81-415e-bea6-6d8674dac446.png)

交互异常：
* BrushFilter 无法二次刷选，且刷选后 Tooltip 异常，见 profitIntervalBrushFilter 、penguinsPointBrushFilter等
* 刷选蒙版异常，见 indicesLineChartFacetBrushShared
<img width="695" alt="image" src="https://user-images.githubusercontent.com/25787943/224490161-4ed6f8f7-cf37-4a01-841d-f78d344d605c.png">

不确定：
* scoreByItemAreaRadar
<img width="560" alt="image" src="https://user-images.githubusercontent.com/25787943/224489995-b6a51044-61e6-4d91-8b4a-374d76722a43.png">

2023-03-13 03:07 UTC, xiaoiver commented
这个几个例子我认为不能算问题：
* peguins
* morleyBox

应该是 node-canvas 的绘制误差。理由如下，以 boxplot 为例：

![30-morleyBox-diff](https://user-images.githubusercontent.com/3608471/224598568-45edca56-bebd-4776-b57f-68a0225249fb.png)

每个 box 其实都是一条 Path 绘制的，但观察相邻两根线的粗细都是有差别的：
![test2](https://user-images.githubusercontent.com/3608471/224599068-7d40adfb-b938-4526-ae8d-56eb7f6d5de1.png)


而实际浏览器运行效果是粗细一致的（本来其实就是一根 Path）：
<img width="421" alt="截屏2023-03-13 上午10 54 24" src="https://user-images.githubusercontent.com/3608471/224598743-1ba8200e-abb8-4cd5-8fd5-f1d1acdd3fdf.png">

2023-03-18 08:55 UTC, pearmini requested changes

2023-03-18 08:55 UTC, pearmini commented on src/interaction/brushFilter.ts
> +                ...(hideX && { x: { labelOverlap: [{ type: 'hide' }] } }),
透传了 labelOverlap？

2023-03-18 08:55 UTC, pearmini commented on src/interaction/sliderFilter.ts
> +          x: { labelOverlap: [{ type: 'hide' }] },
同上

2023-03-18 08:55 UTC, pearmini commented on src/runtime/plot.ts
> +      // zIndex: 0,
删除

2023-03-18 10:57 UTC, pearmini approved these changes

2023-03-18 10:57 UTC, merged