fix: Horizontal cylindrical bar display error
antvis/G2 pull request #4764
Opened 2023-03-14 05:35 UTC by wuhaiyang

* **G2 Version**: v5 fix: [水平圆角柱状图展示有错误](https://github.com/antvis/G2/issues/4761)
* **Mini Showcase(like screenshots)**:
   - before: 
    ![image](https://user-images.githubusercontent.com/49330279/224692492-3f4fd30f-410c-43e0-aeab-d9fb832c0586.png)
    
    ![image](https://user-images.githubusercontent.com/8447716/224905651-b3fa74c0-24ee-48ac-81a2-7e7b62945b3b.png)

   - after:
     
    ![image](https://user-images.githubusercontent.com/8447716/224905162-79c5c9d4-5132-487e-9ab1-6300f58e0090.png)
    ![image](https://user-images.githubusercontent.com/8447716/224905493-2b34878b-e597-4c91-a0be-812963213c15.png)

* **CodePen Link**:

2023-03-14 06:45 UTC, pearmini requested changes
对于有新增测试案例的情况，需要本地运行一下 `npm t` 生成基准截图。

2023-03-14 06:45 UTC, pearmini commented on src/shape/interval/color.ts
> +      ),
下面这种写法的可读性会好一点？

```js
...Object.fromEntries(standardDir.map((d, i) => [d, standardDirRadius[i]])),
```

2023-03-14 06:45 UTC, pearmini commented on src/shape/interval/color.ts
> +      standardDir.splice(standardDir.length, 0, ...standardDir.splice(0, 1));
下面的写法可读性会好一点？

```js
standardDir.push(standardDir.shift())
```

2023-03-14 06:45 UTC, pearmini commented on src/shape/interval/color.ts
> +    // transpose: rotate it clockwise by 90
G2 的注释规范是首字母大写，然后加句号。

```js
//  Rotate it clockwise by 90 in the transpose coordinate.
```

2023-03-14 14:26 UTC, wuhaiyang commented on src/shape/interval/color.ts
> +      ),
已经修复

2023-03-14 14:26 UTC, wuhaiyang commented on src/shape/interval/color.ts
> +      standardDir.splice(standardDir.length, 0, ...standardDir.splice(0, 1));
已修改

2023-03-14 14:26 UTC, wuhaiyang commented on src/shape/interval/color.ts
> +    // transpose: rotate it clockwise by 90
已修复

2023-03-15 07:01 UTC, pepper-nice approved these changes

2023-03-15 07:06 UTC, pearmini approved these changes

2023-03-15 07:06 UTC, merged