feat: theme set as default
antvis/G2 pull request #4765
Opened 2023-03-14 10:23 UTC by pepper-nice

https://github.com/antvis/G2/discussions/4760

2023-03-14 11:14 UTC, Aarebecca commented on __tests__/unit/api/chart.spec.ts
> +    const chart = new Chart({ container });
这里为啥没有呢

2023-03-14 11:19 UTC, Aarebecca commented on __tests__/unit/api/chart.spec.ts
> +    const chart = new Chart({ container });
这里没有指定主题不会抛出异常吗

2023-03-14 11:20 UTC, pearmini requested changes

2023-03-14 11:20 UTC, pearmini commented on src/stdlib/index.ts
> +    'theme.darkClassic': Dark,
darkClassic -> classicDark

2023-03-14 11:20 UTC, pearmini commented on src/api/chart.ts
> -  { name: 'theme', type: 'object' },
这个应该不用去掉吧？`chart.theme` 这个 API 还是在的。

2023-03-14 11:20 UTC, pearmini commented on src/runtime/render.ts
> +    error('Please specify theme!');
可以多给一些信息：

```js
error('chartOptions.theme is required, such as classic.');
```

2023-03-15 02:02 UTC, pepper-nice commented on __tests__/unit/api/chart.spec.ts
> +    const chart = new Chart({ container });
这条 test 没有调用 render，所以我没加 theme

2023-03-15 02:07 UTC, pepper-nice commented on src/api/chart.ts
> -  { name: 'theme', type: 'object' },
<img width="614" alt="image" src="https://user-images.githubusercontent.com/109653633/225186260-bb1548a5-fb97-44cd-b1e8-fb6c2d17784a.png">
这里原本重复了，我删掉一个。

2023-03-15 02:22 UTC, pearmini commented on src/api/chart.ts
> -  { name: 'theme', type: 'object' },
哦哦哦，好的！

2023-03-15 02:29 UTC, pearmini approved these changes

2023-03-15 06:15 UTC, merged