feat: bullet mark
antvis/G2 pull request #4767
Opened 2023-03-15 06:56 UTC by pepper-nice

#### 使用
基础图表
```js
{
  type: 'bullet',
  data: {
    value: {
      title: '满意度',
      actual: [60],
      target: [80],
      range: [100],
    },
  },
  axis: {
    y: {
      grid: {},
      title: null,
    },
  },
}
```
<img width="610" alt="image" src="https://user-images.githubusercontent.com/109653633/225225895-ad3b03d4-9d60-46ed-9b3c-1cd4c4ea721b.png">

多区间
```js
{
  type: 'bullet',
  coordinate: { transform: [{ type: 'transpose' }] },
  data: {
    value: {
      title: '满意度',
      actual: [
        { title: '一季度实际值', value: 24 },
        { title: '二季度实际值', value: 32 },
      ],
      target: [{ title: '目标值', value: 80 }],
      range: [
        { title: '差', value: 30 },
        { title: '良', value: 60 },
        { title: '优', value: 100 },
      ],
    },
  },
}
```
<img width="648" alt="image" src="https://user-images.githubusercontent.com/109653633/225225933-9ce1dd6b-2fcc-4af0-8651-c32a4e93a945.png">

2023-03-29 08:00 UTC, pearmini requested changes
数据格式保持和 G2 4.0 已经 Vega-Lite 一致：

- G2 4.0: https://g2-v4.antv.vision/zh/examples/other/other#bullet-graph
- Vega-Lite：https://vega.github.io/vega-lite/examples/facet_bullet.html

测试把上面两个案例加进去。

2023-04-20 02:20 UTC, pearmini requested changes

2023-04-20 02:20 UTC, pearmini commented on __tests__/plots/static/bullet-facet.ts
> +            target: [80],
这个不是分面

2023-04-23 03:38 UTC, pearmini requested changes
代码实现的挺整洁的，就是 API 设计有点问题：和之前有相似性的 Mark 不太一致，这个后续可以注意一下。然后还有一个问题：

- bullet 有 tooltip 吗？

2023-04-23 03:38 UTC, pearmini commented on src/mark/bullet.ts
> +    scale: {
这里不用 stack

2023-04-23 03:38 UTC, pearmini commented on src/mark/bullet.ts
> +    transform: [{ type: 'stackY' }],
这里也不用 stack

2023-04-23 03:38 UTC, pearmini commented on __tests__/plots/static/bullet-group.ts
> +      },
应该不支持在一个视图画多个子弹图，参考水波图。一个原因是它们的 y 比例尺不需要同步，这个是 boxplot 有区别的。

2023-04-23 03:38 UTC, pearmini commented on __tests__/plots/static/bullet-default.ts
> +  };
这里的 api 应该和 progressBar 这种保持一致：

```ts
export function bulletDefault(): G2Spec {
  return {
    type: 'bullet',
    coordinate: { transform: [{ type: 'transpose' }] },
    data: {
      value: {
        title: '重庆',
        ranges: [30, 90, 120],
        measures: [65],
        target: [80],
      },
    },
  };
}

```

2023-04-23 03:38 UTC, pearmini commented on __tests__/plots/static/bullet-space.ts
> +          },
这里应该通过分面而不是 space 来实现。

```js
const options = {
  type: 'faceRect',
  data: [
    {
      type: 'bullet',
      data: [
        {
          title: 'Profit',
          ranges: [20, 25, 60],
          measures: [21, 23],
          target: [55],
        },
      ],
    },
    {
      type: 'bullet',
      data: [
        {
          title: 'Order Size',
          ranges: [350, 500, 600],
          measures: [100, 320],
          target: [550],
        },
      ],
    },
    // ...
  ],
  encode: {
    x: 'title',
  },
  children: [{ type: 'bullet' }],
};
```

类似仪表盘的这个例子：https://github.com/antvis/G2/pull/4851

2023-04-23 03:44 UTC, pepper-nice commented on __tests__/plots/static/bullet-default.ts
> +  };
这个 API 我是和 vite 保持一致的。我改一下 progressBar的吧。保持统一

2023-04-23 04:59 UTC, pearmini commented on __tests__/plots/static/bullet-default.ts
> +  };
![image](https://user-images.githubusercontent.com/49330279/233820679-fe2c064e-35c1-48a1-be9f-95ca82bab46a.png)

Vega-Lite 也不是数组，它也是通过分面实现的。

2023-05-16 02:28 UTC, closed without merging