refactor(chart): update chart clear&destroy api
antvis/G2 pull request #4779
Opened 2023-03-16 09:35 UTC by pepper-nice

2023-03-16 09:39 UTC, pepper-nice commented on src/api/chart.ts
> +    const { container, canvas, key = CHART_KEY, ...rest } = options;
为 chart 添加了默认的 key，不需要用户显式指定。这样用户调用 chart.getGroup() 这些 API 时友好一些

2023-03-16 09:42 UTC, pearmini requested changes
参考 __tests__/unit/api/interaction.spec.ts 这里例子新增一个 chart.clear 清空交互的测试案例？

2023-03-16 09:42 UTC, pearmini commented on __tests__/unit/api/chart.spec.ts
> +import { CHART_KEY } from '../../../src/api/chart';
这个 Key 用来干啥的？

2023-03-16 09:42 UTC, pearmini commented on src/api/chart.ts
> +  }
暂时不加这个哈，直接用 `this._options = {}` 就行

2023-03-17 02:40 UTC, pearmini commented on __tests__/unit/api/chart.spec.ts
> +import { CHART_KEY } from '../../../src/api/chart';
ok

2023-03-17 02:57 UTC, pearmini requested changes

2023-03-17 02:57 UTC, pearmini commented on __tests__/unit/api/chart.spec.ts
> +    });
这个用 setTimout 的原因是？

2023-03-17 02:57 UTC, pearmini commented on __tests__/unit/api/chart.spec.ts
> +    });
可以用 `chart.render().then`?

2023-03-17 02:57 UTC, pearmini commented on __tests__/unit/api/chart.spec.ts
> +    });
同上

2023-03-19 08:49 UTC, pearmini requested changes

2023-03-20 02:09 UTC, pearmini approved these changes

2023-03-20 02:10 UTC, merged