docs: refactor site api
antvis/G2 pull request #4804
Opened 2023-03-20 07:43 UTC by pepper-nice

2023-03-20 08:00 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [mark.**_[component]_**](/spec/component/axis) - 添加 component 到该视图。
这个属性去掉，后面代码中也会去掉

2023-03-20 08:00 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [mark.**getNodeByType**](/api/mark#getNodeByType) - 根据 key 获取 children 对象组。
同理，分类（和 Chart 思路一样）

2023-03-20 08:01 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [chart.**style**](/spec/style/overview) - 添加 style 到该视图。
这里不是**添加**，是**设置该视图的样式**。

2023-03-20 08:01 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [chart.**theme**](/spec/theme/overview) - 添加 theme 到该视图。
设置 theme

2023-03-20 08:02 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [mark.**label**](/spec/label/overview) - 添加 label 到该视图。
设置 mark 的主题和数据标签

2023-03-20 08:03 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [spaceLayer.**coordinate**](/spec/coordinate/overview) - 申明该视图的 coordinate。
这些方法都没有

2023-03-20 08:03 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [spaceFlex.**coordinate**](/spec/coordinate/overview) - 申明该视图的 coordinate。
这些方法都没有

2023-03-20 08:04 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [spaceLayer.**rect**](/spec/mark/rect) - 添加一个 rect 标记到该视图。
这里不能叫**视图**，叫**复合视图**

2023-03-20 08:05 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [spaceRect.**getNodeByType**](/api/spaceRect#getNodeByType) - 根据 key 获取 children 对象组。
没有这个方法

2023-03-20 08:05 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [spaceRect.**render**](/api/spaceRect#render) - 渲染该视图。
没有个这些方法

2023-03-20 15:35 UTC, Aarebecca commented on site/docs/api/overview.zh.md
> +- [chart.**interval**](/spec/mark/interval) - 添加一个 interval 标记到该视图。
这里把 “一个” 去掉？

2023-03-20 16:37 UTC, pearmini requested changes
1. 所有的容器都需要在 api 下单独增加文章。

- chart
- mark
- view
- spaceLayer
- 。。。

都需要在 api 下有一篇单独的文章。

2. 每一篇文章的 api 和 overview 中的保持一致。比如 chart.[mark] 需要去掉，替换成具体的 mark

2023-03-20 16:37 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [chart.**legend**](/spec/legend/overview) - 设置或获取该复合视图的 legend。
这种设置属性的 api 可以单独一类

2023-03-20 16:37 UTC, pearmini commented on site/docs/api/overview.zh.md
> +- [geoView.**getGroup**](/api/chart#chartgetgroup) - 获得复合视图的 canvas group 实例。
对于复合节点，获取实例的方法都不用透出。

2023-03-20 16:37 UTC, pearmini commented on site/docs/api/chart.zh.md
>  更改图形的数据来源并重新渲染整个图表。
node 相关的可以去掉，分散到不同的容器文档中。

2023-03-20 16:44 UTC, pearmini requested changes

2023-03-21 03:38 UTC, pearmini approved these changes

2023-03-21 03:40 UTC, merged