feat: 进度条 mark 开发
antvis/G2 pull request #4863
Opened 2023-04-04 02:53 UTC by wuhaiyang

* **G2 Version**:  5.0
* **Platform**: any
* **Mini Showcase(like screenshots)**:   https://github.com/antvis/G2/discussions/4862
* **CodePen Link**:

2023-04-04 02:59 UTC, wuhaiyang commented on __tests__/plots/static/progress-bar-custom.ts
> +    // TODO: 未生效
漏网之鱼，这里我还要看看为啥没生效

2023-04-04 03:50 UTC, pearmini requested changes
大部分都没有问题，只有一些小问题，对了，commit 可以尽量用英文 🤣

2023-04-04 03:50 UTC, pearmini commented on src/mark/progress.ts
> +    const { graphType = 'arc', data = {}, ...resOptions } = options;
这配置可以放在 `progress.style` 里面？这样和其他复合 Mark 会统一点，比如 boxplot 通过 `style.point` 去决定是否绘制异常点。

```js
const options = {
  type: 'progress',
  style: {
    arc: true // 默认为 true
  }
}
```

2023-04-04 03:50 UTC, pearmini commented on __tests__/plots/static/progress-bar-custom.ts
> +    // TODO: 未生效
这里应该是 label 应该是一个数组，但是下面 `typeof value === 'object'` 那里统一处理有问题。

2023-04-04 03:50 UTC, pearmini commented on src/mark/progress.ts
> +    const textOption: ProgressOptions = {};
这里觉得 inner 和 outer 不是很形象，其实就是一个是前景，一个是背景，感觉 fore 和 back 会更合适一点？

```js
const options = {
  type: 'progress',
  style: {
    foreStrokeWidth: 10,
    backStrokeWidth: 20,
  }
}
```

2023-04-04 03:50 UTC, pearmini commented on __tests__/plots/static/progress-ring-custom.ts
> +    // }
这里去掉。

2023-04-04 03:50 UTC, pearmini commented on __tests__/plots/static/progress-ring-custom.ts
> +    },
scale 不会根据前缀去区分，因为对应复合 Mark 来说，一般都共用一个颜色比例尺。上面的效果应该如下声明：

```js
const options = {
  type: 'progress',
  style: {
    backFill: 'rgba(250, 57, 57, 1)',
  },
}
```

2023-04-04 03:50 UTC, pearmini commented on __tests__/plots/static/progress-bar-custom.ts
> +    },
scale 不会根据前缀区分，所以应该如下声明：

```js
const options = {
  scale: {
    color: { domain: [100, 250, 300], range: ['#F4664A', '#FAAD14', 'green'] }
  }
}
```

2023-04-04 03:50 UTC, pearmini commented on src/mark/progress.ts
> +    });
这里不建议这样统一处理：

- 不是所有 key 都需要根据前缀区分，比如 scale

```js
const options = {
  type: 'progress',
  scale: { color: {} }, // 不会加前缀
}
```
- 有的类型不是 object，比如 label，是一个数组，这样处理就会失效
- tooltip 都处理会有点不同，可以参考其他复合 Mark

比较推荐还是一个 key 一个 key 单独处理。

2023-04-04 03:50 UTC, pearmini commented on src/mark/utils.ts
> +}
这个方法如果只有 progress 用到了感觉可以直接放在 src/mark/progress 里面？

2023-04-04 04:07 UTC, wuhaiyang commented on src/mark/progress.ts
> +    });
嗯，我抛一下我当时的不成熟想法哈：scale、style 我认为是「同等公民」，都能加前缀，  未添加前缀的 对 fore 、back 、text 的mark 都生效，更方便？

![image](https://user-images.githubusercontent.com/8447716/229684680-0d8d27c8-5a93-441c-bd65-38f90d221e67.png)
这里 label 不是Object 吗？


这块可以按照之前约定规范来搞哈。

2023-04-04 04:08 UTC, wuhaiyang commented on src/mark/utils.ts
> +}
> 这个方法如果只有 progress 用到了感觉可以直接放在 src/mark/progress 里面？

仪表盘那边也有了这个。仪表盘、进度条 这类的应该都属于进度图，所以这么命名了

2023-04-04 04:09 UTC, wuhaiyang commented on src/mark/progress.ts
> +    const textOption: ProgressOptions = {};
> 这里觉得 inner 和 outer 不是很形象，其实就是一个是前景，一个是背景，感觉 fore 和 back 会更合适一点？
> 
> ```js
> const options = {
>   type: 'progress',
>   style: {
>     foreStrokeWidth: 10,
>     backStrokeWidth: 20,
>   }
> }
> ```

嗯，确实优雅点

2023-04-04 04:09 UTC, wuhaiyang commented on src/mark/progress.ts
> +    const { graphType = 'arc', data = {}, ...resOptions } = options;
> 这配置可以放在 `progress.style` 里面？这样和其他复合 Mark 会统一点，比如 boxplot 通过 `style.point` 去决定是否绘制异常点。
> 
> ```js
> const options = {
>   type: 'progress',
>   style: {
>     arc: true // 默认为 true
>   }
> }
> ```

可以的

2023-04-04 04:09 UTC, wuhaiyang commented
>

2023-04-04 04:10 UTC, wuhaiyang commented
> 大部分都没有问题，只有一些小问题，对了，commit 可以尽量用英文 🤣

好的。

2023-04-04 10:43 UTC, wuhaiyang commented on __tests__/plots/static/progress-ring-custom.ts
> +    },
> scale 不会根据前缀去区分，因为对应复合 Mark 来说，一般都共用一个颜色比例尺。上面的效果应该如下声明：
> 
> ```js
> const options = {
>   type: 'progress',
>   style: {
>     backFill: 'rgba(250, 57, 57, 1)',
>   },
> }
> ```

fore back 两个interval   共用同一个 scale ，如果我只想要设置 fore 的scale 咋搞呢？比如下面这种？

<img width="400" alt="image" src="https://user-images.githubusercontent.com/8447716/229673812-a91a7cec-8259-4947-9a3c-e738dad07d4c.png">

2023-04-04 10:52 UTC, pearmini commented on src/mark/utils.ts
> +}
ok

2023-04-04 10:54 UTC, pearmini commented on src/mark/progress.ts
> +    });
这里的 mark.label 其实是向 labels 数组里面添加一个 label，可以看下面两个例子：`__tests__/plots/static/market-interval-marimekko.ts`

2023-04-04 10:58 UTC, pearmini commented on __tests__/plots/static/progress-ring-custom.ts
> +    },
完整的声明形应该是：

```js
const options = {
  type: 'progress',
  scale: {
    color: { domain: [100, 250, 300], range: ['#F4664A', '#FAAD14', 'green'] },
  },
  style: {
    backFill: '#aaa',
  },
};
```

然后 back 的那个 interval 的 color scale 可以设置 independent，这样两个的比例尺就完全独立了。

```js
function ProgressBar() {
  return () => {
    return [
      {
        type: 'interval',
        scale: {
          color: {
            independent: true, // 完全独立
          },
        },
      },
      { type: 'interval' },
    ];
  };
}
```

2023-04-07 02:59 UTC, pepper-nice commented on src/mark/progress.ts
> +            fill: '#D0D0D0',
这些属性怎么不写在外面，用 DEFAULT_OPTIONS来定义

2023-04-11 11:50 UTC, hustcc commented
默认的样式，使用业务的主题美化一下~~~

2023-05-16 02:28 UTC, closed without merging