fix(interval): fix interval render funnel (#4868)
antvis/G2 pull request #4875
Opened 2023-04-07 03:31 UTC by shield2018

修复interval绘制funnel、pyramid

2023-04-07 09:54 UTC, hustcc commented
非常感谢贡献，PR 描述中写一下当前的问题和你的解法方案吧，有助于 CR 以及大家了解这个 PR。@shield2018

2023-04-07 09:56 UTC, pearmini commented
> 非常感谢贡献，PR 描述中写一下当前的问题和你的解法方案吧，有助于 CR 以及大家了解这个 PR。@shield2018

这里有个相关的 https://github.com/antvis/G2/issues/4868

2023-04-07 10:06 UTC, hustcc requested changes

2023-04-07 10:06 UTC, hustcc commented on src/shape/interval/color.ts
> +    }
我的建议是：这段逻辑直接写到 funnel 和 pyramid 文件中，funnel 和 pyramid 没有必要在调用 Color.ts 这个文件了，本身复用率并不高。

这两个 shape 暂时也不用考虑非直角坐标系的情况。

2023-04-07 10:06 UTC, hustcc commented on src/shape/interval/color.ts
> +    }
另外，可以再加一个 pyramid 的单侧文件。

2023-04-10 07:38 UTC, shield2018 commented
麻烦关注一下
https://github.com/antvis/G2/issues/4877

这个bug会导致漏斗图点击图例后，4个点的计算出现问题

2023-04-10 07:44 UTC, hustcc commented on src/shape/interval/funnel.ts
>    defaultMarker: 'funnel',
> defaultMarker: 'square'

另外 `Pyramid ` shape 应该有和 `funnel` 类似的问题。

2023-04-11 02:31 UTC, pearmini requested changes
这里应该需要更新一下截图，代码里面的 maker 是 square：

![image](https://user-images.githubusercontent.com/49330279/231040237-d16a3370-a208-48ba-a775-ee880a61a011.png)

2023-04-11 06:21 UTC, pearmini approved these changes

2023-04-11 06:54 UTC, hustcc approved these changes

2023-04-11 11:23 UTC, merged