fix(OOM): clear interaction and cancel animation when rerendering
antvis/G2 pull request #4899
Opened 2023-04-21 03:14 UTC by pearmini

# 内存泄漏

解决 https://github.com/antvis/G2/issues/4896 提到的问题的 90% 。

## 出现原因

- chart.render 之前没有取消之前的 animation。
- 多次调用 chart.render 的时候没有正确销毁之前的交互，导致 markState 这个变量一直没有销毁。

## 修复办法

- 在 render 之前把上一次的 animation 对象全部取消。
- 正确的保存和销毁交互

## 效果

可以发现内存增长的很慢了，这个部分需要 @xiaoiver 进一步在 g 里面看看：调用 animation.cancel 时候完全清除了动画。

![image](https://user-images.githubusercontent.com/49330279/233531850-f7c2d4c2-acb6-4a2c-8358-3df1a8209948.png)

2023-04-21 03:25 UTC, xiaoiver commented on src/runtime/plot.ts
> +  context.animations?.forEach((animation) => animation?.cancel());
这里我需要写一个创建大量动画并调用 `cancel` 销毁的例子，验证下还是否存在少量 OOM 现象。

2023-04-21 03:25 UTC, xiaoiver requested changes

2023-04-21 03:25 UTC, xiaoiver commented on site/examples/general/line/demo/line-basic.ts
> +setInterval(() => chart.render(), 1000);
这里可以去掉调试代码

2023-04-21 03:44 UTC, pearmini commented on src/runtime/plot.ts
> +  context.animations?.forEach((animation) => animation?.cancel());
嗯嗯，交给你了！

2023-04-21 03:45 UTC, hustcc approved these changes

2023-04-21 05:16 UTC, merged

2023-04-23 07:10 UTC, hustcc commented
> 可以发现内存增长的很慢了，这个部分需要 @xiaoiver 进一步在 g 里面看看：调用 animation.cancel 时候完全清除了动画。

@xiaoiver  这个彻底解决了吗？

2023-04-23 08:02 UTC, xiaoiver commented
> @xiaoiver 这个彻底解决了吗？

之前怀疑是 animation 对象调用 cancel 后没销毁，但我写了一个例子，每隔 1 秒销毁之前的动画并创建 1000 个新动画，观察内存是否呈线性增长趋势：
https://codepen.io/xiaoiver/pen/KKGMMqB

但观察下来 Animation 对象始终维持在 1000 个，并不会无限增长。

2023-04-23 08:09 UTC, hustcc commented
> > @xiaoiver 这个彻底解决了吗？
> 
> 之前怀疑是 animation 对象调用 cancel 后没销毁，但我写了一个例子，每隔 1 秒销毁之前的动画并创建 1000 个新动画，观察内存是否呈线性增长趋势： https://codepen.io/xiaoiver/pen/KKGMMqB
> 
> 但观察下来 Animation 对象始终维持在 1000 个，并不会无限增长。

那内存泄漏就不是 animation 带来的，继续排查下，这个案例，现在增长是变慢了，但是我 setInterval 改成 100 的时候，依然很快就爆炸了。

2023-04-24 07:22 UTC, pearmini commented
setInterval 为 100 的可能是新的问题：上一次渲染还没有完成（动画 300ms）就开始了下一次。

2023-04-24 08:04 UTC, hustcc commented
> 染还没有完成（动画 300ms）就开始了下一

那也是需要清除之前的动画。