fix: labelFilter 参数与 labelFormatter 保持一致
antvis/G2 pull request #4911
Opened 2023-04-24 11:16 UTC by Aarebecca

主要是对用户传入的 labelFormatter 和 labelFilter 做了层包装

<img width="284" alt="image" src="https://user-images.githubusercontent.com/25787943/233980680-2f2e5cde-a4d5-4128-9ed7-24628e7a3c7b.png">

2023-04-24 11:22 UTC, pearmini requested changes
- 加一个单测测一下 tickFilter？
- commit 英文

2023-04-25 01:41 UTC, hustcc commented
文档需要更新吗？

2023-04-25 02:35 UTC, pearmini approved these changes

2023-04-25 06:20 UTC, merged

2023-04-25 07:17 UTC, pearmini commented
fix https://github.com/antvis/G2/issues/4909