refactor: adjust legend recommand strategy
antvis/G2 pull request #4938
Opened 2023-05-05 01:42 UTC by Aarebecca

* 调整图例组件推荐策略
  * 分类图例支持 size + opacity 比例尺和 size 比例尺推断
  * 连续图例支持 opacity 比例尺推断
* 图例默认关闭标题
* 图例不会默认完全填充给定空间，而是固定 size，如果需要设置连续图例的色带高度，可通过 `ribbonSize` 配置项设置

2023-05-06 05:00 UTC, pearmini approved these changes

2023-05-06 05:03 UTC, pearmini requested changes
```ts

export function bodyPointScatterPlotOpacity(): G2Spec {
  return {
    type: 'point',
    data: {
      type: 'fetch',
      value: 'data/body.json',
    },
    encode: {
      x: 'height',
      y: 'weight',
      opacity: 'weight',
    },
    legend: {
      opacity: {
        size: 100,
      },
    },
  };
}
```

<img src="https://user-images.githubusercontent.com/49330279/236601019-9d4ed918-7b96-4edd-83ba-02754cfb1982.png" width=640 />

这张图的 opacity 生效了吗？

2023-05-06 05:03 UTC, pearmini commented on __tests__/plots/static/body-point-scatter-plot-size-opacity.ts
> +    },
这里都么有 color 通道，为啥有 color scale

2023-05-06 05:07 UTC, pearmini commented
这个 issue 的问题都解决了吗：https://github.com/antvis/G2/issues/4944

2023-05-06 08:22 UTC, Aarebecca commented
> 这个 issue 的问题都解决了吗：#4944

发错了吧

2023-05-06 08:25 UTC, pearmini commented
> > 这个 issue 的问题都解决了吗：#4944
> 
> 发错了吧

改了

2023-05-06 08:38 UTC, Aarebecca commented
> 这个 issue 的问题都解决了吗：#4915

解决了，取的默认值

2023-05-09 03:19 UTC, pearmini requested changes

2023-05-09 03:19 UTC, pearmini commented on src/theme/classic.ts
> +      title: false,
还是默认先把 tilte 展示吧，我看了一下去掉的效果：特别对于连续图例来说，其实不太清楚展示的信息是什么，如果要去掉也是等设计师更新主题之后？

2023-05-09 03:20 UTC, pearmini commented
> ```ts
> export function bodyPointScatterPlotOpacity(): G2Spec {
>   return {
>     type: 'point',
>     data: {
>       type: 'fetch',
>       value: 'data/body.json',
>     },
>     encode: {
>       x: 'height',
>       y: 'weight',
>       opacity: 'weight',
>     },
>     legend: {
>       opacity: {
>         size: 100,
>       },
>     },
>   };
> }
> ```
> 
> <img alt="" width="640" src="https://user-images.githubusercontent.com/49330279/236601019-9d4ed918-7b96-4edd-83ba-02754cfb1982.png">
> 
> 这张图的 opacity 生效了吗？

这个看看？

2023-05-09 03:22 UTC, Aarebecca commented
> ```ts
> export function bodyPointScatterPlotOpacity(): G2Spec {
>   return {
>     type: 'point',
>     data: {
>       type: 'fetch',
>       value: 'data/body.json',
>     },
>     encode: {
>       x: 'height',
>       y: 'weight',
>       opacity: 'weight',
>     },
>     legend: {
>       opacity: {
>         size: 100,
>       },
>     },
>   };
> }
> ```
> 
> <img alt="" width="640" src="https://user-images.githubusercontent.com/49330279/236601019-9d4ed918-7b96-4edd-83ba-02754cfb1982.png">
> 
> 这张图的 opacity 生效了吗？

point mark 的 opacity 没有生效，需要修复一下

2023-05-10 01:51 UTC, pearmini approved these changes

2023-05-10 01:51 UTC, merged