feat: update gui and adapt to crossSize config
antvis/G2 pull request #4949
Opened 2023-05-06 08:32 UTC by Aarebecca

> wip: 待测试

接入 crossSize 配置项，使用容器 size 作为 crossSize 值

2023-05-06 16:01 UTC, Aarebecca commented
`aaplLineSliderFilterTranspose` 这个用例会卡住，无法完成

2023-05-08 01:41 UTC, pearmini requested changes

2023-05-08 01:41 UTC, pearmini commented on __tests__/plots/interaction/appl-line-slider-filter-transpose.ts
> +aaplLineSliderFilterTranspose.skip = true;
这个 skip 是案例被卡住了？卡住的原因是？和 slider 有关吗？

2023-05-08 01:42 UTC, Aarebecca commented on __tests__/plots/interaction/appl-line-slider-filter-transpose.ts
> +aaplLineSliderFilterTranspose.skip = true;
不太确定，我在预览环境打开看没啥问题，测试环境里就一直卡着，也不报错

2023-05-08 01:42 UTC, Aarebecca commented on __tests__/plots/interaction/appl-line-slider-filter-transpose.ts
> +aaplLineSliderFilterTranspose.skip = true;
slider gui这块没有变动

2023-05-09 02:32 UTC, pearmini approved these changes

2023-05-09 02:33 UTC, merged