fix: svg renderer not works in website demo
antvis/G2 pull request #5000
Opened 2023-05-10 20:13 UTC by hustcc

因为 PR #4721 将用户传入的 renderer omit 了，所以使用了默认的 canvas 渲染。@lxfu1

```ts
options(options?: G2ViewTree): Chart | G2ViewTree {
  if (arguments.length === 0) {
    return this._options || optionsOf(this);
  }
  this._options = deepMix(
    this._options || optionsOf(this),
    omit(options, SPEC_EXTERNAL_KEYS),
  );
  return this;
}
```

2023-05-11 02:40 UTC, pearmini requested changes
加一个测试？

2023-05-11 02:40 UTC, pearmini commented on src/api/chart.ts
> +export const SPEC_EXTERNAL_KEYS = ['container'];
renderer 和 container 都不应该是 options 的内容。options 包含的配置应该只是图表的声明，和渲染器没有关系，一个完整的渲染函数的签名应该如下：

```js
render(rendererOptions, specOptions);
```

所以 options 里面本身就不需要包含 renderer 和 plugins 两个东西，而是用单独的成员变量存储。应该如下实现：

```js
class Chart {
  construtor(options) {
    this._render = options.renderer;
    this._plugins = options.plugins;
  } 
  render() {
    if(!this._context.canvas) {
      this._context.canvas = Canvas(this._container, this._renderer, this._plugins);
    }
  }
  options() {
    this._options = deepMix(this._options || optionsOf(this));
  }
}
```

2023-05-11 03:30 UTC, hustcc commented on src/api/chart.ts
> +export const SPEC_EXTERNAL_KEYS = ['container'];
我问问福老师为啥要 omit。

2023-05-11 06:02 UTC, pearmini requested changes
还需要把 renderer 和 plugins 从 options 里面解构出来，不然 chart.options 里面有这个两个配置，spec tab 会出问题：包含了 renderer 和 plugins。

```js
class Chart {
  constructor(options) {
    this._renderer = options.renderer;
    this._plugins = options.plugins;
  }
}
```

2023-05-11 07:09 UTC, hustcc commented
相当于说 option 和 spec 不是一个东西，option 内容更多？

2023-05-11 07:16 UTC, pearmini commented
> 相当于说 option 和 spec 不是一个东西，option 内容更多？

options = 渲染器的配置（container，renderer，plugs）+ 图表的配置（spec）

2023-05-12 02:46 UTC, pearmini approved these changes

2023-05-12 02:48 UTC, merged