feat: add thresholds params in gauge mark
antvis/G2 pull request #5021
Opened 2023-05-15 03:20 UTC by pepper-nice

#### 示例

```js
const chart = new Chart();

chart.options({
  type: 'gauge',
  data: {
    value: {
      target: 120,
      total: 400,
      name: 'score',
      thresholds: [100, 200, 400],
    },
  },
  scale: {
    color: {
      range: ['#F4664A', '#FAAD14', 'green'],
    },
  },
});

chart.render();
```
<img width="470" alt="image" src="https://github.com/antvis/G2/assets/109653633/54994d3f-78ca-4fc8-9118-a120937dd91c">

2023-05-15 03:35 UTC, pearmini reviewed
更新一下文档和案例，还有把其中一个案例隐藏掉：目前自定义 shape 的能力还没有透出。

2023-05-15 04:45 UTC, pearmini requested changes
更新一下文档和案例，还有把其中一个案例隐藏掉：目前自定义 shape 的能力还没有透出。

2023-05-15 06:07 UTC, pearmini approved these changes

2023-05-15 06:31 UTC, merged

2023-05-16 01:30 UTC, hustcc commented
fixed https://github.com/antvis/G2/issues/4998