fix: chart clear retain theme (fixed #5018)
antvis/G2 pull request #5022
Opened 2023-05-15 03:54 UTC by pepper-nice

issue: #5018 

#### 问题描述

2023-05-15 03:55 UTC, hustcc commented
#5018 体现出来两个问题：

1. clear 的时候需要保留 theme
2. chart.theme 需要可以修改 theme 主题包

2023-05-15 03:57 UTC, pepper-nice commented
> #5018 体现出来两个问题：
> 
> 1. clear 的时候需要保留 theme
> 2. chart.theme 需要可以修改 theme 主题包

第2点我再提个 PR 修改

2023-05-15 04:27 UTC, hustcc approved these changes

2023-05-15 04:48 UTC, pearmini requested changes
`chart.clear` 为啥需要保存主题？不报错才是合理的，应该解决 chart.clear 之后无法设置 theme 的问题.

2023-05-15 04:49 UTC, pearmini commented
`chart.clear` 理论上就是 clear，不应该非渲染器之外的配置。

2023-05-15 05:17 UTC, hustcc commented
chart clear 主要是用来：

1. 一些没有提供增伤改查的配置项，比如： mark
2. 中间数据，比如从配置项延伸出来信息，比如：scale

2023-05-15 05:44 UTC, pearmini commented
> 甚至对于可以在 new Chart 创建传入的配置，不清空更好。

4.x 是把图表（width、height 和 autoFit ）和渲染器器（container）的 options 放在一起了，如果没有 4.x 包袱，更好的 API 应该如下，把**图表配置**和**渲染器配置**分离开：**这样不和特定的渲染环境绑定**。

```js
const chart = new Chart(rendererOptions);

chart.options(specOptions);

chart.render();
```

> 按照这样的话，width、height、theme 等其实都有各自的方法去修改，所以清空不清空都无所谓

如果用户只使用 options API，不使用 chart api，如何清空 width，height 和 theme 这些？从另一个角度讲，同样的 scale 也有相应的 api 修改，是否应该也保存？

> 用户使用 clear 一般都是用来删除 geometry、annotation（比如在搭建产品中），然后加入新的

那这种情况，用户其实只是想复用 container，其实已经是不同的两个图表了。

至于用户自己想保留那些配置，应该用户直接去声明，而不是框架内部决定。

```js
const retainOptions = {
  width: 640,
  height: 480;
}

const chart = new Chart();

chart.options({...retainOptions, ...spec});

chart.clear();

chart.options({...retainOptions, ...newSpec});
```

2023-05-15 05:47 UTC, hustcc commented
所以应该怎么做？

2023-05-15 06:13 UTC, pepper-nice commented
> 

按照你这种说法，用户需要再次单独申明 theme，对用户很不友好：
```js
chart.clear();
// 再次指定 theme
chart.theme('classic');
chart.interval()...;

chart.render()
```

2023-05-15 06:15 UTC, pepper-nice commented
> > `chart.clear` 为啥需要保存主题？不报错才是合理的，应该解决 chart.clear 之后无法设置 theme 的问题.
> 
> 如果这样修改，用户需要再次单独申明 theme，对用户很不友好：
> 
> ```js
> chart.clear();
> // 再次指定 theme
> chart.theme('classic');
> chart.interval()...;
> 
> chart.render()
> ```

2023-05-16 01:05 UTC, hustcc commented
重点解决 chart.theme 设置不生效的问题，至于 theme width height 等属性是否 clear 需要再看，这个 PR 先关闭掉了。

2023-05-16 01:05 UTC, closed without merging