feat: tooltip render to mount dom
antvis/G2 pull request #5025
Opened 2023-05-15 09:56 UTC by hustcc

fixed #5024

- [x] add `mount` config to tooltip interaction
- [x] refactor tooltip component
- [x] tests
- [x] documents

```ts
{
  width: 600,
  height: 400,
  type: 'view',
  data: {
    type: 'fetch',
    value: 'data/aapl.csv',
  },
  children: [
    {
      type: 'area',
      encode: {
        x: 'date',
        y: 'close',
      },
      transform: [
        {
          type: 'sample',
          thresholds: 100,
          strategy: 'lttb',
        },
      ],
      style: {
        fillOpacity: 0.5,
      },
      tooltip: {
        title: (d) => new Date(d.date).toUTCString(),
      },
      interaction: {
        tooltip: {
          mount: 'body',
          bounding: {
            x: 100,
            y: 100,
            width: 500,
            height: 300,
          },
        },
      },
    },
  ],
}
```

2023-05-15 11:14 UTC, hustcc commented
另外，tooltip 的 classname 目前是 `.tooltip` 不具备标识性，改成和 4.x 一致的 `.g2-tooltip`。

2023-05-15 11:48 UTC, pearmini requested changes
`__tests__/integration/snapshots/tooltip/aapl-line-area-basic-sample-mount/step0.html` 这个截图为啥没有内容？

2023-05-15 12:20 UTC, hustcc commented
> `__tests__/integration/snapshots/tooltip/aapl-line-area-basic-sample-mount/step0.html` 这个截图为啥没有内容？

已修复。

2023-05-15 12:21 UTC, hustcc commented
> 另外，tooltip 的 classname 目前是 `.tooltip` 不具备标识性，改成和 4.x 一致的 `.g2-tooltip`。

下一个 pr 统一改，减少 cr 难度。

2023-05-16 01:39 UTC, pearmini approved these changes

2023-05-16 01:44 UTC, merged