feat: add density mark, violin shape and kde transform
antvis/G2 pull request #5043
Opened 2023-05-16 12:00 UTC by hustcc

fixed #5036 

- [x] KDE data.transform
- [x] density mark and shape
- [x] box shape
- [x] demo
- [x] document
- [x] tests

![image](https://github.com/antvis/G2/assets/7856674/69ffd55b-8398-491e-a17f-92a6bd05be08)

### 直接使用 violin mark，需外部 KDE

```ts
const data = [
  {
    "species": "I. setosa",
    "x": "PetalWidth",
    "y": [0.2, 1, 2, 3, 4],
    "size": [0.1, 0.3, 0.2, 0.2],
  },
  // ...
];

chart
  .violin()
   .data(data)
  .encode('x', 'x')
  .encode('y', 'y')
  .encode('size', 'size')
  .encode('color', 'species')
```

### 使用 内置 KDE

```ts
chart
  .violin()
  .data({
      type: 'kde',
      value: originalData,
      transform: [{ type: 'kde', as: ['_y', '_size'] }]
   })
  .encode('x', 'x')
  .encode('y', '_y')
  .encode('size', '_size')
  .encode('color', 'species')
```

2023-05-17 05:55 UTC, hustcc commented
## 怎么使用 violin



```ts
const data = [
  {
    "species": "I. setosa",
    "x": "PetalWidth",
    "y": [0.2, 1, 2, 3, 4],
    "size": [0.1, 0.3, 0.2, 0.2],
  },
  // ...
];

chart
  .violin()
  .encode('x', 'x')
  .encode('y', 'y')
  .encode('size', 'size')
  .encode('color', 'species')
```

2023-05-17 05:58 UTC, pearmini commented
小提琴图有聚合数据和非聚合数据之分吗？

2023-05-17 06:04 UTC, hustcc commented
理论上 kde 只对小提琴可用，kde 出来的数据就直接是小提琴的视觉位置。

2023-05-17 06:54 UTC, pearmini commented
查阅了两个参考资料：

- https://g2-v4.antv.vision/zh/examples/other/other#violin
- https://zhuanlan.zhihu.com/p/376055263
- https://en.wikipedia.org/wiki/Violin_plot
- https://zhuanlan.zhihu.com/p/106194051

可以简单理解小提琴图 = 箱线图 + 核密度图。

![image](https://github.com/antvis/G2/assets/49330279/2ef7a17c-4b32-4e9c-b5ce-50ebb388bcdf)

针对可视化聚合前后的数据应该有不同的方式。

## 聚合后


用 density + box 绘制。

```js
const data = fetchJSON('https://assets.antv.antgroup.com/g2/penguins.json');

const boxData  = quartiles(data); // 聚合数据
const densityData = kde(data); // 聚合数据

chart.options({
  type: 'view',
  children: [
    { type: 'density', data: densityData, encode: { x, y, color: 'sex' } },
    {
      type: 'box',
      data: boxData,
      encode: {
        x,
        y,
        color: 'sex',
        shape: 'violin', // 需要给 box 新增一个 violin 的 shape
      },
    },
  ],
});

```

在 ggplot 里面也有 density mark。

![image](https://github.com/antvis/G2/assets/49330279/0494287f-861e-4ca6-9fb6-e54721758d86)

## 聚合前

用 violinplot 绘制，这个是一个复合 Mark，由 box 和 density 构成，并且分别对数据进行预处理。

```js
chart.options({
  type: 'violinplot',
  encode: {
    x: 'species',
    y: 'flipper_length_mm',
    color: 'sex',
    series: 'sex',
  },
});
```

在 matlibplot 里面就有 violinplot plot。

![image](https://github.com/antvis/G2/assets/49330279/360230c7-9253-4558-8f03-035ff100fe22)

## 综上

建议增加两个 mark：

- density：需要考虑分组的情况，也就是由 series encode。
- violinplot：里面计算  density 的可以是 data.tranform 也可以是 transform。如果是前者，可以注册使用也可以内联使用；如果是后者参考 boxplot 的 groupX 的 reducer，建议内联使用。

以及给 box 增加一个新的 shape：violin，如下：

<img src="https://github.com/antvis/G2/assets/49330279/bf223b12-2759-4521-955f-b2decad1259a" width=100 />

2023-05-17 12:24 UTC, pearmini requested changes

2023-05-17 12:24 UTC, pearmini commented on __tests__/plots/static/species-violin-basic-polar.ts
> +        transform: [{ type: 'dodgeX' }],
有了 series 字段，这个应该可以去掉

2023-05-17 12:24 UTC, pearmini commented on __tests__/plots/static/species-density-basic.ts
> +    transform: [{ type: 'dodgeX' }],
这里可以去掉

2023-05-17 12:24 UTC, pearmini commented on __tests__/plots/static/species-violin-basic.ts
> +        transform: [{ type: 'dodgeX' }],
这里应该可以去掉。

2023-05-17 12:24 UTC, pearmini commented on __tests__/plots/static/species-violin-basic.ts
> +        transform: [{ type: 'dodgeX' }],
这里也可以去掉

2023-05-18 03:01 UTC, pearmini approved these changes

2023-05-18 03:02 UTC, hustcc commented on site/docs/spec/data/kde.zh.md
> +| width    | 确定一个元素左右影响多少点，类似于 bandWidth。           |  `number`                    | `2`            |
typo，我改一下。

2023-05-18 04:00 UTC, merged