feat: add heatmap mark and shape
antvis/G2 pull request #5047
Opened 2023-05-18 02:19 UTC by hustcc

fixed #5037

- [ ] heatmap mark and shape
- [ ] tests
- [ ] demo
- [ ] document

![image](https://github.com/antvis/G2/assets/7856674/953883c2-cc60-4d46-9a80-8d5cd2d14610)

参考：

- [heatmap.js](https://www.patrick-wied.at/static/heatmapjs/docs.html)

### 使用

```ts
chart
  .heatmap()
  .encode('x', 'x')
  .encode('y', 'y')
  .encode('size', 'value')
  .style('gradient', '');
```

2023-05-18 06:54 UTC, pearmini commented
可以参考 plot 的 raster mark：https://observablehq.com/plot/marks/raster，并且在测试里面添加里面的几个例子（4.0 的例子不太美观）？

2023-05-18 07:00 UTC, pearmini commented
建议改名成 **raster**，plot（如上）和 ggplot: https://ggplot2.tidyverse.org/reference/geom_tile.html#ref-examples  都是叫 raster。

![image](https://github.com/antvis/G2/assets/49330279/bd65de7a-4d15-437c-9b32-f59712c0dff7)

2023-05-18 07:00 UTC, hustcc commented
> 可以参考 plot 的 raster mark：https://observablehq.com/plot/marks/raster ，并且在测试里面添加里面的几个例子（4.0 的例子不太美观）？

可以的，正好找不到素材。

2023-05-19 07:47 UTC, xiaoiver commented
在 G2Context 中增加了 `createCanvas`，这样在服务端渲染时类似 heatmap 可以用它创建类 `<canvas>` 元素绘制。

https://github.com/antvis/G/issues/1344

2023-05-24 09:55 UTC, hustcc commented on package.json
> +    "flru": "^1.0.2",
很简单的 O(1) lru 实现。

2023-05-24 09:56 UTC, hustcc commented on src/mark/text.ts
> -    if (cartesian) return visualMark(index, scale, value, coordinate);
return 前面已经做了这个逻辑，所以删除这个无效逻辑。

2023-05-24 09:56 UTC, hustcc commented on src/runtime/render.ts
> +  },
reject 不传的时候，相当于吃掉报错了。所以默认加一个 throw 方法。

2023-05-24 09:57 UTC, hustcc commented on src/shape/image/image.ts
> +    height = typeof height === 'string' ? p(height) * h : height;
图片的宽度、高度支持百分比，用于设置到背景。

2023-05-25 02:58 UTC, pearmini requested changes

2023-05-25 02:58 UTC, pearmini commented on src/api/mark/index.ts
> +  heatmap: Heatmap,
需要在 `__tests__/unit/api/chart.spec.ts#L136` 和 `__tests__/unit/api/composition.spec.ts` 加对应的单测，之前的 density 等也需要加上。

2023-05-25 06:19 UTC, hustcc commented on __tests__/plots/static/diamond-heatmap-density.ts
> +          },
这里还在纠结，有啥建议吗？G 里是[这么写的](https://g.antv.antgroup.com/api/css/gradient#linear-gradient)，但是这里其实不需要指定 gradient 的类型 linear 还是 arc。

2023-05-25 10:37 UTC, pearmini commented on __tests__/plots/static/diamond-heatmap-density.ts
> +          },
也许数组会好一点？毕竟这里的 stop color 是有序。

```js
{ gradient: [[0, 'white'], [0.2, 'blue']]}
```

2023-05-25 10:38 UTC, pearmini approved these changes

2023-05-25 10:39 UTC, pearmini commented on __tests__/plots/static/diamond-heatmap-density.ts
> +          },
字符串也行：

```js
{ gradient: '0 white 0.2 blue'}
```

2023-05-25 11:02 UTC, hustcc commented on __tests__/plots/static/diamond-heatmap-density.ts
> +          },
那就参考 G 的写法，去掉gradient 的类型。

```ts
{ gradient: '0:white 0.2:blue'}
```

![image](https://github.com/antvis/G2/assets/7856674/9a2cef2a-6fff-47d9-afbf-0d3381e9b666)

2023-05-25 12:06 UTC, merged