fix: label formatter callback params
antvis/G2 pull request #5062
Opened 2023-05-19 07:02 UTC by pepper-nice

#### 描述
label formatter 函数传入更多参数供业务层识别。

2023-05-19 07:54 UTC, pearmini requested changes
加测试和文档。

2023-05-22 09:25 UTC, hustcc commented on src/runtime/plot.ts
> +    const value = { ...style, text: f(text, datum, index, abstractData) };
这个 callback 不是很符合数组 callback 函数结构，其他地方也有类似的 callback 吗？

```ts
// 数组的 callback 参数是这个
[].map((v, idx, arr) => '');
```

2023-05-22 09:46 UTC, hustcc commented
axis、legend、slider、scrollbar、tooltip 等组件都改成同样的签名吧。

```ts
formatter: (text, datum, idx, data) => string;

2023-05-23 02:35 UTC, pearmini approved these changes

2023-05-23 03:10 UTC, merged