chore: show treeshaking effects via bundle analyzer
antvis/G2 pull request #5097
Opened 2023-05-25 09:27 UTC by xiaoiver

为了验证使用 G2 的项目是否能够享受 treeshaking 特性。在 `__tests__/treeshaking` 下创建了一个测试项目（依赖构建后的 esm），使用 rollup-plugin-visualizer 验证效果：

```bash
$ npm run build
$ npm run test:treeshaking
```

执行后会在根目录下生成一个 `analyser.html` 文件：

<img width="1837" alt="截屏2023-05-25 下午5 47 36" src="https://github.com/antvis/G2/assets/3608471/c141d9a5-c2f2-43d1-83b7-84049644e658">

2023-05-25 09:28 UTC, pearmini approved these changes

2023-05-25 11:47 UTC, hustcc requested changes

2023-05-25 11:47 UTC, hustcc commented on __tests__/treeshaking/index.html
> +    <div id="app"></div>
container

2023-05-25 11:47 UTC, hustcc commented on __tests__/treeshaking/main.ts
> +const chart = new Chart({ theme: 'classic', container: $container });
这里直接用 `container` string 就可以了。

2023-05-26 05:57 UTC, hustcc approved these changes

2023-05-26 10:17 UTC, merged