feat: tooltip interaction support showContent params
antvis/G2 pull request #5157
Opened 2023-06-05 10:28 UTC by pepper-nice

#### 描述
`chart.on('tooltip:show', () => {})` 依赖 tooltip 显示才能调用。
业务层期望使用 tooltip:show 但不使用 G2 tooltip 组件，使用业务层的 tooltip 组件。
 
```js
chart
  .interval()
  .data([
    { genre: 'Sports', sold: 275 },
    { genre: 'Strategy', sold: 115 },
    { genre: 'Action', sold: 120 },
    { genre: 'Shooter', sold: 350 },
    { genre: 'Other', sold: 150 },
  ])
  .encode('x', 'genre')
  .encode('y', 'sold')
  .encode('color', 'genre')
  .interaction('tooltip', {
    showContent: false,
  });

  chart.on('tooltip:show', ({ data }) => {
    p.innerText = JSON.stringify(data);
  });

  chart.on('tooltip:hide', () => {
    console.log('hide');
  };);

chart.render();
```

<img width="702" alt="image" src="https://github.com/antvis/G2/assets/109653633/b7d56554-8e75-4240-b6dc-992e3cf2a6e5">

2023-06-05 10:37 UTC, hustcc commented on src/interaction/tooltip.ts
> +      if (body && showContent) {
新版中，叫 body，应该和 showContent 是一个含义。

2023-06-05 14:40 UTC, pearmini requested changes

2023-06-05 14:40 UTC, pearmini commented on src/interaction/tooltip.ts
> +      if (body && showContent) {
是的，body 和 showContent 是一个含义

2023-06-05 14:40 UTC, pearmini commented on src/interaction/tooltip.ts
> +      if (showContent) {
这里改成 body

2023-06-05 14:40 UTC, pearmini commented on __tests__/plots/api/chart-emit-item-tooltip-hide-content.ts
> +  const button = document.createElement('button');
这个文件需要加断言，目前只是一个测试，参考  `__tests__/integration/api-chart-emit-item-tooltip.spec.ts`

2023-06-05 14:42 UTC, pearmini commented
我比较好奇，为啥需要这个能力，render 函数不行吗？还是希望 render 能返回当前的数据？

2023-06-06 02:23 UTC, pepper-nice commented
> 我比较好奇，为啥需要这个能力，render 函数不行吗？还是希望 render 能返回当前的数据？

渲染没有走 render 函数，用了 `plot.on('tooltip:show', render)` 的方式。
因为 render 不够灵活，无法控制锁定/解锁状态，无法在其他交互时渲染调用该 render 函数传入特殊参数。

2023-06-07 07:29 UTC, hustcc approved these changes

2023-06-07 07:39 UTC, pearmini approved these changes

2023-06-08 01:34 UTC, pearmini commented
> 无法控制锁定/解锁状态

这个是 G2 的 tooltip 应该是需要提供相应的 API 的。

> 无法在其他交互时渲染调用该 render 函数传入特殊参数。

只要 render 函数的参数提供了对应的数据点，就可以获得特殊的参数？

2023-06-27 02:35 UTC, merged