fix(layout): auto inset ignore null bbox
antvis/G2 pull request #5228
Opened 2023-06-25 07:37 UTC by pearmini

- fix: https://github.com/antvis/G2/issues/5220
- 原因：auto inset 没有跳过 null 的 bbox

<img src="https://github.com/antvis/G2/assets/49330279/a94aa358-1d2d-4826-aad8-c624b07d74df" width=640 />

```ts
export function mockIntervalFacetRectPolar(): G2Spec {
  return {
    type: 'facetRect',
    height: 320,
    data: [
      { type: 'A', value: 1, n: 64 },
      { type: 'A', value: 2, n: 37 },
      { type: 'A', value: 3, n: 29 },
      { type: 'B', value: 1, n: 58 },
      { type: 'B', value: 2, n: 38 },
      { type: 'B', value: 3, n: 25 },
    ],
    encode: { x: 'type' },
    children: [
      {
        type: 'interval',
        frame: false,
        coordinate: { type: 'polar' },
        encode: {
          x: 'value',
          y: 'n',
          color: 'value',
        },
        axis: { y: { label: false, title: false }, x: { title: false } },
      },
    ],
  };
}
```

2023-06-25 07:43 UTC, hustcc requested changes

2023-06-25 07:43 UTC, hustcc commented on src/composition/facetRect.ts
> +  if (guide === null || guide === false) return () => null;
为啥不是直接判断 !guide？

2023-06-25 07:48 UTC, pearmini commented on src/composition/facetRect.ts
> +  if (guide === null || guide === false) return () => null;
需要 guide 是 undefined 的时候走默认逻辑。

2023-06-25 11:14 UTC, hustcc approved these changes

2023-06-25 11:14 UTC, hustcc commented on src/composition/facetRect.ts
> +  if (guide === null || guide === false) return () => null;
默认逻辑在这个前面是不是就处理掉了？

2023-06-26 01:39 UTC, pearmini commented on src/composition/facetRect.ts
> +  if (guide === null || guide === false) return () => null;
这里倒没处理。

2023-06-26 01:39 UTC, merged