fix(slider): index scale by scaleKey
antvis/G2 pull request #5291
Opened 2023-07-11 03:11 UTC by pearmini

# Slider

加入 text annotation 的时候，slider 失效。

```js
chart.options({
  type: 'view',
  children: [
    { type: 'point' },
    { type: 'text', style: { text: 'hello', x: '50%', y: '50%' } },
  ],
});
```

## 问题原因

之前是通过 channel name 去索引 scale 的。这存在一个问题：当一个 channel 有多个 scale 的时候，后面的 scale 会覆盖前面的 scale。

```js
// After
chart.getScale(); // { x: Identity, y: Identity }
```

point x 和 y 通道的 Linear scale 被 text 的 Identity scale 覆盖了。

## 解决办法

通过 scaleKey 去索引 scale。如果没有显示的指定 scaleKey，将 `${channelName}${maxIndex}` 作为该 scale 的 key。

```js
// Before
chart.getScale(); // { x: Identity, y: Identity, x1: Identity, y1: Identity }
```

这样存储 scale 之后应该可以解决 https://github.com/antvis/G2/issues/5242 提到的问题。

## 效果

![slider-annotation](https://github.com/antvis/G2/assets/49330279/0cb9b697-f0d4-4ebd-ab40-ba9bb7680e0f)

```ts
export function countriesAnnotationSliderFilter(): G2Spec {
  return {
    type: 'view',
    theme: 'classic',
    padding: 'auto',
    data: {
      type: 'fetch',
      value: 'data/countries.json',
    },
    children: [
      { type: 'lineX', data: [0] },
      { type: 'lineY', data: [0] },
      {
        type: 'range',
        data: [
          { x: [-25, 0], y: [-30, 0], region: '1' },
          { x: [-25, 0], y: [0, 20], region: '2' },
          { x: [0, 5], y: [-30, 0], region: '2' },
          { x: [0, 5], y: [0, 20], region: '1' },
        ],
        encode: { x: 'x', y: 'y' },
        style: {
          fillOpacity: 0.2,
          fill: (d) => (d.region === '1' ? '#d8d0c0' : '#a3dda1'),
        },
      },
      {
        type: 'point',
        encode: {
          x: 'change in female rate',
          y: 'change in male rate',
          size: 'pop',
          color: 'continent',
          shape: 'point',
        },
        scale: {
          color: {
            range: ['#ffd500', '#82cab2', '#193442', '#d18768', '#7e827a'],
          },
          x: { nice: true },
          y: { nice: true },
          size: { range: [4, 30] },
        },
        legend: { size: false },
        style: { stroke: '#bbb', fillOpacity: 0.8 },
        axis: { x: { title: 'Female' }, y: { title: 'Male' } },
        slider: {
          x: { labelFormatter: (d) => d.toFixed(1) },
          y: { labelFormatter: (d) => d.toFixed(1) },
        },
        tooltip: {
          items: [
            { channel: 'x', valueFormatter: '.1f' },
            { channel: 'y', valueFormatter: '.1f' },
          ],
        },
      },
      {
        type: 'text',
        style: {
          text: 'Population',
          x: '100%',
          y: '100%',
          dx: -10,
          dy: -10,
          textAlign: 'end',
          fontSize: 50,
          textBaseline: 'bottom',
        },
      },
    ],
  };
}
```

2023-07-11 06:00 UTC, hustcc requested changes

2023-07-11 06:00 UTC, hustcc commented on src/runtime/scale.ts
> +    if (typeof key === 'string') {
逻辑是如果存在就不覆盖？

2023-07-11 06:59 UTC, pearmini commented on src/runtime/scale.ts
> +          .map((d) => +(/[^\d]+(\d*)$/.exec(d)?.[1] || 0));
提取 `x1` 中的 `1`

2023-07-11 07:00 UTC, pearmini commented on src/runtime/scale.ts
> +    if (typeof key === 'string') {
嗯嗯，或者说不存在就设置会好一点。

2023-07-11 07:00 UTC, pearmini commented on src/runtime/scale.ts
> +          .map((d) => +(/[^\d]+(\d*)$/.exec(d)?.[1] || 0));
我添加一个注释吧。

2023-07-12 05:23 UTC, hustcc commented on src/runtime/scale.ts
> +          .map((d) => +(/[^\d]+(\d*)$/.exec(d)?.[1] || 0));
> Number(s.replace(/[^0-9]/g, '')) || 0;

这样是不是语义化更好一些。

2023-07-12 06:05 UTC, pearmini commented on src/runtime/scale.ts
> +          .map((d) => +(/[^\d]+(\d*)$/.exec(d)?.[1] || 0));
那不如 `d => d.replace('name', '')`，毕竟前面已经有 `d.startsWith(name)` 的判断了？

2023-07-12 07:10 UTC, hustcc approved these changes

2023-07-12 07:14 UTC, merged