feat: sphere shape used in 3d lib #5375
antvis/G2 pull request #5412
Opened 2023-08-16 05:33 UTC by xiaoiver

##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

2023-08-17 02:21 UTC, pearmini requested changes

2023-08-17 02:21 UTC, pearmini commented on src/mark/point3D.ts
> +          ] as Vector3[];
当有 size 通道的时候，shape 得到的控制点应该是 3个？

2023-08-17 02:21 UTC, pearmini commented on src/mark/point3D.ts
> +    { name: 'z' },
z 通道 required 设置成必须？

2023-08-17 02:21 UTC, pearmini commented on src/mark/point3D.ts
> +    { type: MaybeZeroY },
后续可能需要加一个 `{ type: MaybeZeroZ }`

2023-08-17 12:46 UTC, hustcc commented on site/docs/api/chart.zh.md
> +添加 point3D 图形，具体见 [mark](/spec/mark/point3D)。
这里地址是大写，估计打开是 404 吧？

2023-08-17 12:47 UTC, hustcc commented on site/docs/manual/extra-topics/3d-charts.zh.md
> +$ npm install @antv/g-webgl @antv/g-plugin-3d @antv/g-plugin-control --save;
后面不要分号。

2023-08-17 12:50 UTC, hustcc commented on site/docs/manual/extra-topics/3d-charts.zh.md
> +<img alt="perspective" src="https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*KNCUQqzw2JsAAAAAAAAAAAAADmJ7AQ/original" width="400" />
文档中，已经可以用代码做可交互的 demo 了。

2023-08-17 12:51 UTC, hustcc commented on site/docs/manual/extra-topics/3d-charts.zh.md
> +title: 3D 图表
标题为：

- 绘制 3D 图表
- 如何绘制 3D 图表？

2023-08-17 12:51 UTC, hustcc commented on site/docs/spec/mark/point3D.zh.md
> +import { CameraType } from '@antv/g';
这个 demo 可以直接做成可交互的。

2023-08-17 12:55 UTC, hustcc commented on src/lib/std.ts
> +    ...threedlib(),
threedlib 不作为默认包，不然会带来 G2 大小暴涨。

2023-08-17 12:56 UTC, hustcc commented on src/lib/threed.ts
> +    'mark.point3D': Point3D,
还有 shape 也放到这个里面。

2023-08-18 02:04 UTC, xiaoiver commented on site/docs/manual/extra-topics/3d-charts.zh.md
> +我们使用 [point3D](/spec/mark/point3-d) Mark 并选择 cube 作为 shape 进行绘制。
是的，文档里单独增加了一个 3D 分类：`/spec/3d/point3-d`

2023-08-18 02:08 UTC, hustcc commented on site/docs/manual/extra-topics/3d-charts.zh.md
> +我们使用 [point3D](/spec/mark/point3-d) Mark 并选择 cube 作为 shape 进行绘制。
https://g2.antv.antgroup.com/manual/extra-topics/bundle#g2threedlib 就是文档中的这个。

另外这个文档的名字还是叫 point-3d 吧，感觉 point3-d 有点奇怪，虽然符合规则。

2023-08-18 02:52 UTC, xiaoiver commented on site/docs/manual/extra-topics/3d-charts.zh.md
> +<img alt="perspective" src="https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*KNCUQqzw2JsAAAAAAAAAAAAADmJ7AQ/original" width="400" />
已更新

2023-08-18 02:52 UTC, xiaoiver commented on src/lib/std.ts
> +    ...threedlib(),
已从 stdlib 中移除

2023-08-18 02:53 UTC, xiaoiver commented on src/lib/threed.ts
> +    'mark.point3D': Point3D,
shape 现在都在 mark 中引用

2023-08-18 04:44 UTC, xiaoiver commented on site/docs/spec/mark/point3D.zh.md
> +import { CameraType } from '@antv/g';
已加

2023-08-18 05:15 UTC, hustcc approved these changes

2023-08-18 05:38 UTC, merged