feat: 3d line plot
antvis/G2 pull request #5471
Opened 2023-08-28 03:13 UTC by xiaoiver

##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

2023-08-29 06:39 UTC, hustcc requested changes

2023-08-29 06:39 UTC, hustcc commented on __tests__/plots/api/chart-render-3d-line-plot-perspective.ts
> +import { CameraType } from '@antv/g';
好像没有提交单测的截图？

2023-08-29 06:54 UTC, xiaoiver commented on __tests__/plots/api/chart-render-3d-line-plot-perspective.ts
> +import { CameraType } from '@antv/g';
G6 那边使用的 WebGL 服务端渲染库是 headless-gl，G2 这边还没使用。后面我另写一个 PR 做。

2023-08-29 06:59 UTC, hustcc commented
![image](https://github.com/antvis/G2/assets/7856674/a7ca3a8e-8034-462f-b577-ba441fbc33ec)

当个文件的覆盖率还是需要提高一下~

2023-08-29 12:23 UTC, hustcc approved these changes

2023-08-30 02:01 UTC, pearmini approved these changes

2023-08-30 02:01 UTC, pearmini commented on __tests__/plots/api/chart-render-3d-line-plot-perspective.ts
> +
后面这种例子可以放在集成测试里面，用 playwright 去截图。

2023-08-30 02:01 UTC, merged