update rollup plugins and fix dependency conflict
antvis/G2 pull request #5489
Opened 2023-08-31 02:31 UTC by xcy960815

##### Checklist

- [x ] `npm test` passes
- [x ] benchmarks are included
- [x ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

2023-08-31 05:05 UTC, hustcc commented
解决问题是什么？

2023-08-31 05:05 UTC, hustcc commented on package.json
> +    "rollup-plugin-typescript2": "^0.35.0",
为啥有两个？

2023-08-31 05:06 UTC, hustcc commented on rollup.config.js
> +// 新配置插件---------------
这些注释都是多余的。

2023-08-31 05:06 UTC, hustcc commented on rollup.config.js
> +export default {
上面加一个空行

2023-08-31 05:07 UTC, hustcc commented on rollup.config.js
> +//     },
不需要就删除，而不是注释。

2023-08-31 05:07 UTC, hustcc commented on tsconfig.json
> +    "module": "ES2015",
不需要就删除。

2023-08-31 05:41 UTC, xcy960815 commented
> 解决问题是什么？

更新 rollup 插件，顺带解决 rollup  插件依赖冲突的问题

2023-09-01 08:35 UTC, pearmini commented
看了一下，主要的变化有：

- `rollup-plugin-uglify` -> `@rollup/plugin-terser`
- `rollup-plugin-typescript` -> `rollup-plugin-typescript2`
- context.widow
- tsConfig.module : `commonjs` -> `ESNext`

2023-09-01 08:38 UTC, xcy960815 commented
> 看了一下，主要的变化有：
> 
>     * `rollup-plugin-uglify` -> `@rollup/plugin-terser`
> 
>     * `rollup-plugin-typescript` -> `rollup-plugin-typescript2`
> 
>     * context.widow
> 
>     * tsConfig.module : `commonjs` -> `ESNext`

是的， 还有一个就是  rollup.config.js的 采用esm 导出方式

2023-09-01 08:43 UTC, xcy960815 commented
> 看了一下，主要的变化有：
> 
>     * `rollup-plugin-uglify` -> `@rollup/plugin-terser`
> 
>     * `rollup-plugin-typescript` -> `rollup-plugin-typescript2`
> 
>     * context.widow
> 
>     * tsConfig.module : `commonjs` -> `ESNext`

移除 tsconfig.json的 outDir 属性

2023-09-01 09:10 UTC, pearmini requested changes

2023-09-01 09:10 UTC, pearmini commented on tsconfig.json
> +    "module": "ESNext",
这个 module 字段也可以去掉？

2023-09-01 09:10 UTC, pearmini commented on rollup.config.js
> +import terser from '@rollup/plugin-terser';
terser 相对于的 uglify 有啥优势？

2023-09-01 09:20 UTC, xcy960815 commented on tsconfig.json
> +    "module": "ESNext",
不可以去掉，如果在 tsconfig.json 文件中没有指定 "module" 选项，则 TypeScript 将采用默认值 "commonjs"。
但是 rollup-plugin-typescript2 打包会读取 tsconfig.json的该配置，rollup-plugin-typescript2不支持"commonjs"，
使用 "ESNext" 作为 TypeScript 的 "module" 选项的一个好处是能够使用最新版本的 ECMAScript 标准，而不仅仅是固定在某个特定模块系统的语法中。
从长远的角度看 使用 "ESNext" 还可能让代码更易于迁移到未来的 ECMAScript 版本，因为它可以保持与最新语言特性的兼容性，并且允许开发者逐步地采用这些新功能

2023-09-01 09:20 UTC, xcy960815 commented on rollup.config.js
> +import terser from '@rollup/plugin-terser';
没有什么优势，二者是一个作者，但是在安装uglify依赖的时候回出现 依赖冲突，https://github.com/TrySound/rollup-plugin-uglify/issues/82，所以要升级达成 terser

2023-09-01 09:57 UTC, merged