feat: add mask.liquid
antvis/G2 pull request #5498
Opened 2023-08-31 12:13 UTC by ai-qing-hai

examples: 
![image](https://github.com/antvis/G2/assets/65594180/0c3cd30f-5a1a-4870-bdbe-b0b40c88d3af)
![chrome-capture-2023-7-31](https://github.com/antvis/G2/assets/65594180/8f535b82-3a73-486c-b613-d8d9f75d9782)

api: 
![image](https://github.com/antvis/G2/assets/65594180/db978186-2192-4680-a2f2-66b756072c05)

2023-08-31 12:18 UTC, hustcc commented on site/docs/spec/mark/liquid.zh.md
> +<img alt="wordCloud" src="https://mdn.alipayobjects.com/huamei_za7we3/afts/img/A*cHArRaizyBsAAAAAAAAAAAAADo2bAQ/original
liquid

2023-08-31 12:18 UTC, hustcc commented on site/docs/spec/mark/liquid.zh.md
> +  theme: 'classic',
rebase 一下 v5，theme 可以去掉了。

2023-08-31 12:18 UTC, hustcc commented on site/docs/spec/mark/liquid.zh.md
> +  .data({
data 可以直接写 0.3 吗？

2023-08-31 12:20 UTC, hustcc commented on site/docs/spec/mark/liquid.zh.md
> +
加一个文档和 demo，怎么自定义 水波图。参考：https://zhuanlan.zhihu.com/p/447521800

2023-08-31 12:20 UTC, hustcc commented on site/examples/general/Liquid/demo/liquid-background.ts
> +  theme: 'classic',
theme 去掉，下同。

2023-08-31 12:21 UTC, hustcc commented on site/docs/spec/mark/liquid.zh.md
> +
下面有了，这个 cr 忽略。

2023-08-31 12:23 UTC, hustcc commented on src/shape/liquid/getLiquidShape.ts
> +export const getLiquidShape = (shape = 'circle') =>
这个方法去掉，让这个文件更纯粹，直接在使用的地方去处理。

2023-08-31 12:24 UTC, hustcc commented on src/shape/liquid/liquidShape.ts
> +export const LiquidShape: SC<LiquidShapeOptions> = (options, context) => {
命名直接 Liquid 好了。

2023-08-31 12:25 UTC, hustcc commented on src/shape/liquid/addWaterWave.ts
> + * @reference http://gitlab.alipay-inc.com/datavis/g6/blob/1.2.0/src/graph/utils/path.js#L135
这类注释，引用的内部地址，别人也访问不到，去掉。

2023-08-31 12:28 UTC, hustcc commented on src/shape/liquid/getLiquidShape.ts
> +/**
shapes.ts

2023-08-31 12:29 UTC, hustcc commented on src/shape/liquid/addWaterWave.ts
> +import { PathStyleProps, IAnimation } from '@antv/g';
wave.ts 简洁

2023-09-01 01:57 UTC, pearmini requested changes
整体很不错，有两点需要注意一下：

- 添加集成测试，参考 [gauge](https://github.com/antvis/G2/pull/4739/files#diff-56118229bf718fe77fd215164e066f5bd52bc04fdeb4369d5fd2151cf8813308) 的 PR。
- 注释都用英文（国际化需要）

2023-09-01 07:29 UTC, ai-qing-hai commented on site/docs/spec/mark/liquid.zh.md
> +  .data({
gauge 也不能 data 直接数据吧。

2023-09-01 09:30 UTC, ai-qing-hai commented on src/shape/liquid/addWaterWave.ts
> +import { PathStyleProps, IAnimation } from '@antv/g';
已修改

2023-09-01 09:30 UTC, ai-qing-hai commented on src/shape/liquid/addWaterWave.ts
> + * @reference http://gitlab.alipay-inc.com/datavis/g6/blob/1.2.0/src/graph/utils/path.js#L135
已修改

2023-09-01 09:31 UTC, ai-qing-hai commented on src/shape/liquid/getLiquidShape.ts
> +export const getLiquidShape = (shape = 'circle') =>
已修改

2023-09-01 09:31 UTC, ai-qing-hai commented on site/examples/general/Liquid/demo/liquid-background.ts
> +  theme: 'classic',
已修改

2023-09-01 09:31 UTC, ai-qing-hai commented on site/docs/spec/mark/liquid.zh.md
> +  theme: 'classic',
已删除

2023-09-01 09:31 UTC, ai-qing-hai commented on site/docs/spec/mark/liquid.zh.md
> +<img alt="wordCloud" src="https://mdn.alipayobjects.com/huamei_za7we3/afts/img/A*cHArRaizyBsAAAAAAAAAAAAADo2bAQ/original
已修改

2023-09-04 06:39 UTC, ai-qing-hai commented
> 整体很不错，有两点需要注意一下：
> 
> * 添加集成测试，参考 [gauge](https://github.com/antvis/G2/pull/4739/files#diff-56118229bf718fe77fd215164e066f5bd52bc04fdeb4369d5fd2151cf8813308) 的 PR。
> * 注释都用英文（国际化需要）

2023-09-04 06:39 UTC, closed without merging

2023-09-04 06:43 UTC, ai-qing-hai commented
> 整体还不错，有两点需要注意一下：
> 
> * 添加集成测试，参考[gauge](https://github.com/antvis/G2/pull/4739/files#diff-56118229bf718fe77fd215164e066f5bd52bc04fdeb4369d5fd2151cf8813308)的PR。
> * 注释均用中文（国际化需要）

已经修改并推安家测试