feat: add auto mark
antvis/G2 pull request #5585
Opened 2023-09-22 02:45 UTC by ixuxinyue

https://github.com/antvis/G2/issues/5449#issue-1862649799
添加 auto lib，主要包含 auto mark，通过 AVA 能力提供图表spec的智能推荐。此 pr 包含 code test

AVA能支持推荐的图表类型：
pie_chart & donut_chart
line_chart & step_line_chart
area_chart & stack_area_chart & percent_stacked_area_chart
bar_chart & group_bar_chart & stack_bar_chart & percent_stacked_bar_chart
column_chart & grouped_column_chart & stacked_column_chart & percent_stacked_column_chart
scatter_plot
bubble_chart
histogram
heatmap

- [ ]  code
- [ ]  test （待补充更丰富的test cases）
- [ ]  docs
- [ ]  demos

![image](https://github.com/antvis/G2/assets/22525231/6c38c454-446a-422f-b450-82d81f9d4f29)

2023-09-22 07:08 UTC, pearmini requested changes
代码的 CI 挂了，可以运行 `tnpm run ci`，解决一下 ci 问题：

- 需要更新 __tests__/unit/lib/std.spec.ts  中的测试，添加 autoMark
- 需要新增 __tests__/unit/lib/auto.spec.ts 中，添加对 auto lib 的测试

2023-09-22 07:08 UTC, pearmini commented on src/mark/auto.ts
> +  return results?.[0].spec;
这里感觉可以这么写：

```js
export const Auto = (options) => {
  // 把 ava 相关的配置解构出来
  const { dataProps, fields, smartColor, options: o, colorOptions, ..rest} = options;
  const results = chartAdvisor.advise({
    dataProps,
    fields,
    smartColor，
    options: o,,
  });
  return deepMix({}, rest, results?.[0].spec);
};
```

这样可以让用户可以指定一些默认值，比如样式什么的：不管推荐出什么，都希望使用 dark theme：

```js
chart.options({
  type: 'auto',
  data: [],
  theme: 'dark',
})
```

2023-09-22 07:50 UTC, ixuxinyue commented on src/spec/mark.ts
> +export type AutoMark = { type: 'auto' } & AdviseParams;
写成BaseMark<'auto'>的话 那用户如果输入了encoding等属性的话，也不会提示错误，不过其实AVA用不上这些属性，不知道会不会有影响？

2023-09-25 01:58 UTC, pearmini commented on src/spec/mark.ts
> +export type AutoMark = { type: 'auto' } & AdviseParams;
如果让用户可以指定一些默认值的话，应该就说得通了，比如如下：

```js
chart.options({
  type: 'auto',
  data: [],
  theme: 'dark', // 指定默认主题
})
```

2023-09-25 03:29 UTC, pearmini commented
打包有点问题，可能需要排查一下：

![image](https://github.com/antvis/G2/assets/49330279/601fb758-2280-4011-91ac-2d973feb05fb)

2023-09-28 01:54 UTC, pearmini commented
因为能力不完整，autolib 先不同 src/index.ts 暴露出去，不过这个 PR 可以正常合并。

2023-09-28 02:07 UTC, pearmini approved these changes

2023-09-28 05:37 UTC, merged