chore: translate api docs
antvis/G2 pull request #5604
Opened 2023-09-27 04:23 UTC by xiaoiver

##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

2023-09-27 05:44 UTC, hustcc commented
赞，这个等 pearmini 把中文梳理清除再翻译和合并吧~

2023-10-16 03:48 UTC, pearmini requested changes
这些翻译的文档先删除，线后我合并一下 PR。

2023-10-16 05:54 UTC, pearmini requested changes

2023-10-16 05:54 UTC, pearmini commented on site/docs/api/chart.en.md
> -<!-- <embed src="@/docs/spec/chart.zh.md"></embed> -->
这个应该不需要删除？（下面同理）

2023-10-16 07:43 UTC, pearmini approved these changes

2023-10-16 08:51 UTC, merged