fix(liquid): add liquid percent.toFixed
antvis/G2 pull request #5648
Opened 2023-10-17 02:24 UTC by ai-qing-hai

![image](https://github.com/antvis/G2/assets/65594180/f0ea2f22-cfc3-4fa9-a77a-edc99b9bff49)

2023-10-17 03:04 UTC, lxfu1 commented on src/mark/liquid.ts
> +        text: `${(percent * 100).toFixed(2)} %`,
感觉不能简单的toFixed， 例如 0.55 这种会被转换为 55.00%

2023-10-17 03:21 UTC, pearmini requested changes

2023-10-17 03:21 UTC, pearmini commented on src/mark/liquid.ts
> +        text: `${(percent * 100).toFixed(2)} %`,
全局搜索 prettyNumber 这个函数，把它抽出来放在 `src/utils/number.ts` 里面，然后在这里使用：避免精度问题。

2023-10-17 03:23 UTC, pearmini requested changes

2023-10-17 03:23 UTC, pearmini commented on src/mark/liquid.ts
> +        text: `${(percent * 100).toFixed(2)} %`,
同时修改水波图的测试案例为这个特殊的文本，然后更新截图

2023-11-10 03:13 UTC, ai-qing-hai commented on src/mark/liquid.ts
> +        text: `${(percent * 100).toFixed(2)} %`,
好了

2023-11-10 03:31 UTC, pearmini commented
这里 rebase 一下 v5，不要用 merge

2023-11-13 01:51 UTC, closed without merging

2023-11-13 01:52 UTC, ai-qing-hai commented
> 这里 rebase 一下 v5，不要用 merge

https://github.com/antvis/G2/pull/5788 重新创建一个 pr