fix: 为interval添加最小高度配置
antvis/G2 pull request #5715
Opened 2023-11-01 12:27 UTC by iamzone

##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

Fiexs #5686 
Interval shape 增加 minHeight 最小高度的配置

2023-11-01 12:27 UTC, iamzone commented
![line](https://github.com/antvis/G2/assets/14135813/6b9ec073-2b4c-4d3a-badc-001893be5abc)

2023-11-02 07:43 UTC, Runtus commented
hi老哥，你这里的柱状图的最小值是倒着渲染的，我那里改了一版把这个修复了，不知道是否能给你的fork仓库提一个PR

2023-11-02 07:44 UTC, iamzone commented
> hi老哥，你这里的柱状图的最小值是倒着渲染的，我那里改了一版把这个修复了，不知道是否能给你的fork仓库提一个PR

可以的

2023-11-03 03:48 UTC, pearmini requested changes
参考这个 PR https://github.com/antvis/G2/pull/5123 添加：

- 测试案例
- 文档
- Demo

目前没有去测水平情况。

2023-11-03 03:51 UTC, pearmini requested changes

2023-11-03 03:51 UTC, pearmini commented on src/shape/interval/color.ts
> +    const finalY = isMinHeight ? absY + insetTop - heightDiff : absY + insetTop;
不建议修改这里的计算，处理 clamp 和其余逻辑混合在一起了，建议直接修改之后的 clamp 逻辑。

2023-11-03 03:51 UTC, pearmini commented on src/shape/interval/color.ts
>      const clampY = finalY - (clampHeight - finalHeight) / 2;
这里改成 `const clampY = finalY - (clampHeight - finalHeight)` 就可以解决 @Runtus 提到的问题，但还有水平的情况需要考虑一下。

2023-11-03 05:57 UTC, iamzone commented on src/shape/interval/color.ts
>      const clampY = finalY - (clampHeight - finalHeight) / 2;
好的，今晚我会修改，并补充测试

2023-11-03 07:32 UTC, Runtus commented on src/shape/interval/color.ts
> +    const finalY = isMinHeight ? absY + insetTop - heightDiff : absY + insetTop;
好的，我这里会做修改，同时适配水平方向的minHeight

2023-11-03 07:44 UTC, Runtus commented on src/shape/interval/color.ts
> +    const finalY = isMinHeight ? absY + insetTop - heightDiff : absY + insetTop;
@pearmini  您好，我想再找您确认一下，`minHeight`生效是**数据为0的时候生效**，还是说**数据渲染出来的直方图高度小于minHeight的时候生效**，因为这两个不同的话，对应的逻辑会稍微有些不同。

2023-11-03 08:01 UTC, pearmini commented on src/shape/interval/color.ts
> +    const finalY = isMinHeight ? absY + insetTop - heightDiff : absY + insetTop;
@Runtus 第二种情况：条通过数据计算出的高度小于 minHeight 的时候生效

2023-11-03 08:21 UTC, Runtus commented on src/shape/interval/color.ts
> +    const finalY = isMinHeight ? absY + insetTop - heightDiff : absY + insetTop;
get

2023-11-03 08:47 UTC, Runtus commented on src/shape/interval/color.ts
>      const clampY = finalY - (clampHeight - finalHeight) / 2;
@iamzone hi老哥，我这里已经把代码改好了，这里在写测试，等会儿会提一个PR，到时候麻烦您CR一下。

2023-11-06 03:30 UTC, pearmini commented
代码格式存在一些问题，运行一下：`npm run fix` 再提交。

2023-11-06 03:33 UTC, pearmini requested changes
大部分都没有问题了，还有两点需要一下：

- 运行 `npm run lint`
- 去掉 `maxHeight` 的类型定义

2023-11-06 03:33 UTC, pearmini commented on src/shape/interval/rect.ts
> +  maxHeight?: number;
maxHeight 可以去掉了，我看代码里已经没有这个配置了。

2023-11-06 07:02 UTC, Runtus commented on src/shape/interval/rect.ts
> +  maxHeight?: number;
已修改并向 @iamzone 提交了PR

2023-11-07 08:59 UTC, pearmini approved these changes
LGTM

2023-11-07 09:00 UTC, merged