feat: add default format to tooltip title #5684
antvis/G2 pull request #5748
Opened 2023-11-06 09:06 UTC by BENcorry

##### Checklist

- [ x] `npm test` passes
- [ ] benchmarks are included
- [ x] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change
1. 给tooltip title的Date格式数据添加默认格式化
2. 更新集成测试快照

2023-11-06 09:11 UTC, pearmini commented
这里的测试快照可以先不更新，现在的环境在不同机器上有差异，等我们解决了更新即可。这个 PR 只需要包含代码更新就行。

2023-11-06 09:17 UTC, BENcorry commented
> 这里的测试快照可以先不更新，现在的环境在不同机器上有差异，等我们解决了更新即可。这个 PR 只需要包含代码更新就行。

OK, 已更新

2023-11-07 02:14 UTC, pearmini commented
在 PR 描述里面更新一些 API 的使用方式（通过一些案例体现），同时解释一下实现思路？

2023-11-07 04:15 UTC, BENcorry commented
> 在 PR 描述里面更新一些 API 的使用方式（通过一些案例体现），同时解释一下实现思路？参考这个 PR 的描述：#5751

已更新～

2023-11-08 02:56 UTC, pearmini requested changes
- format 函数挺好！
- 这里不建议在 tooltip 交互里面做 format，这个在提取 title 数据的过程中比较好，相关的代码在这里 https://github.com/antvis/G2/blob/v5/src/runtime/transform.ts#L187 ，这里可能需要根据数据类型 value1 去设置默认的 formatter
- 参考 `__tests__/plots/tooltip/aapl-line.ts` 添加一个测试，CI 报错可以不管

2023-11-08 05:11 UTC, BENcorry commented
> * format 函数挺好！
> * 这里不建议在 tooltip 交互里面做 format，这个在提取 title 数据的过程中比较好，相关的代码在这里 https://github.com/antvis/G2/blob/v5/src/runtime/transform.ts#L187 ，这里可能需要根据数据类型 value1 去设置默认的 formatter
> * 参考 `__tests__/plots/tooltip/aapl-line.ts` 添加一个测试，CI 报错可以不管

2023-11-08 05:58 UTC, BENcorry commented
> > * format 函数挺好！
> > * 这里不建议在 tooltip 交互里面做 format，这个在提取 title 数据的过程中比较好，相关的代码在这里 https://github.com/antvis/G2/blob/v5/src/runtime/transform.ts#L187 ，这里可能需要根据数据类型 value1 去设置默认的 formatter
> > * 参考 `__tests__/plots/tooltip/aapl-line.ts` 添加一个测试，CI 报错可以不管

我在title的处理过程中针对于无回调处理的title做了处理，这种的title属性是一个列表

2023-11-08 07:56 UTC, BENcorry commented
> * format 函数挺好！
> * 这里不建议在 tooltip 交互里面做 format，这个在提取 title 数据的过程中比较好，相关的代码在这里 https://github.com/antvis/G2/blob/v5/src/runtime/transform.ts#L187 ，这里可能需要根据数据类型 value1 去设置默认的 formatter
> * 参考 `__tests__/plots/tooltip/aapl-line.ts` 添加一个测试，CI 报错可以不管
1. title的处理过程中针对于无回调处理的title做了处理
2. 新增测试文件__tests__/plots/tooltip/aapl-line-date-default-format.ts

2023-11-08 09:49 UTC, pearmini requested changes
有两个地方需要改一下：

- 不需要去处理时间字符串，如果是一个字符串就返回字符串，只有当值是 Date 对象的时候再处理。这里的部分原因是 `Date.parse` 在不同浏览器的兼容性不同。
- 不应该根据 title 的类型（数组？回调？对象）去判断是否格式化时间，而是当 value 是 Date 的时候统一处理，相当于替换默认的 `Date.toString` 函数，因为 Date 最后展示出来都是字符串。

类似所有情况，作如下的处理：

```js
if (typeof item === 'function') {
  const values = [];
  for (const i of I) {
    const v = item(data[i], i, data, encode);
    const v1 = v instanceOf Date ? dynamicFormatDateTime(v) : v ; // 👈
    if (isStrictObject(v)) values[i] = v1;
    else values[i] = { value: v1 };
  }
  return values;
}
```

2023-11-08 10:27 UTC, BENcorry commented
> 有两个地方需要改一下：
> 
> * 不需要去处理时间字符串，如果是一个字符串就返回字符串，只有当值是 Date 对象的时候再处理。这里的部分原因是 `Date.parse` 在不同浏览器的兼容性不同。
> * 不应该根据 title 的类型（数组？回调？对象）去判断是否格式化时间，而是当 value 是 Date 的时候统一处理，相当于替换默认的 `Date.toString` 函数，因为 Date 最后展示出来都是字符串。
> 
> 类似所有情况，作如下的处理：
> 
> ```js
> if (typeof item === 'function') {
>   const values = [];
>   for (const i of I) {
>     const v = item(data[i], i, data, encode);
>     const v1 = v instanceOf Date ? dynamicFormatDateTime(v) : v ; // 👈
>     if (isStrictObject(v)) values[i] = v1;
>     else values[i] = { value: v1 };
>   }
>   return values;
> }
> ```

有几个小问题：
1. 当tooltip不做处理的时候，title到valueof的时候是一个列表，可能走不到处理逻辑
2. 通过maybeTitle在做transform的时候直接处理会不会更好一点，这个时候Date会应为join直接转化为String

2023-11-09 03:31 UTC, merged

2023-11-13 01:40 UTC, hustcc commented
- fixed https://github.com/antvis/G2/issues/4995