docs(Transform): Translate transform to En
antvis/G2 pull request #5759
Opened 2023-11-07 10:23 UTC by Zhizhi-2986

#5743 

##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

2023-11-08 02:23 UTC, pearmini requested changes
- 注意大小写问题：比如 Mark
- 文中出现的 conversion 全部变成 transform

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +Transform is an array, executed in the order when they are declared. It can be configured at the hierarchy of Mark:
hierarchy of Mark -> level of mark

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +## Mark conversion
Mark conversion -> Mark Transform

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +Mark conversion will modify the data bound to each channel, thereby changing the display form of the chart. For example, StackY conversion stacks the column data bound to bar graph y and y1 channels:
Mark conversion -> Mark Transform

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +## View conversion
View conversion -> View Transform

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +Conversion declared on the view will be passed on to the Mark declared in `children`. Set if it is not converted, otherwise, it has no effect. For example, the following stacked area chart with conve
Conversion -> Transform

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +There are generally two common conversion functions:
conversion -> transform

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +One function of conversion is to prevent overlap. For example, the bars in the following data bar chart overlap.
conversion -> transform

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +This is actually one of the functions of Mark conversion: **Prevent overlap** In addition to DodgeX, there are also transformations such as StackY and JitterX that can be used to prevent overlap.
conversion -> transform

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +This is actually one of the functions of Mark conversion: **Prevent overlap** In addition to DodgeX, there are also transformations such as StackY and JitterX that can be used to prevent overlap.
`**Prevent overlap**` 后面添加句号

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +In addition to preventing overlap, there is also a type of Mark conversion mainly used for data aggregation: such as Bin and Group. Different from traditional data aggregation, Mark aggregation occur
Mark -> mark

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +First, let's draw a scatter diagram as follows, showing the correlation between penguin culmen_depth_mm and culmen_length_mm.
scatter diagram -> scatterplot

2023-11-08 02:23 UTC, pearmini commented on site/docs/manual/core/transform.en.md
> +## Multiple conversions
Multiple conversions -> Multiple Transform

2023-11-08 03:32 UTC, Zhizhi-2986 commented
> * 注意大小写问题：比如 Mark
> * 文中出现的 conversion 全部变成 transform

好的，我注意一下

2023-11-09 08:33 UTC, pearmini requested changes
🚀🚀🚀

还剩下几个小问题！

2023-11-09 08:33 UTC, pearmini commented on site/docs/manual/core/animation.en.md
> +Animation properties can be used as a channel in G2, and can also encode data. For example, in the Gantt chart below, the appearance and duration of each bar are linearly related to the data.
gantt -> gantt

2023-11-09 08:33 UTC, pearmini commented on site/docs/manual/core/coordinate.en.md
> +**The Coordinate System** in G2 will perform a series of point transform. In G2, the marked position channels x and y will be mapped to the range [0,1] through a scale mapping, after that, the coordi
marked -> mark's

2023-11-09 08:33 UTC, pearmini commented on site/docs/manual/core/coordinate.en.md
> +The coordinate system be configured at the level of View:
View -> view

2023-11-09 08:33 UTC, pearmini commented on site/docs/manual/core/coordinate.en.md
> +you can also use interval mark and theta coordinate system to draw pie charts.
you -> Your

2023-11-09 08:33 UTC, pearmini commented on site/docs/manual/core/coordinate.en.md
> +You can also use interval mark and radial coordinate systems to draw Yujue charts.
Yujue -> radial

2023-11-09 08:33 UTC, pearmini commented on site/docs/manual/core/label.en.md
> +- `function`- Custom selector
`- `function`- Custom selector` -> `- **function** - custom selectir`

2023-11-10 06:04 UTC, pearmini approved these changes
LGTM

2023-11-10 06:05 UTC, merged