Doc/bundle ssr
antvis/G2 pull request #5763
Opened 2023-11-07 15:22 UTC by Exlau

##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [x] documents are updated

##### Description of change

2023-11-08 03:19 UTC, pearmini requested changes
CR 了两篇，一些问题注意一下：

- 大小写：特别是 Mark
- 主语的缺失：可能是中文就有问题，可以一并改一下

每翻译一篇可以通读一下，修改存在的问题。后面没有 CR 的三篇可以先看看有没有类似的问题。

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/3d-charts.en.md
> +* Using camera interaction and animation
添加句号

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/3d-charts.en.md
> +* [g-plugin-control](https://g.antv.antgroup.com/plugins/control) Provide camera interaction in 3D scenes
添加句号

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/3d-charts.en.md
> +We use [point3D](/specs/thread/point-thread) Mark and select cube as the shape to draw.
Mark -> mark

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/3d-charts.en.md
> +In a 3D scene we can use orthographic or perspective projection, and the camera can be get from the Chart context after the first rendering is completed. You can then use the [Camera API](https://g.a
Camera API -> camera API

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/bundle.en.md
> +G2 version 5.0.19 publishs the on-demand packaging function. Can use [Tree-Shaking](https://rollupjs.org/introduction/#tree-shaking) ablility of tools like [Rollup](https://rollupjs.org/),[Webpack](h
Can use 这句话不太通顺？

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/bundle.en.md
> +The architecture of G2 is composed of Runtime + library. Runtime is responsible for the rendering process, and library is a JavaScript Object composed of a series of visual components, used to proces
Object -> object

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/bundle.en.md
> +Return to the core library, containing only basic Mark. You can view the included visual components through the source code. ([Source code](https://github.com/antvis/G2/blob/v5/src/lib/core.ts)·[Case
Mark -> mark

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/bundle.en.md
> +Return to an advanced statistical analysis library, including some sophisticated statistical tags (Snakey et al.) and transformations (Venn et al.). Cannot be used alone, must be used with [G2.coreli
Cannot be used alone -> 这里缺少主语？

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/bundle.en.md
> +Returns the geographical analysis library, including geographical tags (GeoPath, etc.) and projections (Projection). Cannot be used alone, must be used with [G2.corelib](#g2corelib). You can view the
Cannot be ->  没有主语？

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/bundle.en.md
> +Returns the enhanced analysis library, providing enhanced analysis tags (Auto, etc.). This library will depend on [@antv/ava](https://github.com/antvis/AVA), providing capabilities such as automatic
Cannot be -> 缺少主语？

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/bundle.en.md
> +* Provide a smaller library than corelib: Mark-level on-demand packaging can be achieved.
Mark -> mark

2023-11-08 03:19 UTC, pearmini commented on site/docs/manual/extra-topics/bundle.en.md
> +The current thinking for the third idea is: provide `G2.litelib`, Mark can be imported on demand.
Mark -> mark

2023-11-08 06:19 UTC, Exlau commented on site/docs/manual/extra-topics/3d-charts.en.md
> +* Using camera interaction and animation
Resolved please check.

2023-11-08 06:19 UTC, Exlau commented on site/docs/manual/extra-topics/3d-charts.en.md
> +* [g-plugin-control](https://g.antv.antgroup.com/plugins/control) Provide camera interaction in 3D scenes
Resolved please check.

2023-11-08 06:19 UTC, Exlau commented on site/docs/manual/extra-topics/3d-charts.en.md
> +We use [point3D](/specs/thread/point-thread) Mark and select cube as the shape to draw.
Resolved please check.

2023-11-08 06:19 UTC, Exlau commented on site/docs/manual/extra-topics/3d-charts.en.md
> +In a 3D scene we can use orthographic or perspective projection, and the camera can be get from the Chart context after the first rendering is completed. You can then use the [Camera API](https://g.a
Resolved please check.

2023-11-08 06:19 UTC, Exlau commented on site/docs/manual/extra-topics/bundle.en.md
> +G2 version 5.0.19 publishs the on-demand packaging function. Can use [Tree-Shaking](https://rollupjs.org/introduction/#tree-shaking) ablility of tools like [Rollup](https://rollupjs.org/),[Webpack](h
Resolved please check.

2023-11-08 06:19 UTC, Exlau commented on site/docs/manual/extra-topics/bundle.en.md
> +The architecture of G2 is composed of Runtime + library. Runtime is responsible for the rendering process, and library is a JavaScript Object composed of a series of visual components, used to proces
Resolved please check.

2023-11-08 06:19 UTC, Exlau commented on site/docs/manual/extra-topics/bundle.en.md
> +Return to the core library, containing only basic Mark. You can view the included visual components through the source code. ([Source code](https://github.com/antvis/G2/blob/v5/src/lib/core.ts)·[Case
Resolved please check.

2023-11-08 06:19 UTC, Exlau commented on site/docs/manual/extra-topics/bundle.en.md
> +Return to an advanced statistical analysis library, including some sophisticated statistical tags (Snakey et al.) and transformations (Venn et al.). Cannot be used alone, must be used with [G2.coreli
Resolved please check.

2023-11-08 06:19 UTC, Exlau commented on site/docs/manual/extra-topics/bundle.en.md
> +Returns the geographical analysis library, including geographical tags (GeoPath, etc.) and projections (Projection). Cannot be used alone, must be used with [G2.corelib](#g2corelib). You can view the
Resolved please check.

2023-11-08 06:20 UTC, Exlau commented on site/docs/manual/extra-topics/bundle.en.md
> +* Provide a smaller library than corelib: Mark-level on-demand packaging can be achieved.
Resolved please check.

2023-11-08 06:20 UTC, Exlau commented on site/docs/manual/extra-topics/bundle.en.md
> +The current thinking for the third idea is: provide `G2.litelib`, Mark can be imported on demand.
Resolved please check.

2023-11-09 08:42 UTC, pearmini requested changes
🚀🚀🚀

还有几个小问题

2023-11-09 08:42 UTC, pearmini commented on site/docs/manual/extra-topics/event.en.md
> +G2 exposes some events to get the chart life cycle and interaction information. G2 exported a `ChartEvent` type, used to define the type of event.
exported -> exports

2023-11-09 08:42 UTC, pearmini commented on site/docs/manual/extra-topics/event.en.md
> +* Monitor the global `Mark` event
Mark -> element

2023-11-09 08:42 UTC, pearmini commented on site/docs/manual/extra-topics/event.en.md
> +* Monitor specified `Mark` event
Mark -> element

2023-11-09 08:42 UTC, pearmini commented on site/docs/manual/extra-topics/event.en.md
> +* Listen to Plot area events
Plot -> plot

2023-11-09 08:42 UTC, pearmini commented on site/docs/manual/extra-topics/pattern.en.md
> +Then you can use the built-in patterns. In this [example](/zh/examples/theme/pattern#lines-pattern):
`/zh/examples/theme/` -> `en/examples/theme/`

2023-11-09 10:57 UTC, Exlau commented on site/docs/manual/extra-topics/pattern.en.md
> +Then you can use the built-in patterns. In this [example](/zh/examples/theme/pattern#lines-pattern):
Resovled please check

2023-11-10 03:40 UTC, pearmini commented
最后一个问题，这个 PR 更新了一下 ssr 的中文：https://github.com/antvis/G2/pull/5780 ，因为也对应重新翻译一下？

2023-11-10 04:51 UTC, closed without merging

2023-11-10 05:02 UTC, Exlau commented
Hello @pearmini  issue resovled, 这个PR我rebase出了点问题，我新提了一个PR [5781](https://github.com/antvis/G2/pull/5781)