docs: translate getting-started, what-is-g2, why-g2
antvis/G2 pull request #5778
Opened 2023-11-09 10:24 UTC by pitaokkk

##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [x] documents are updated

##### Description of change

translate 3 files in introduction to english

2023-11-10 07:06 UTC, pearmini requested changes
🚀🚀🚀

翻译完了读一下文档，保证通顺和格式没有错误，下面有两个比较通用的问题：

- markers -> mark
- `**xxx**` 前后两端加空格

2023-11-10 07:06 UTC, pearmini commented on site/docs/manual/introduction/why-g2.en.md
> +The most wonderful thing about G2 is that you can get new charts by combining different charts (more precisely markers)! For example, if we add the Point mark of the scatter chart and the Link mark o
markers -> marks

2023-11-10 07:06 UTC, pearmini commented on site/docs/manual/introduction/why-g2.en.md
> +In the process of visualization, processing data often takes a lot of time, and there is a certain cost of getting started. To simplify this process, reduce data preprocessing time and standardize co
- `**Transform**` 前后加空格

2023-11-10 07:06 UTC, pearmini commented on site/docs/manual/introduction/why-g2.en.md
> +In addition to providing rich built-in interactions, G2 also`chart.on`and`chart.emit`Provides an ability to link interactions between different views, such as the "Focus and Context" ability shown be
- `G2 also`chart.on`and`chart.emit`Provides` 这句话修改一下

2023-11-10 07:06 UTC, pearmini commented on site/docs/manual/introduction/why-g2.en.md
> +G2 provides two styles of API:**Functional API**and**Optional API**. The former declares the chart through a series of function chain calls, and the latter declares the chart through a JavaScript obj
- `**Functional API**and**Optional API**` 加空格

2023-11-10 07:06 UTC, pearmini commented on site/docs/manual/introduction/why-g2.en.md
> +G2 provides two styles of API:**Functional API**and**Optional API**. The former declares the chart through a series of function chain calls, and the latter declares the chart through a JavaScript obj
- `For example in[Concise syntax](<concise syntax>)If` 这个地方改一下

2023-11-10 07:06 UTC, pearmini commented on site/docs/manual/introduction/why-g2.en.md
> +G2 is an architecture built by**Runtime**and a series of**Visual component (Component)**constituted. The runtime is mainly responsible for completing data mapping, creation and inference of scales, e
- `**Runtime**` 前后空格
- `**Visual component (Component)**` 前后空格

2023-11-13 02:33 UTC, pearmini requested changes
修改的很好，还差几个小问题

2023-11-13 02:33 UTC, pearmini commented on site/docs/manual/introduction/getting-started.en.md
> + G2 also provides a UMD version, which can be loaded directly through CDN and used directly. At this time `Chart` Objects can be accessed through namespaces`G2`Go visit.
- `namespaces`G2`Go visit.` 不通顺？
- 同样 G2 前后也要加空格

2023-11-13 02:33 UTC, pearmini commented on site/docs/manual/introduction/what-is-g2.en.md
> +## more capabilities
More 需要大些

2023-11-15 02:20 UTC, pearmini commented
@pitaokkk 这个 PR 我先合并了，因为时间比较久了，存在的问题我提一个 PR 解决一下。

2023-11-15 02:20 UTC, merged

2023-11-15 02:34 UTC, pitaokkk commented
好嘞

2023-11-15 02:36 UTC, pitaokkk commented
抱歉回复的有点迟