feat(mark): add chord mark
antvis/G2 pull request #5810
Opened 2023-11-18 15:12 UTC by Gavinchen92

##### Checklist

- [x] `npm test` passes
- [ ] benchmarks are included
- [x] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

1. 增加Chord Mark
2. 增加Chord单测

2023-11-19 17:40 UTC, Gavinchen92 commented
@hustcc  @pearmini 帮忙补充下弦图的示例图

2023-11-20 01:57 UTC, pearmini requested changes
可以在 `site/examples/graph/hierarchy/demo` 下面在添加几个 Demo？ Demo 截图你发给我，我帮你上传后，把链接给你

2023-11-20 04:51 UTC, Gavinchen92 commented
> 可以在 `site/examples/graph/hierarchy/demo` 下面在添加几个 Demo？ Demo 截图你发给我，我帮你上传后，把链接给你

放在network下面是否更合适？

2023-11-20 04:58 UTC, pearmini commented
> 放在network下面是否更合适？

嗯嗯，放在 network 下面好一点

2023-11-20 08:41 UTC, pearmini approved these changes

2023-11-20 08:42 UTC, merged