feat(slider): support sparkline
antvis/G2 pull request #5832
Opened 2023-11-22 06:36 UTC by deletenothing

##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

feat(slider): support sparkline
slider组件默认使用图表数据展示迷你图

2023-11-22 07:43 UTC, pearmini requested changes
- 运行  `npm t` 生成一下截图
- 在官网添加一个例子？

2023-11-22 07:43 UTC, pearmini commented on __tests__/plots/static/aapl-line-basic.ts
> +      }
这个的注释可以去掉

2023-11-22 07:47 UTC, deletenothing commented on __tests__/plots/static/aapl-line-basic.ts
> +      }
好的

2023-11-22 08:00 UTC, deletenothing commented on __tests__/plots/static/aapl-line-basic.ts
> +      }
![微信截图_20231122155636](https://github.com/antvis/G2/assets/55045285/fbd4e3f3-589f-42d0-aab0-ab3efae75e2f)

2023-11-22 08:06 UTC, deletenothing commented on __tests__/plots/static/aapl-line-basic.ts
> +      }
以及想问一下，新增一个例子具体是指在哪里呢

2023-11-22 09:10 UTC, pearmini commented on __tests__/plots/static/aapl-line-basic.ts
> +      }
- 这个 fail 的数量感觉不太正常，你 rebase 一下 v5，然后重新安装依赖试试？
- 这里 `site/examples/component` 增加一个 slider 文件夹。

2023-11-24 02:04 UTC, pearmini requested changes

2023-11-24 02:04 UTC, pearmini commented on src/component/slider.ts
> +    const { scales: [scale], value, theme, coordinate } = content;
这个不是 content，是 context

2023-11-24 02:04 UTC, pearmini commented on src/component/slider.ts
> +  if (options.sparklineData && isArray(options.sparklineData))
这个直判断 `Array.isArray(options.sparklineData)` 就可以了

2023-11-27 01:29 UTC, deletenothing commented on src/component/slider.ts
> +  if (options.sparklineData && isArray(options.sparklineData))
- 我在对__tests__文件中actual进行.replace(/\n/g，'rin').slice(，-1)处理后得到了正常的测试结果
<img width="643" alt="2c52a2ff79baffcd505efd4b50dd43d" src="https://github.com/antvis/G2/assets/55045285/cf865cfc-20f5-4dfc-8cf1-1c53e6d862df">
其中两个failed对比如下，
<img width="962" alt="dfc06ca7ae22a30fa7aa6bfc9795043" src="https://github.com/antvis/G2/assets/55045285/379d5a36-224e-4f3f-a76a-4f45132a769e">
<img width="968" alt="2c1549d26216cd0087dfc309573b1b9" src="https://github.com/antvis/G2/assets/55045285/931a3a37-379d-4d8f-8fba-2c413dfb2a3c">
我觉得算是符合预期的？
- npm run fix的脚本在windows上运行会产生1000+的修改，因此我改了一下只扫了slider.ts

2023-11-27 02:43 UTC, pearmini commented on src/component/slider.ts
> +  if (options.sparklineData && isArray(options.sparklineData))
嗯嗯，这个是复合预期的，我可以把之前的截图删除，然后重新生成 `npm t` 即可。

2023-11-27 02:45 UTC, pearmini requested changes
Rebase 一下 V5 的最新分支，不然会包含别的提交记录。

2023-11-28 05:30 UTC, pearmini commented
@deletenothing 本地运行 `npm t` 是通过的吗？

2023-11-28 06:54 UTC, deletenothing commented
> @deletenothing 本地运行 `npm t` 是通过的吗？

两个failed，就上面截图那两个

2023-11-28 07:27 UTC, pearmini commented
> 两个failed，就上面截图那两个

嗯嗯，可以 `__tests__/integration/snapshots` 中对应的图片删除，然后重新运行 `npm t` 运行即可

2023-11-28 09:10 UTC, deletenothing commented
> > 两个failed，就上面截图那两个
> 
> 嗯嗯，可以 `__tests__/integration/snapshots` 中对应的图片删除，然后重新运行 `npm t` 运行即可

然后我需要再提交一次吗

2023-11-28 09:13 UTC, pearmini commented
> 然后我需要再提交一次吗

需要，目的是保证 CI 能通过

2023-11-29 02:54 UTC, pearmini approved these changes
CI 过了！非常优秀，还解决了 Windows 下的测试环境问题。

2023-11-29 02:55 UTC, merged