Fix ci issues
antvis/G2 pull request #5839
Opened 2023-11-24 06:49 UTC by thejasonxie

##### Checklist

- [x] `npm test` passes
- [x] commit message follows commit guidelines

##### Description of change
My previous PR had ci issues. Still new to contributing, so didn't realize tests not related to my prev commits had to be fixed as well. 

**Fixed following ci issues:**
- style linting - 4 files weren't following correct style format
- test - fixed chart show and hide test failure
- test - github actions requires more time for animation to complete before testing

2023-11-24 07:30 UTC, pearmini requested changes

2023-11-24 07:30 UTC, pearmini commented on src/chart/chart.ts
> +    super.changeVisible(visible);
为啥要添加这行代码？

2023-11-25 02:48 UTC, thejasonxie commented on src/chart/chart.ts
> +    super.changeVisible(visible);
Yeah sorry I don't remember my thought process here. My goal was to fix the [show()](https://github.com/antvis/G2/blob/v4.1.x/tests/unit/chart/chart-spec.ts#L97) and [hide()](https://github.com/antvis/G2/blob/v4.1.x/tests/unit/chart/chart-spec.ts#L104) tests and it somehow worked. I do realize now that it is not the proper solution.

I reverted this commit and used method overriding as the new solution. Thanks.

2023-11-27 02:38 UTC, pearmini commented on src/chart/chart.ts
> +    super.changeVisible(visible);
Ok, I get it.

2023-11-27 02:42 UTC, pearmini approved these changes

2023-11-27 02:42 UTC, merged