docs: add simple pie demos
antvis/G2 pull request #5921
Opened 2023-12-11 13:57 UTC by li1615882553

> close: https://github.com/antvis/G2/issues/5899

迁移 4.0 官网中的饼图样例：

简单饼图：
<img width="841" alt="简单饼图" src="https://github.com/antvis/G2/assets/35752509/1ea5541e-f5dd-460b-a6b3-59099ec65ce8">
简单环图：
<img width="777" alt="简单环图" src="https://github.com/antvis/G2/assets/35752509/b0413a5a-54d4-49ff-9660-786d0b49b716">
分面环图
<img width="1153" alt="分面换图" src="https://github.com/antvis/G2/assets/35752509/0360b25a-8082-445e-9c57-8e2e9224742f">

2023-12-12 02:36 UTC, pearmini requested changes
分面环图实现得很不错。修复了 CR 建议之后，重新贴一下图，我帮你上传。

2023-12-12 02:36 UTC, pearmini commented on site/examples/general/pie/demo/pie-base.ts
> +  })
这个就不用配置了，简单饼图就展示默认色板即可。

2023-12-12 02:36 UTC, pearmini commented on site/examples/general/pie/demo/donut-base.ts
> +  })
这个也不用设置了，色板使用默认的即可

2023-12-12 02:36 UTC, pearmini commented on site/examples/general/pie/demo/pie-base-face.ts
> +import { Chart } from '@antv/g2';
这个文件叫 `pie-base-facet` 会好一点，facet 是分面更准确的英文。

2023-12-12 05:04 UTC, li1615882553 commented
> 分面环图实现得很不错。修复了 CR 建议之后，重新贴一下图，我帮你上传。

已更新

2023-12-12 05:39 UTC, pearmini commented
@li1615882553  这里是链接：

- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*1yoaSJ0rfrYAAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*06RqSKmmVbEAAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*enGVRIWj9KUAAAAAAAAAAAAADmJ7AQ/original

2023-12-13 01:19 UTC, li1615882553 commented
> @li1615882553 这里是链接：
> 
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*1yoaSJ0rfrYAAAAAAAAAAAAADmJ7AQ/original
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*06RqSKmmVbEAAAAAAAAAAAAADmJ7AQ/original
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*enGVRIWj9KUAAAAAAAAAAAAADmJ7AQ/original

已更新链接

2023-12-13 02:33 UTC, merged

2023-12-13 02:34 UTC, pearmini commented
感谢对 G2 的贡献！欢迎加入 G2 开源先锋群：

<img src="https://github.com/antvis/G2/assets/49330279/38ede750-f3d1-44f3-971e-e96865383078" width=400 />