feat(interaction): add drilldown in treemap
antvis/G2 pull request #5962
Opened 2023-12-21 02:39 UTC by ai-qing-hai

![image](https://github.com/antvis/G2/assets/65594180/92ad3370-6aee-4fba-8878-4b0f6bba24a9)

2023-12-22 02:55 UTC, pearmini requested changes
legend 交互不更新的原因可能是：update 的时候没有去 reapply 它，相关代码在这：

https://github.com/antvis/G2/blob/a63e388532d89b8e3b1ed57c83b9c290b8861187/src/runtime/plot.ts#L400

看看能不能通过给 update 函数传递一个参数，使得所有交互都更新。

2023-12-22 02:55 UTC, pearmini commented on site/examples/graph/hierarchy/demo/treemap-drill-down.ts
> +      },
这里的 API 设计和其余交互不太统一，应该是：breadCrumbY, breadCrumbFill

2023-12-22 02:55 UTC, pearmini commented on src/interaction/drillDown.ts
> +  };
这个拍平

2023-12-22 02:55 UTC, pearmini commented on src/interaction/drillDown.ts
> +            console.log(textGroup.getBBox());
去掉哈

2023-12-27 08:58 UTC, pearmini requested changes

2023-12-27 08:58 UTC, pearmini commented on site/examples/graph/hierarchy/demo/treemap-drill-down.ts
> +      },
这个地方可以写成如下吗？

```js
.interaction({ drillDown: { breadCrumbY: 12, activeFill: '#873bf4' }})
```

参考 Tooltip 的 API。

2023-12-27 10:14 UTC, ai-qing-hai commented on site/examples/graph/hierarchy/demo/treemap-drill-down.ts
> +      },
修改好了

2023-12-28 06:49 UTC, ai-qing-hai commented on src/interaction/drillDown.ts
> +            console.log(textGroup.getBBox());
已删除

2023-12-28 06:49 UTC, ai-qing-hai commented on src/interaction/drillDown.ts
> +  };
已修改

2023-12-28 06:49 UTC, ai-qing-hai commented on site/examples/graph/hierarchy/demo/treemap-drill-down.ts
> +      },
已修改

2024-01-03 03:12 UTC, pearmini requested changes
非常的优秀！再添加一下截图测试就好了！

2024-01-04 03:08 UTC, ai-qing-hai commented
> 非常的优秀！再添加一下截图测试就好了！

已添加

2024-01-04 03:20 UTC, pearmini approved these changes

2024-01-04 07:28 UTC, pearmini requested changes
Rebase 一下 V5，把这些 commit 合并成一个，可以本地测试通过了再 push

<img width="680" alt="image" src="https://github.com/antvis/G2/assets/49330279/29cd2c3d-5c44-4eed-b27b-9c8b4f18a0d4">

2024-01-04 09:19 UTC, closed without merging