fix: fix point scale generates gradient color
antvis/G2 pull request #5977
Opened 2023-12-24 13:41 UTC by li1615882553

##### Checklist

- [x] `npm test` passes
- [ ] benchmarks are included
- [x] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

解决问题：
1.fixes #5230 修复x轴为point类型坐标系时，拖动Slider计算渐变色产生undefined的问题 

解决方案：
1.针对拖动Slider产生的NaN，数据不参与映射，直接返回0

修复后：

https://github.com/antvis/G2/assets/35752509/9af17531-149a-46cf-ae23-60bad7845308

2023-12-25 02:20 UTC, pearmini requested changes
修复得很简洁，但是还需要添加一下截图测试，参考这个：https://github.com/antvis/G2/pull/5914

2023-12-25 02:20 UTC, pearmini commented on src/shape/utils.ts
> +  const percentage = (i) => (Number.isNaN(P[i]) ? 0 : p.map(P[i]));
这里有两个问题：

1. P[i] 可能是 undefined 或者 null 吗？
2. 如果是是，可以正常绘制出来吗？

2024-01-03 03:15 UTC, pearmini commented
@li1615882553 有看看 CR 哈 🤣

2024-01-03 03:28 UTC, li1615882553 commented
> @li1615882553 有看看 CR 哈 🤣

嗯嗯，发现了个新问题还没解决：计算渐变色没有考虑起始线条断开的情况，如果起始线条是断开的，会导致渐变色向后移动
正常情况：
![image](https://github.com/antvis/G2/assets/35752509/dc542fb5-b2b8-45bf-9f07-3118085b02d4)
起始断开情况：
![image](https://github.com/antvis/G2/assets/35752509/5b5a6b17-fba1-4f03-b11c-4d8b522fc215)

2024-01-05 09:05 UTC, pearmini commented
@li1615882553 有办法解决吗？

2024-01-08 13:00 UTC, li1615882553 commented on src/shape/utils.ts
> +  const percentage = (i) => (Number.isNaN(P[i]) ? 0 : p.map(P[i]));
> 这里有两个问题：
> 
> 1. P[i] 可能是 undefined 或者 null 吗？
> 2. 如果是是，可以正常绘制出来吗？

在scale配置里，可以指定unknown的值，导致p[i]可能是任意值，所以加了一个数字判断并且非NaN的情况下才走map，否则直接返回0

线条如果起始断开的时候，渐变色向后移动这个问题还没找到好的解决办法

2024-01-09 10:03 UTC, merged