feat: 添加G2 中Table的mark
antvis/G2 pull request #6088
Opened 2024-02-21 12:04 UTC by kun6696

##### Checklist

- [ ] `npm test` passes
- [] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

2024-02-21 12:14 UTC, pearmini requested changes

2024-02-23 08:52 UTC, kun6696 commented
![2024-02-23 16 50 15](https://github.com/antvis/G2/assets/143773015/0eb32230-8710-434f-90d2-e5dd66e2c051)
这里按照scrollbar 配置 ratio:range。首次展示的正确，翻页的时候，出现错乱的情况  @pearmini

2024-02-23 09:22 UTC, pearmini commented
@kun6696 这个应该是离散 slider 的一个 bug，我下周看看能不能修复

2024-03-04 08:00 UTC, kun6696 commented
> @kun6696 This should be a bug in the discrete slider. I’ll see if it can be fixed next week.

Is there any repair?

2025-04-08 02:20 UTC, closed without merging