[WIP](interaction): add elementpointmove interaction
antvis/G2 pull request #6110
Opened 2024-03-05 07:55 UTC by ai-qing-hai

add elementPointMove
![image](https://github.com/antvis/G2/assets/65594180/00d4ba80-4ff1-427b-9bfe-5bba4b0f9ceb)

- [ ] line add
    - [x] 折线图可用
    - [ ]  雷达图可用
- [ ] interval add
    - [x] 柱状图可用
    - [x] 条形图可用
    - [ ] 饼图可用

2024-03-08 02:31 UTC, pearmini requested changes
很优秀，几个 API 设计可能还需要考虑一下。

2024-03-08 02:31 UTC, pearmini commented on __tests__/plots/static/flare-element-point-move-radar.ts
> +        selected: [1, 4],
这里的 selected 是 [1, 4] 是 index 的意思吗？其他类似交互声明初始状态是通过 `chart.emit` 来实现的，比如 elementHight: `chart.emit('element:highlight', options)`，这里需要保持一致吗？

2024-03-08 02:31 UTC, pearmini commented on site/examples/interaction/data/demo/bar-element-point-move.ts
> +      },
这里的回调其他交互是通过 `chart.on` 实现的，比如 `chart.on('element:highlight', options)` 这里应该保持一致？

```js
chart.on('point:select', () => {});
chart.on('point:unselect', () => {});
chart.on('point:move', () => {});
```

回调参数的设计参考其他交互。

2024-03-11 03:31 UTC, ai-qing-hai commented on site/examples/interaction/data/demo/bar-element-point-move.ts
> +      },
已修改，   修改为 element:select point:moveed  element:unselect

2024-03-11 03:31 UTC, ai-qing-hai commented on __tests__/plots/static/flare-element-point-move-radar.ts
> +        selected: [1, 4],
已经修改。 但我同时保留 selection： [1,4] 的配置方式

2024-03-11 08:03 UTC, pearmini commented on site/examples/interaction/data/demo/bar-element-point-move.ts
> +      },
> element:select  element:unselect

如果同时有 elementPointMove 和 elementSelect，上面的事件会冲突吗？

2024-03-11 08:53 UTC, ai-qing-hai commented on site/examples/interaction/data/demo/bar-element-point-move.ts
> +      },
冲突的意思是？

2024-03-11 08:58 UTC, ai-qing-hai commented on site/examples/interaction/data/demo/bar-element-point-move.ts
> +      },
elementPointMove 和 elementSelect 和 上面的事件挂载的对象不一样， point 和 element 以及 chart 。 互不干扰 @pearmini

2024-03-13 08:13 UTC, pearmini commented on site/examples/interaction/data/demo/bar-element-point-move.ts
> +      },
```js
chart.on('point:select', () => {});
```

这个有歧义，可以 point 的 mark 的 select 事件，也可以是新增交互的事件。

2024-03-14 07:25 UTC, ai-qing-hai commented on site/examples/interaction/data/demo/bar-element-point-move.ts
> +      },
@pearmini  这个交互的事件 就 element:select 和 element:unselect 以及 point:moveend 。 没有 point:click

2024-03-14 09:50 UTC, pearmini approved these changes

2024-03-14 11:43 UTC, merged