docs: add radial graph demos
antvis/G2 pull request #6116
Opened 2024-03-09 16:34 UTC by LonelySnowman

##### Checklist

- [x] `npm test` passes
- [x] benchmarks are included
- [x] commit message follows commit guidelines
- [x] documents are updated

##### Description of change

相关issue：https://github.com/antvis/G2/issues/5902

2024-03-09 16:40 UTC, LonelySnowman commented
![image](https://github.com/antvis/G2/assets/111493458/e38168b3-a24a-470b-aabb-43a12e7fe28f)

![image](https://github.com/antvis/G2/assets/111493458/ce2c64f9-a3d2-40c1-af88-8b2b725dc89c)

![image](https://github.com/antvis/G2/assets/111493458/6195c747-3185-48f2-886a-5b8feadb0629)

2024-03-13 08:17 UTC, pearmini commented
很优秀！图片链接在下面：

- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*9FxwQIEcoDMAAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*h3MESLqnM4QAAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*T3NtSLBLc0sAAAAAAAAAAAAADmJ7AQ/original

2024-03-14 02:19 UTC, LonelySnowman commented
连接已更新

2024-03-14 02:23 UTC, pearmini requested changes

2024-03-14 02:23 UTC, pearmini commented on site/examples/general/radial/demo/radial-stacked.ts
> +// 数据被加工成 { State: 'WY', 年龄段: '小于5岁', 人口数量: 25635 }
这个地方可以用 data transform 里面的 fold 来完成：https://g2.antv.antgroup.com/spec/data/fold

2024-03-14 03:05 UTC, LonelySnowman commented on site/examples/general/radial/demo/radial-stacked.ts
> +// 数据被加工成 { State: 'WY', 年龄段: '小于5岁', 人口数量: 25635 }
GET，已更新

2024-03-14 05:59 UTC, pearmini approved these changes

2024-03-14 05:59 UTC, merged

2024-03-14 07:04 UTC, pearmini commented
感谢给 G2 贡献代码，欢迎加入 G2 开源先锋群！

![1710399785165](https://github.com/antvis/G2/assets/49330279/434e02d0-4e33-40e9-854c-e599a021748c)