fix(label): 修复label显示错误的问题
antvis/G2 pull request #6172
Opened 2024-04-12 13:12 UTC by BENcorry

close: https://github.com/antvis/G2/issues/5960

###### 解决问题
借助图形标注展示总计 label 显示错误

###### 解决办法
原因：label显示问题的主要原因是在处理valueOf时，没有对datum类型的判断导致取值时datum为字符串，value为数字字符串‘3’，结果就是字符串的第三位，显示异常
解决办法：给datum增加类型判断即可

####### Case
```
import { G2Spec } from '../../../src';

export const data = [
  {
    time: '1991/01',
    value: 0,
    type: 'Lon',
  },
  {
    time: '1992/01',
    value: 4,
    type: 'Lon',
  },
  {
    time: '1993/01',
    value: 3.5,
    type: 'Lon',
  },
  {
    time: '1994/01',
    value: 1,
    type: 'Lon',
  },
  {
    time: '1995/01',
    value: 2,
    type: 'Lon',
  },
  {
    time: '1996/01',
    value: 3,
    type: 'Lon',
  },
  {
    time: '1997/01',
    value: 4,
    type: 'Lon',
  },
  {
    time: '1998/01',
    value: 9,
    type: 'Lon',
  },
  {
    time: '1999/01',
    value: 1,
    type: 'Lon',
  },
  {
    time: '1991/01',
    value: 3,
    type: 'Bor',
  },
  {
    time: '1992/01',
    value: 4,
    type: 'Bor',
  },
  {
    time: '1993/01',
    value: 3.5,
    type: 'Bor',
  },
  {
    time: '1994/01',
    value: 5,
    type: 'Bor',
  },
  {
    time: '1995/01',
    value: 2,
    type: 'Bor',
  },
  {
    time: '1996/01',
    value: 6,
    type: 'Bor',
  },
  {
    time: '1997/01',
    value: 7,
    type: 'Bor',
  },
  {
    time: '1998/01',
    value: 9,
    type: 'Bor',
  },
  {
    time: '1999/01',
    value: 1,
    type: 'Bor',
  },
];

export function stackBarAnnotationStyleText(): G2Spec {
  const groupData = data.reduce((acc, item) => {
    if (acc[item.time]) {
      acc[item.time] = [...acc[item.time], item];
    } else {
      acc[item.time] = [item];
    }
    return acc;
  }, {});

  const annotations = Object.keys(groupData).map((key) => {
    const val = groupData[key].reduce((a, b) => a + b.value, 0);
    console.log('val-=====>', val);
    return {
      type: 'text',
      data: [key, val],
      encode: {
        x: 'time',
        y: 'value',
      },
      style: {
        text: `${val}`,
        textBaseline: 'bottom',
        position: 'top',
        textAlign: 'center',
        fontSize: 14,
        fill: 'rgba(0,0,0,0.85)',
      },
      tooltip: false,
    };
  });
  return {
    type: 'view',
    height: 300,
    width: 640,
    data,
    children: [
      {
        type: 'interval',
        axis: { x: { labelAutoHide: true } },
        encode: {
          x: 'time',
          y: 'value',
          color: 'type',
        },
        transform: [
          {
            type: 'stackY',
          },
        ],
        labels: [
          {
            text: 'value',
            textBaseline: 'bottom',
            position: 'inside',
          },
        ],
      },
      ...annotations,
    ],
  };
}

```

###### 处理前
<img width="627" alt="image" src="https://github.com/antvis/G2/assets/25734833/3e23fa24-5f34-43d8-aca4-9e2d341bae56">

###### 处理后
<img width="867" alt="image" src="https://github.com/antvis/G2/assets/25734833/b6adcb72-9143-4c4e-ace1-00836bcd4ad3">

2024-04-13 08:36 UTC, BENcorry commented
比较奇怪我本地测试能过，github CI过不了

2024-04-13 13:24 UTC, BENcorry commented
> 比较奇怪我本地测试能过，github CI过不了 ![image](https://private-user-images.githubusercontent.com/25734833/322189538-975021e4-d366-4097-920f-e0da9cc8d227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTQyMTgsIm5iZiI6MTcxMzAxMzkxOCwicGF0aCI6Ii8yNTczNDgzMy8zMjIxODk1MzgtOTc1MDIxZTQtZDM2Ni00MDk3LTkyMGYtZTBkYTljYzhkMjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEzMTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMzg3ZDRkMzYzYTYyMDBlYWFlMzUxMDYzMDg4MDBlMmQ1YjI3NDg1MTIyMmVmY2MxMWVkNGMxOTdjZmE5ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xEXqmlBmrGX9HTntY8nPQYpEryS8RFwPZLuy2scSSM8)

node版本必须和ci环境一致才行，16.20.2

2024-04-18 08:17 UTC, pearmini requested changes

2024-04-18 08:17 UTC, pearmini commented on src/runtime/plot.ts
> +  if (datum[value] !== undefined && typeof datum === 'object')
这里判断是否为对象应该需要更严格一点？不然 date 和 null 也会走到这个分支？

2024-04-18 08:30 UTC, BENcorry commented on src/runtime/plot.ts
> +  if (datum[value] !== undefined && typeof datum === 'object')
需要加上null的逻辑，目前datum的类型定义是可选的any,如果datum为null可能导致异常。Date实例是没有public属性的，基本上会走到undefined的逻辑，我加一下null的逻辑

2024-04-19 02:48 UTC, pearmini requested changes

2024-04-19 02:48 UTC, pearmini commented on src/runtime/plot.ts
> +    return datum[value];
可以用 helper 里面的方法，并且建议判断类型放在前面：

```js
import { isStrictObject } from '../utils/helper';

// ...
if(isStrictObject(datum) && datum[value]) return datum[value]
```

2024-04-20 02:27 UTC, BENcorry commented on src/runtime/plot.ts
> +    return datum[value];
已经用isStrictObject做替换了哈

2024-04-22 02:15 UTC, pearmini approved these changes
LGTM

2024-04-22 02:18 UTC, merged