feat(label): add label transform feature exceedAdjust
antvis/G2 pull request #6209
Opened 2024-04-27 01:37 UTC by Runtus

##### Checklist

- [x] `npm test` passes
- [x] benchmarks are included
- [x] commit message follows commit guidelines
- [x] documents are updated

##### Description of change
* 增加Label下的transform-exceedAdjust新属性，当label超出 canvas 画布的时候，自动反方向移动位置，防止被剪裁。

2024-04-27 11:48 UTC, hustcc requested changes

2024-04-27 11:48 UTC, hustcc commented on site/docs/spec/label/exceedAdjust.en.md
> +title: overflowHide
这个名字没改。

2024-04-27 11:48 UTC, hustcc commented on src/label-transform/exceedAdjust.ts
> +    const { width, height } = coordinate.getOptions();
这个还不是画布的大小，是图形区域的大小，但是期望还是画布大小。

2024-04-27 11:48 UTC, hustcc commented on src/label-transform/exceedAdjust.ts
> +  const adjustCoorValue = (target: Bounds, edge: Bounds) => {
Coor 是什么意思？

2024-04-27 12:15 UTC, Runtus commented on src/label-transform/exceedAdjust.ts
> +  const adjustCoorValue = (target: Bounds, edge: Bounds) => {
是坐标的意思，意思就是判断坐标超出了多少，然后按照超出的值来计算反方向移动的值

2024-04-27 12:16 UTC, Runtus commented on src/label-transform/exceedAdjust.ts
> +    const { width, height } = coordinate.getOptions();
这个需要向大佬请教下，想问下画布大小可以通过什么方法来获取，我之前尝试找了下，我只找到了获得图形区域大小的方法

2024-04-28 01:29 UTC, Runtus commented on src/label-transform/exceedAdjust.ts
> +    const { width, height } = coordinate.getOptions();
> 这个还不是画布的大小，是图形区域的大小，但是期望还是画布大小。

这个想向大佬请教下，想问下画布大小可以通过什么方法来获取，我之前尝试找了下，我只找到了获得图形区域大小的方法

2024-04-28 04:34 UTC, hustcc commented on src/label-transform/exceedAdjust.ts
> +  const adjustCoorValue = (target: Bounds, edge: Bounds) => {
可以就叫 adjustPosition

2024-04-28 04:35 UTC, hustcc commented on src/label-transform/exceedAdjust.ts
> +    const { width, height } = coordinate.getOptions();
@pearmini 看看这个环境中有画布宽高吗？

2024-05-07 07:13 UTC, hustcc commented on src/label-transform/exceedAdjust.ts
> +    const { width, height } = coordinate.getOptions();
@Runtus 先固定在 plot 区域吧，也算是合理的。使用 Canvas 大小也有它的问题。

2024-05-07 07:16 UTC, hustcc commented on src/label-transform/exceedAdjust.ts
> +  const adjustCoorValue = (target: Bounds, edge: Bounds) => {
这个方法抽到 ExceedAdjust 外面吧，这样更纯净一些。

2024-05-07 10:15 UTC, hustcc commented
单测

2024-05-07 10:40 UTC, Runtus commented
> 单测报错了！

怪了，我本地跑test是通过的，不知道为啥CI的test没过

2024-05-07 11:09 UTC, hustcc commented on src/label-transform/exceedAdjust.ts
> + * Hide the label when overlap.
注释改一下。

2024-05-07 11:10 UTC, hustcc commented on src/label-transform/exceedAdjust.ts
> +          [width, height],
这个地方的 0,0 不太对，coordinate 的区域是有 x y width height 的。

2024-05-07 11:11 UTC, Runtus commented on src/label-transform/exceedAdjust.ts
> +          [width, height],
好的，我看下

2024-05-07 11:36 UTC, hustcc commented
等这个 PR https://github.com/antvis/G2/pull/6222 合并之后，合并进来，然后把那个碰撞的位置还是改成画布大小吧，刚想起来，coordinate 有可能是圆形的，如果用 coordinate 可能出 bug。

```ts
export const OverlapHide: LLC<OverlapHideOptions> = (options) => {
  const { priority } = options;
  return (labels: DisplayObject[], { canvas }) => {
    const x = 0;
    const y = 0;
    const { width, height } = canvas.getConfig();  // 这里
   // ...

  }
}
```

2024-05-07 11:39 UTC, Runtus commented
> 等这个 PR #6222 合并之后，合并进来，然后把那个碰撞的位置还是改成画布大小吧，刚想起来，coordinate 有可能是圆形的，如果用 coordinate 可能出 bug。
> 
> ```ts
> export const OverlapHide: LLC<OverlapHideOptions> = (options) => {
>   const { priority } = options;
>   return (labels: DisplayObject[], { canvas }) => {
>     const x = 0;
>     const y = 0;
>     const { width, height } = canvas.getConfig();  // 这里
>    // ...
> 
>   }
> }
> ```

明白

2024-05-07 12:50 UTC, hustcc commented on src/label-transform/exceedAdjust.ts
> +  return (labels: DisplayObject[], { coordinate, canvas }) => {
coordinate 变量不需要了。

2024-05-07 12:50 UTC, hustcc commented on src/label-transform/exceedAdjust.ts
> +          [x, y],
0 0 可以直接写这里，没问题的。

2024-05-07 14:32 UTC, hustcc approved these changes

2024-05-07 14:33 UTC, merged