feat(interaction.tooltip): add crosshairs, crosshairsX, crosshairsY setting
antvis/G2 pull request #6229
Opened 2024-05-12 06:45 UTC by Runtus

##### Checklist

- [x] `npm test` passes
- [x] benchmarks are included
- [x] commit message follows commit guidelines
- [x] documents are updated

##### Description of change
* 增加十字辅助线的设置，并增加了crosshairsX, crosshairsY配置接口。

<img width="684" alt="image" src="https://github.com/antvis/G2/assets/48038769/6b54b919-4388-48d6-9135-42df63e15e36">
<img width="635" alt="image" src="https://github.com/antvis/G2/assets/48038769/e0a2bc08-7c64-490e-96e4-4b20b9921826">

2024-05-12 10:06 UTC, hustcc commented on site/docs/manual/core/tooltip.zh.md
> +        strokeWidth: 4
还是要拍平，这个是一个配置规范。

2024-05-12 11:32 UTC, Runtus commented on site/docs/manual/core/tooltip.zh.md
> +        strokeWidth: 4
明白了 就全部设置为crosshairsxxxx, crosshairsXxxx, crosshairsYxxxx这样嘛

2024-05-21 07:44 UTC, pearmini requested changes

2024-05-21 07:44 UTC, pearmini commented on __tests__/plots/interaction/stocks-line-slider.ts
> +        crosshairsX: false,
crosshairX 现在默认的是开启的吗？如果保证兼容性，可以默认关闭，用户可以手动开启？

2024-05-21 12:28 UTC, pearmini commented on __tests__/plots/interaction/stocks-line-slider.ts
> +        crosshairsX: false,
是滴

2024-05-22 02:05 UTC, pearmini approved these changes

2024-05-22 02:11 UTC, pearmini commented
非常优秀！🚀

2024-05-22 02:11 UTC, merged