迁移 4.0 官网案例中一些简单的玫瑰图，下面红框中是最新添加的。
antvis/G2 pull request #6258
Opened 2024-05-31 03:04 UTC by the-lemonboy

### 迁移 4.0 官网案例中一些简单的玫瑰图，下面红框中是最新添加的。
<img width="1130" alt="image" src="https://github.com/antvis/G2/assets/64092696/fc205b9a-4040-4496-ae1b-ea3671e6a7b4">

2024-05-31 03:20 UTC, pearmini requested changes

2024-05-31 03:20 UTC, pearmini commented on site/examples/general/rose/demo/nightingale-rose.ts
> +  .encode('x', 'year')
`chart.xxx` 之间空一行，看上去更有“段落感 ”🤣

2024-05-31 03:20 UTC, pearmini commented on site/examples/general/rose/demo/polar-stack.ts
> +  .interval()
同上

2024-05-31 03:20 UTC, pearmini commented on site/examples/general/rose/demo/meta.json
> +    {
这些图片都是之前的图片吗？如果是的话，可以把新的图截图发给我，然后我上传图片之后把链接给你。

2024-05-31 03:32 UTC, the-lemonboy commented on site/examples/general/rose/demo/nightingale-rose.ts
> +  .encode('x', 'year')
好的

2024-05-31 03:37 UTC, the-lemonboy commented on site/examples/general/rose/demo/meta.json
> +    {
1、wind rose
<img width="693" alt="image" src="https://github.com/antvis/G2/assets/64092696/8bc16328-b5dd-47c2-a341-1f6021d6bc9d">
2、南丁格尔玫瑰图
<img width="625" alt="image" src="https://github.com/antvis/G2/assets/64092696/f720c903-a17d-4922-b5a9-9cff62c5d13d">
3、南丁格尔玫瑰环图
<img width="742" alt="image" src="https://github.com/antvis/G2/assets/64092696/055351fa-8a64-45e3-a037-861542f81390">
4、极坐标下的层叠柱状图
<img width="490" alt="image" src="https://github.com/antvis/G2/assets/64092696/b71e23cd-b6d3-459a-a73f-e45ce117c879">

2024-05-31 03:46 UTC, pearmini commented on site/examples/general/rose/demo/meta.json
> +    {
https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*pu1LTrmzMyUAAAAAAAAAAAAADmJ7AQ/original
https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*FZtzRbGNkRMAAAAAAAAAAAAADmJ7AQ/original
https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*dHw7RYx7V3cAAAAAAAAAAAAADmJ7AQ/original
https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*JWPuSIRzU_MAAAAAAAAAAAAADmJ7AQ/original

2024-05-31 05:42 UTC, pearmini approved these changes
🚀🚀🚀

2024-05-31 06:01 UTC, merged

2024-06-17 07:29 UTC, pearmini commented
感谢参与到 G2 的贡献中！感兴趣的话可以加入下面的贡献者群，了解更多的动态🤣

<img src="https://github.com/antvis/G2/assets/49330279/97c7220e-9671-463a-97b7-502dee68ff0d" width=400 />