fix: liquid data is not in object form antvis #6145
antvis/G2 pull request #6379
Opened 2024-07-22 11:30 UTC by the-lemonboy

修复liquid data不是{value:data}形式显示NaN问题。
![image](https://github.com/user-attachments/assets/36c2fa56-816a-468b-85f7-9bf2221fb73c)

2024-07-22 11:33 UTC, hustcc commented on src/composition/utils.ts
> +  if (isNumber(dataDescriptor)) return dataDescriptor;
我感觉这里可能有问题 @pearmini

2024-07-23 02:08 UTC, pearmini requested changes
非常感谢贡献！🙏

不过，可以参考 `__tests__/plots/static/liquid-default.ts` 添加一个测试案例，测试一下水波图的数据合并问题：

```ts
import { G2Spec } from '../../../src';

export function liquidNumber(): G2Spec {
  return {
    type: 'view',
    data: 0.3,
    children: [{ type: 'liquid' }],
  };
}

liquidNumber.skip = true;
```

运行 `npm run dev` 确保对应案例没有问题。

2024-07-23 02:08 UTC, pearmini commented on src/composition/utils.ts
> +  if (isNumber(dataDescriptor)) return dataDescriptor;
这里下面的写法也许更好？

```js
if(Arrray.isArray(dataDescriptor)) return dataDescriptor;
if(isObject(dataDescriptor)) {
  const { value = dataValue, ...rest } = dataDescriptor;
  return { ...rest, value };
};
return dataDescriptor;
```

这样可以保证以后数据是 boolean 或者 string 的情况。

2024-07-23 02:12 UTC, the-lemonboy commented
> 非常感谢贡献！🙏
> 
> 不过，可以参考 `__tests__/plots/static/liquid-default.ts` 添加一个测试案例，测试一下水波图的数据合并问题：
> 
> ```ts
> import { G2Spec } from '../../../src';
> 
> export function liquidNumber(): G2Spec {
>   return {
>     type: 'view',
>     data: 0.3,
>     children: [{ type: 'liquid' }],
>   };
> }
> 
> liquidNumber.skip = true;
> ```
> 
> 运行 `npm run dev` 确保对应案例没有问题。

好的，感谢提供思路。

2024-07-23 05:57 UTC, pearmini approved these changes
🚀🚀🚀

2024-07-23 05:58 UTC, merged