docs: add custom symbol demo
antvis/G2 pull request #6388
Opened 2024-07-26 04:33 UTC by wangxingkang

##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

2024-07-26 04:33 UTC, wangxingkang commented
<img width="714" alt="image" src="https://github.com/user-attachments/assets/9d9c21a4-daef-4808-a195-abef23c30736">

2024-07-26 05:35 UTC, pearmini commented
@wangxingkang 可以把截图中的 tooltip 去掉吗！

2024-07-26 05:36 UTC, pearmini requested changes

2024-07-26 05:36 UTC, pearmini commented on site/examples/component/legend/demo/symbol.ts
> +    ];
🎉

2024-07-26 05:41 UTC, wangxingkang commented on site/examples/component/legend/demo/symbol.ts
> +    ];
好的

2024-07-26 05:46 UTC, wangxingkang commented
<img width="704" alt="image" src="https://github.com/user-attachments/assets/41347be1-6065-4740-ab16-cdb7c6551a3d">

2024-07-26 05:47 UTC, wangxingkang commented
@pearmini 看下是否可以

2024-07-28 01:13 UTC, pearmini commented
@wangxingkang 可以的，我周一上传一下！

2024-07-29 02:12 UTC, pearmini commented
@wangxingkang 

https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*UM2yQKYXczEAAAAAAAAAAAAADmJ7AQ/original

2024-07-29 03:55 UTC, wangxingkang commented
@pearmini 可以了

2024-07-29 09:02 UTC, pearmini approved these changes
gooood!

2024-07-29 09:02 UTC, merged