feat: add columnWidthRatio configuration to the style of the interval
antvis/G2 pull request #6474
Opened 2024-09-24 08:31 UTC by interstellarmt

close #6386 
##### Checklist

- [x] `npm test` passes
- [x] benchmarks are included
- [x] commit message follows commit guidelines
- [x] documents are updated

##### Description of change
add columnWidthRatio configuration to the style of the interval.
You can refer to the example below for usage.
***example***：
style: { columnWidthRatio: 0.2 } or .style('columnWidthRatio', 0.2)
![image](https://github.com/user-attachments/assets/74f6e639-8724-415f-904d-1687e83f4135)

2024-09-24 11:31 UTC, hustcc commented on src/runtime/render.ts
> +  const optionsPre = optionPreprocess(options);
命名方式用动词+名词吧 preprocessOptions。

2024-09-24 11:36 UTC, hustcc commented on src/runtime/option-preprocess/index.ts
> +export function preprocess<T extends G2ViewTree = G2ViewTree>(options: T): T {
采用一种 flow 的方式去写，然后 flow 的每个函数都针对其中一个 style，并且命名保持一致。参考：https://github.com/antvis/G2Plot/blob/master/src/plots/pie/adaptor.ts#L325

```ts
function flow(...flows) {
  return flows.reduce((result, f) => {
      return f(result);
    }, param);
}
```

```ts
function columnWidthRatio(option) {
  return { ...options };
}
```

```ts
flow(columnWidthRatio)(options)
```

2024-09-24 13:36 UTC, hustcc requested changes

2024-09-24 13:36 UTC, hustcc commented on src/runtime/option-preprocess/index.ts
> +export function preprocess<T extends G2ViewTree = G2ViewTree>(options: T): T {
这个外面不需要用就不 export。

2024-09-24 13:36 UTC, hustcc commented on src/runtime/option-preprocess/index.ts
> +export function optionPreprocess<T extends G2ViewTree = G2ViewTree>(
这个方法名改成动词加名词，也算是方法名的一个命名规范。

2024-09-24 13:36 UTC, hustcc commented on src/runtime/render.ts
> +  const preprocessOptions = optionPreprocess(options);
preprocessedOptiond

2024-09-24 15:37 UTC, hustcc approved these changes

2024-09-24 15:38 UTC, merged

2024-10-16 13:22 UTC, pearmini commented on src/runtime/option-preprocess/style.ts
> +}
这段逻辑更好是放在 transform 里面：这是 G2 提供的增加一些语法糖的内置机制，这样就不需要修改 runtime 的代码了。可以参考这个PR https://github.com/antvis/G2/pull/5914