「wip」feat(transform): add exponential smoothing data transform methods
antvis/G2 pull request #6522
Opened 2024-11-15 10:07 UTC by lulusir

##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change
 add exponential smoothing data transform methods

![image](https://github.com/user-attachments/assets/d5d84fb5-12e1-4627-a5ea-f2d17474c49f)

2024-11-15 17:04 UTC, hustcc commented
这个算法有来源出处吗？以及使用场景？

2024-11-15 17:10 UTC, hustcc requested changes

2024-11-15 17:10 UTC, hustcc commented on site/docs/spec/data/ema.zh.md
> +对数据进行指数平滑
更详细一点的介绍，来源出处，场景等。

2024-11-15 17:10 UTC, hustcc commented on site/docs/spec/data/ema.zh.md
> +        "x": 1,
两个空格。

2024-11-15 17:10 UTC, hustcc commented on src/spec/dataTransform.ts
> +  field: string;
加一个可选参数 as，新增的字段名，默认值为 field，表示覆盖原字段数据。

2024-11-16 01:31 UTC, lulusir commented
> 这个算法有来源出处吗？以及使用场景？

好的，晚点补一下

2024-11-18 15:32 UTC, hustcc approved these changes

2024-11-19 02:55 UTC, merged